### ISSUE TITLE
Change logs link template

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#1056]
We should use the new format

{namespace="zombie-bd7e03796e90104f793bc741b39fa95a",pod="bob"}

**Comment by QuentinMoss** [comment]
@pepoviola I'll this one.

**Comment by bansaltushar014** [comment]
Hello @pepoviola  , I would like to work on this issue. Could you please assign it to me?

**Comment by pepoviola** [comment]
Hi @bansaltushar014, thanks for your interest. To give you more context, you need to change this line
https://github.com/paritytech/zombienet/blob/main/javascript/packages/utils/src/constants.ts#L2

and change this part
```
pod%3D~%5C%22{{namespace}}%2F{{podName}}
```

to use the new format

```
namespace%3D%22{{namespace}}%22%2Cpod%3D%22bob%22
```

Thanks!

**Comment by pepoviola** [comment]
Hi @bansaltushar014, any update on this one? I can pick up since we want to create a new release with this fix.
Thanks!
