### ISSUE TITLE
Support nimbus session keys

### ISSUE THREAD

**Issue by RomarQ** [paritytech/zombienet#1062]
### Is your feature request related to a problem? Please describe.

Related issue: https://github.com/paritytech/zombienet/issues/789

Currently I am facing the same problem described in the issue linked above, unfortunately the issue was closed without describing a solution.

I've integrated [nimbus](https://github.com/PureStake/nimbus) framework into a parachain, where session keys now contain a `nimbus` field to identify the nimbus consensus keys. The issue is that zombienet replaces the genesis session keys configuration with some [zombienet specific structure](https://github.com/paritytech/zombienet/blob/d6d46ff4f4711027bd4bd636acb01ad63de30bc0/javascript/packages/orchestrator/src/chainSpec.ts#L137) where a `nimbus` key is not provided.

Is there any easy way to fix this issue, without passing the chain_spec directly or adding `nimbus` field to this  struct [(orchestrator/src/chainSpec.ts)](https://github.com/paritytech/zombienet/blob/d6d46ff4f4711027bd4bd636acb01ad63de30bc0/javascript/packages/orchestrator/src/chainSpec.ts#L137)?

### Describe the solution you'd like

Reuse `nimbus` field (or any fields unknown by zombienet) when overriding the `session.key` config.

Original spec:

```json
"session": {
        "keys": [
          [
            "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
            "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
            {
              "nimbus": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
            }
          ]
        ]
      },
```

After zombienet overrides:

```json
"session": {
        "keys": [
          [
            "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
            "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
            {
              "grandpa": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
              "babe": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
              "im_online": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
              "parachain_validator": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
              "authority_discovery": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
              "para_validator": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
              "para_assignment": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
              "beefy": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
              "aura": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
              "nimbus": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
            }
          ]
        ]
      },
```

### Describe alternatives you've considered

Adding `nimbus` field here: [(orchestrator/src/chainSpec.ts)](https://github.com/paritytech/zombienet/blob/d6d46ff4f4711027bd4bd636acb01ad63de30bc0/javascript/packages/orchestrator/src/chainSpec.ts#L137)

**Comment by pepoviola** [comment]
Hi @RomarQ,  does `nimbus` use the same key scheme `sr25519`? And also should be only added for collators. In general we use the parachains registry to override this behavior, but I think we can add `nimbus` since could be multiple parachains that want to use it.

**Comment by RomarQ** [comment]
Hi @pepoviola, 

Yes, it uses the same key scheme. Here is the PR with the fix:  https://github.com/paritytech/zombienet/pull/1063
