### ISSUE TITLE
Add support for parachain prefunded accounts

### ISSUE THREAD

**Issue by sandreim** [paritytech/zombienet#1068]
Needed by https://github.com/paritytech/polkadot/issues/7249

**Comment by pepoviola** [comment]
Hi @sandreim, I will talk with @bredamatt to add this feature.
Thanks!

**Comment by bredamatt** [comment]
Thanks for opening the issue @sandreim

**Comment by pepoviola** [comment]
Hi @bredamatt / @sandreim , the `parachain` config allow to use the `genesis` key to override in the same way we do in the `relaychain`. If you have the accounts file pre-generated we can use the `{% include ...%}` syntax. 
I will work in an example an open a pr in polkadot repo.
Thanks!!
