### ISSUE TITLE
Storing number of tests that run in a lightweight database

### ISSUE THREAD

**Issue by emamihe** [paritytech/zombienet#1089]
Back to topic that we wanted to add the dashboard in observability metrics regarding having the number of successful and failed test pipelines. We need to store the statistics of success or failure somewhere like mysql which we can then scrape that metric it and put it in our reporting dashboards.

**Comment by pepoviola** [comment]
Thanks @emamihe, I think our needs fits to use `redis` as db, we can hosted in our cluster. wdyt?

**Comment by pepoviola** [comment]
Hi @emamihe, I think we need to brainstorming/rethink the metrics we want to track. I will closing this one here and add a followup topic to discuss with the team. Can you clean the infra deployed?
Thx!
