### ISSUE TITLE
Polkadot CI logs are unavailable

### ISSUE THREAD

**Issue by sandreim** [paritytech/zombienet#1090]
The logs are no longer available at the URLs dumped in CI - for example: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2890021

This slows down debugging as it requires the developer to always run the test locally, while it could have been easier to fix things just by inspecting the CI run logs.

	📓 To see the full logs of the nodes please go to:
	alice: https://grafana.parity-mgmt.parity.io/explore?orgId=1&left=%5B%221684944245150%22,%221684945034730%22,%22loki.parity-zombienet%22,%7B%22expr%22:%22%7Bpod%3D~%5C%22zombie-5ef799e98ab58e6266154cbdbefc57a1%2Falice%5C%22%7D%22,%22refId%22:%22A%22,%22range%22:true%7D%5D
	charlie: https://grafana.parity-mgmt.parity.io/explore?orgId=1&left=%5B%221684944245150%22,%221684945034730%22,%22loki.parity-zombienet%22,%7B%22expr%22:%22%7Bpod%3D~%5C%22zombie-5ef799e98ab58e6266154cbdbefc57a1%2Fcharlie%5C%22%7D%22,%22refId%22:%22A%22,%22range%22:true%7D%5D
	bob: https://grafana.parity-mgmt.parity.io/explore?orgId=1&left=%5B%221684944245150%22,%221684945034730%22,%22loki.parity-zombienet%22,%7B%22expr%22:%22%7Bpod%3D~%5C%22zombie-5ef799e98ab58e6266154cbdbefc57a1%2Fbob%5C%22%7D%22,%22refId%22:%22A%22,%22range%22:true%7D%5D
	dave: https://grafana.parity-mgmt.parity.io/explore?orgId=1&left=%5B%221684944245150%22,%221684945034730%22,%22loki.parity-zombienet%22,%7B%22expr%22:%22%7Bpod%3D~%5C%22zombie-5ef799e98ab58e6266154cbdbefc57a1%2Fdave%5C%22%7D%22,%22refId%22:%22A%22,%22range%22:true%7D%5D
	ParaId: 2000
		collator01: https://grafana.parity-mgmt.parity.io/explore?orgId=1&left=%5B%221684944245150%22,%221684945034730%22,%22loki.parity-zombienet%22,%7B%22expr%22:%22%7Bpod%3D~%5C%22zombie-5ef799e98ab58e6266154cbdbefc57a1%2Fcollator01%5C%22%7D%22,%22refId%22:%22A%22,%22range%22:true%7D%5D
	ParaId: 2001
		collator02: https://grafana.parity-mgmt.parity.io/explore?orgId=1&left=%5B%221684944245150%22,%221684945034730%22,%22loki.parity-zombienet%22,%7B%22expr%22:%22%7Bpod%3D~%5C%22zombie-5ef799e98ab58e6266154cbdbefc57a1%2Fcollator02%5C%22%7D%22,%22refId%22:%22A%22,%22range%22:true%7D%5D

**Comment by pepoviola** [comment]
Closing here @sandreim, thanks for reporting.
Thx!
