### ISSUE TITLE
[cli/orchestrator] Ensure node >= is used

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#1108]
Followup from https://github.com/paritytech/zombienet/issues/1106#issuecomment-1585696564, we should ensure (in runtime and with `.npmrc`) that minimum node version is meet.

**Comment by wirednkod** [comment]
It seems that we already have the `engine-strict: true` in all 3 packages in [cli](https://github.com/paritytech/zombienet/blob/main/javascript/packages/cli/.npmrc), [orchestrator](https://github.com/paritytech/zombienet/blob/main/javascript/packages/orchestrator/.npmrc), [utils](https://github.com/paritytech/zombienet/blob/main/javascript/packages/utils/.npmrc).
