### ISSUE TITLE
Custom log-level breaks the startup process

### ISSUE THREAD

**Issue by pgherveou** [paritytech/zombienet#1117]
### Is your feature request related to a problem? Please describe.

I was trying to configure my parachain with the following log level
```
  env = [{ name = "RUST_LOG", value = "error,runtime::contracts=debug" }]
```
so that, it's not too verbose and I only get the log events that I need for debugging.
Unfortunately, it looks like no logs is interpreted as a signal that something is not started correctly

```
Error: Log lines of process: 64378 ( node: collator-1 ) doesn't grow, please check logs at /Users/pg/Documents/zombienet/collator-1.log
```

### Describe the solution you'd like

Ideally setting a custom log level should not impact the "readiness" checks

### Describe alternatives you've considered

For now I can just use `info` as the default log level to workaround this.

**Comment by pepoviola** [comment]
Hi @pgherveou, thanks for your feedback. Make sense to `relax` the check in `native` and just ensure that the process is alive after a couple of secs. We will fix it and ping you to confirm.
Thanks!

cc @wirednkod / @l0r1s, same goes to the sdk.
