### ISSUE TITLE
assertion failed [block != nullptr]: BasicBlock requested for unrecognized address

### ISSUE THREAD

**Issue by brunopgalvao** [paritytech/zombienet#1124]
### Issue Description

When running:
```
zombienet-macos -p native spawn awesome-config.toml   
```
I get the following output:
```
assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
(BuilderBase.h:550 block_for_offset)
zsh: trace trap  zombienet-macos -p native spawn config-002.toml
```

### Steps to reproduce the issue

Steps to reproduce the issue
- Use Rust 1.68

### Describe the results you received

Describe the results you received

- An error

### Describe the results you expected

Describe the results you expected
- No error

### Zombienet version

1.3.56

### Provider

Native

### Provider version

```yaml
## For binaries
polkadot 0.9.40-a2b62fb872b
polkadot-parachain 0.9.380-fe24f39507f
```

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by brunopgalvao** [comment]
Solved by upgrading Rust from 1.68 to 1.70.0

**Comment by skunert** [comment]
I am still seing this from time to time both with rust current stable and 1.74.0 nightly.

```
zombienet --dir ~/work/current_zombienet -f --provider native spawn ./cumulus/zombienet/examples/small_network.toml;
assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
(BuilderBase.h:550 block_for_offset)
 error: Recipe `testnet` was terminated on line 28 by signal 5
```

**Comment by pepoviola** [comment]
Closing here, please re-open if needed @skunert / @brunopgalvao.
Thx!

**Comment by jmg-duarte** [comment]
Still happens using Polkadot SDK v1.11.0 and rustc 1.77
