### ISSUE TITLE
Nodes do not have their balance set by default

### ISSUE THREAD

**Issue by zdave-parity** [paritytech/zombienet#1154]
### Issue Description

The [network definition spec](https://paritytech.github.io/zombienet/network-definition-spec.html) says the default initial balance of a node is 2000000000000. This does not seem to be the case. By default it seems that _no_ balance is set. The dev chain spec has balances for alice, bob, and so on, so this is not really noticeable if you only use these node names. If however you use unconventional node names like so:

    [relaychain]
    default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
    default_command = "substrate"
    chain = "local"
    
      [[relaychain.nodes]]
      name = "george"
    
      [[relaychain.nodes]]
      name = "harry"

Then you get a "Stash does not have enough balance to bond" error when the final chain spec is built. Explicitly setting `balance = 2000000000000` for `george` and `harry` fixes the issue for the given network spec.

### Steps to reproduce the issue

1. Build the Substrate kitchen-sink node.
2. Create a `network.toml` file with the above contents.
3. Run `node packages/cli/dist/cli.js --provider native spawn network.toml`.

### Describe the results you received

Substrate panics generating the final chain spec: `Thread 'main' panicked at 'Stash does not have enough balance to bond.'`

### Describe the results you expected

Zombienet should either give nodes a default balance of 2000000000000, or the documentation should be updated to indicate that no balance is set by default. The former seems preferable to me.

### Zombienet version

33a5f83fcf12d330685e2610a94a5160064d5db7

### Provider

Native

### Provider version

Substrate kitchen sink node, don't think the version is really relevant.

### Upstream Latest Release

Yes

**Comment by pepoviola** [comment]
Hi @zdave-parity thanks for reporting, the balance should be set as described in the docs. We will fix asap. 

Thanks!
