### ISSUE TITLE
ZNDSL comments consisting of just # are not parsed properly

### ISSUE THREAD

**Issue by zdave-parity** [paritytech/zombienet#1156]
### Issue Description

The ZNDSL parser doesn't recognise comments which are just a # followed by a newline. It looks like the grammar rule for comments is:

    comment = ${ ("#" | "//") ~ (!NEWLINE ~ ANY)+ }

It should probably be:

    comment = ${ ("#" | "//") ~ (!NEWLINE ~ ANY)* }

ie `*` instead of `+` at the end.

### Steps to reproduce the issue

1. Add a # followed by a newline to a .zndsl file.
2. Pass the file to zombienet.

### Describe the results you received

Zombienet produces an error like:

     Error: 	 Error parsing file:  --> 5:1
      |
    5 | #
      | ^---
      |
      = expected EOI, name, sleep, or comment

### Describe the results you expected

The added comment should have no effect.

### Zombienet version

33a5f83fcf12d330685e2610a94a5160064d5db7

### Upstream Latest Release

Yes

**Comment by pepoviola** [comment]
Hi @zdave-parity, yes this is a bug in the grammar. We will fix asap, thanks for reporting.
Thx!
