### ISSUE TITLE
Error with kusama-asset-hub-local

### ISSUE THREAD

**Issue by wirednkod** [paritytech/zombienet#1172]
### Issue Description

When running a specific toml configuration with `kusama-asset-hub-local` as parachain the following error occurs

### Steps to reproduce the issue

1) Use the versions of zombienet, polkadot, polkadot-parachain as appear below.
2) Use the follow toml file:
```yaml
[relaychain]
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]
chain = "kusama-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 1000
chain = "asset-hub-kusama-local"
cumulus_based = true

  # run alice as parachain collator
  [[parachains.collators]]
  name = "alice"
  validator = true
  command = "polkadot-parachain"
  args = ["-lparachain=debug"]
```

### Describe the results you received

The following error appears:

Error:  	 Error: Command failed with exit code 101: bash -c polkadot-parachain build-spec --chain asset-hub-kusama-local --disable-default-bootnode > /tmp/zombie-f7f74f878cec72756e100a600127ed0d_-118113-gKNYukOHBohn/cfg/asset-hub-kusama-local-1000-kusama-local-plain.json
thread 'main' panicked at 'Failed to open file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', polkadot-parachain/src/command.rs:79:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Describe the results you expected

Zombienet should start with the topology described

### Zombienet version

1.3.60

### Provider

Native

### Provider version

```yaml
## For binaries
polkadot 0.9.43-ba42b9ce51d
polkadot-parachain 0.9.430-9cb14fe3cee
```

### Upstream Latest Release

Yes

### Additional information

Same error occurs with `kusama-asset-hub-local`, `kusama-asset-hub-dev` and `kusama-asset-hub`. Everythings seem to work fine with normal collator01

cc @tadeohepperle

**Comment by pepoviola** [comment]
Hi @wirednkod / @tadeohepperle, this is not an error related to `zombienet`. This version of polkadot-parachain `0.9.430-9cb14fe3cee` doesn't contains the renaming to `asset-hub`, so this chain `kusama-asset-hub-local` will not work.
Can you trying compile `master` and run again zombienet.

Thanks!

**Comment by pepoviola** [comment]
ping @wirednkod / @tadeohepperle, did you manage to test this with the latest polkadot-parachain version? Thx!

**Comment by wirednkod** [comment]
Testing with the following versions and the toml configuration above works:
```
polkadot 1.0.0-1ed6e2e50a4
polkadot-parachain 1.0.0-2306bfb7565
```

As a result I close this
