### ISSUE TITLE
Key type insertion selection

### ISSUE THREAD

**Issue by girazoki** [paritytech/zombienet#1185]
As of today, zombienet injects a bunch of key types in the key store to stay compatible with most of the chains, e.g.:

- `nimbus`
- `aura`
- `vrf`
- `granda`

It would be good if we could configure which of those keys we want to be inserted in the keystore. For instance we could have a flag in the 

`accepted_key_types: ["nimbus", "vrf"]
`
which would only insert `nimbus` and `vrf` keys in the keystore.

**Comment by pepoviola** [comment]
To give more context about this issue, the idea is to allow users to manage which keys are injected in the `keystore` for each node. By `default` we inject all the keys generated by the node automatically, with this change we want to change this [fn](https://github.com/paritytech/zombienet/blob/main/javascript/packages/orchestrator/src/keys.ts#L63).

I think we can name the config key `keystore_key_types` (and `default_keystore_key_types`), both are an array of `string` representing the available key types (e.g: ["nimbus", "vrf"] )

**Comment by girazoki** [comment]
yeah I think the naming is appropriate

**Comment by pepoviola** [comment]
Hi @girazoki, this is already part of the latest release. Can you check if cover your use-case?
Thanks!

**Comment by girazoki** [comment]
will do, and will let you know, thanks!
