### ISSUE TITLE
Allow group matching for metrics

### ISSUE THREAD

**Issue by sandreim** [paritytech/zombienet#119]
This is required to fully be able to use node groups.

`groupname: reports histogram polkadot_pvf_execution_time has 0 samples in buckets ["3", "4", "5", "6", "+Inf"] within 10 seconds`

 https://github.com/paritytech/polkadot/pull/4797#discussion_r813772765

**Comment by pepoviola** [comment]
Fixed by https://github.com/paritytech/zombienet/pull/166
