### ISSUE TITLE
Node companion pod support 

### ISSUE THREAD

**Issue by sandreim** [paritytech/zombienet#120]
This is needed to allow custom tools to be used in a zombienet test for native and k8s.

- Short term: prometheus metrics and health check support (`my-companion-0: is up`) 
- Longer term: backchannel integration if anything is needed .

**Comment by sandreim** [comment]
related https://github.com/paritytech/devops/issues/1451

**Comment by pepoviola** [comment]
Hi @sandreim does the image is already published to use?

**Comment by sandreim** [comment]
Yes, you can pull from here: https://hub.docker.com/r/paritytech/polkadot-introspector/tags

**Comment by pepoviola** [comment]
Hi @sandreim, this is already implementes (for `podman` and `k8s` providers). Is disabled by default and you can enable by set the key `polkador_instrospector` in the `settings`

```toml
[settings]
...
polkador_instrospector = true
```
