### ISSUE TITLE
Add support for new binaries (polkadot)

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#1202]
We should add support in our `setup` command for the upcoming new binaries in `polkadot`.
Reference issue: https://github.com/paritytech/polkadot/pull/7337#issuecomment-1650081554

We should download in the same directory and also set them as executable.

**Comment by wirednkod** [comment]
@pepoviola we have this issue: https://github.com/paritytech/zombienet/issues/434 is it relevant?

**Comment by mrcnski** [comment]
I've just merged https://github.com/paritytech/polkadot/pull/7337, so I can knock this out if no one's started on it yet?

**Comment by wirednkod** [comment]
@mrcnski Im on it - sorry did not assign it to me

**Comment by wirednkod** [comment]
@mrcnski Just to make sure we are on the same page - there will be no more `polkadot` binary? and it will split in these 2? Also can you please let me know if these binaries have official releases (and example links of those)?

**Comment by mrcnski** [comment]
> there will be no more polkadot binary? and it will split in these 2?

There is still the `polkadot` binary, those are two new ones in addition.

> Also can you please let me know if these binaries have official releases (and example links of those)?

I just merged the PR today so no official releases yet AFAIK. Let me know if any other questions. :)

**Comment by wirednkod** [comment]
Thank you @mrcnski . I will push a draft PR and add you as a reviewer - and wait for some release to test it - if you are ok with that

**Comment by mrcnski** [comment]
> Thank you @mrcnski . I will push a draft PR and add you as a reviewer - and wait for some release to test it - if you are ok with that

Perfect

**Comment by pepoviola** [comment]
@wirednkod just a heads-up since a new release will be soon available.
