### ISSUE TITLE
Add a flag on `setup` to download all binaries

### ISSUE THREAD

**Issue by wirednkod** [paritytech/zombienet#1209]
A new flag/option should be added to the command-line interface (CLI) tool's setup command. 

This flag would allow users to specify that they want to download all necessary binary files. By including this flag when executing the setup command, the CLI tool will automatically fetch and download the required binary files from their respective sources.

**Comment by pepoviola** [comment]
@wirednkod this is fix here https://github.com/paritytech/zombienet/pull/1208 right?

**Comment by wirednkod** [comment]
Yes @pepoviola
