### ISSUE TITLE
setup teleport

### ISSUE THREAD

**Issue by emamihe** [paritytech/zombienet#1216]
setting up teleport in our own env

**Comment by pepoviola** [comment]
> @pepoviola In order being able to integrate the teleport with github for the team of zombienet I need to have oauth app in organization level of paritytech in github can I have access? or either you please create the oauth app for teleport? https://github.com/organizations/paritytech/settings/applications

Great! I think we should ping devops to review the access?

**Comment by pepoviola** [comment]
ping @emamihe is this still `todo`?
