### ISSUE TITLE
Support chains without the balances pallet

### ISSUE THREAD

**Issue by zdave-parity** [paritytech/zombienet#1220]
Currently zombienet falls over generating the chain spec:

    Fail to add balance for nodes: [object Object],[object Object]
    
     Unexpected error:  	 TypeError: Cannot read properties of undefined (reading 'balances')

See [here](https://github.com/zdave-parity/polkadot-storage-chain/) for an example of a chain without the balances pallet.

### Describe the solution you'd like

Perhaps `addBalances` could just do nothing if `runtimeConfig.balances` doesn't exist. It would be good to fail if balances had been explicitly requested in the network spec though.

**Comment by pepoviola** [comment]
@zdave-parity / @NachoPal, released in `v1.3.64`.
Thanks!!
