### ISSUE TITLE
`ESM` and `CJS` dual support

### ISSUE THREAD

**Issue by timbrinded** [paritytech/zombienet#1221]
### Is your feature request related to a problem? Please describe.

Increasingly it is becoming harder to support CJS packages inside ESM repos, and unfortunately Zombienet has many CJS deps which are causing issues downstream, e.g. `libp2p-crypto`.

In terms of package support, there always tends to be ESM versions or dual support from the best teams. So in terms of "needing" a particular package, there are alternatives (except for very specific cases like zombienet).

### Describe the solution you'd like

Dual format publishing, which need not be **too** difficult to change the bundle process.

Modern bundlers like [tsup](https://github.com/egoist/tsup) make this pretty easy without config files required. The most onerous task will be changing things like file paths to use specify file extensions.

### Describe alternatives you've considered

Of course you can import CJS packages into ESM projects, but the problem is that Zombienet uses many old libraries which are unable to be properly bundled. These projects are years since last update, so i'm not confident they'll get updated soon.

### Additional context

Because of some of zombienet's deps it does cause issues with using Bun, which is a wonderfully fast alternative runtime to Node.js for Javascript execution on par with Rust (for some operations).

There are unavoidable issues like this for me:
```
❯ bun run src/cmds/entrypoint.ts
343 |     origin[keys[i]] = add[keys[i]];
344 |   return origin;
345 | }, kCustomPromisifiedSymbol = Symbol.for("util.promisify.custom"), promisify = function promisify2(original) {
346 |   if (typeof original !== "function")
347 | 
348 |     throw new TypeError('The "original" argument must be of type Function');
             ^
TypeError: The "original" argument must be of type Function
      at promisify2 (node:util:348:10)
      at /home/****/repo/node_modules/libp2p-crypto/src/keys/rsa.js:7:16
      at globalThis (/home/****/repo/node_modules/libp2p-crypto/src/keys/rsa.js:60:69)
      at /home/****/repo/node_modules/libp2p-crypto/src/keys/rsa-class.js:11:6
      at globalThis (/home/****/repo/node_modules/libp2p-crypto/src/keys/rsa-class.js:168:0)
      at /home/****/repo/node_modules/libp2p-crypto/src/keys/index.js:13:2
```
```[tasklist]
### Tasks
- [ ] Audit deps for updates
```

**Comment by pepoviola** [comment]
Hi @timbrinded, thanks for open this issue. At the moment we are working on the `v2` of zombienet and we definitely want to publish the new version as esm/cjs. Also, we should audit the current version to update the deps (e.g libp2p-crypto repo is archived and moved to https://github.com/libp2p/js-libp2p/tree/master/packages/crypto). I will add this task to this issue, but in the short term if you have a list of deps that are causing issues I can take a quick look.

Thanks!

**Comment by pepoviola** [comment]
Hi @timbrinded, sorry about the delay. I will close this one here since we are moving our focus and effort to v2 (https://github.com/paritytech/zombienet-sdk). Please re-open if this still causing friction on your side and I will try to fix it.

Thanks!!
