### ISSUE TITLE
Table output makes commands hard to copy

### ISSUE THREAD

**Issue by zdave-parity** [paritytech/zombienet#1261]
For example, I can't just copy the command out of this table because of the wrapping:

    ┌─────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────┐
    │ Pod                     │ temp-1                                                                                             │
    ├─────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┤
    │ Status                  │ Launching                                                                                          │
    ├─────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┤
    │ Command                 │ bash -c polkadot-bulletin-chain build-spec --chain /tmp/zombie-040bfb80bc11a29a72c64c              │
    │                         │ a065f568b8_-563482-DTasn5OvRUai/local-plain.json --disable-default-bootnode  --raw > /tmp/         │
    │                         │ zombie-040bfb80bc11a29a72c64ca065f568b8_-563482-DTasn5OvRUai/local-raw.json                        │
    └─────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────┘

### Describe the solution you'd like

Personally I would just drop the table stuff. As well as making things hard to copy, it uses a lot of terminal space. For the above, something like this would be fine:

    Launching pod 'temp-1' with command:
    bash -c polkadot-bulletin-chain build-spec --chain /tmp/zombie-040bfb80bc11a29a72c64ca065f568b8_-563482-DTasn5OvRUai/local-plain.json --disable-default-bootnode  --raw > /tmp/zombie-040bfb80bc11a29a72c64ca065f568b8_-563482-DTasn5OvRUai/local-raw.json

Any output format that allows me to easily copy the commands would probably be an improvement though.

**Comment by pepoviola** [comment]
Hi @zdave-parity, thanks for your feedback! At the moment we have two options, the table logging or `mute` the output. Maybe we can rework the logging to support more formats, wdyt @wirednkod ? I think implement a `json` output can be handy.

Thanks!

**Comment by wirednkod** [comment]
Thank you @zdave-parity for the feedback. I think the table is actually a good addition for grouping information together and making zombienet a bit more attractive to non-too-fond-of-terminal people. I think you have a point here and an alternative could be good to have (also maybe a per person configuration). Ill wrap my mind around it and put something together based on your feedback

**Comment by pepoviola** [comment]
Hi @zdave-parity, this change landed i our latest release (`v1.3.66`) and now you can now use `-l text` (table or silent) as output options.

Thx!
