### ISSUE TITLE
Chain spec in raw instead of json format when using custom parachain startup command

### ISSUE THREAD

**Issue by mikirov** [paritytech/zombienet#1265]
### Issue Description

Chain spec in raw instead of json format when using custom parachain startup command

### Steps to reproduce the issue

Steps to reproduce the issue
1. setup 2 simple relay nodes and 1 parachain collator node with custom command "moonbeam"
- file `test.zndsl`: 
``` # Description: PVF compilation time
Network: ./0002-parachains-pvf-execution-time-good.toml
Creds: config

# Check authority status.
alice: reports node_roles is 4

# Ensure parachains are registered.
alice: parachain 2000 is registered within 60 seconds

# Ensure parachains made progress.
alice: parachain 2000 block height is at least 10 within 200 seconds

# Check execution time.
# There are two different timeout conditions: BACKING_EXECUTION_TIMEOUT(2s) and
# APPROVAL_EXECUTION_TIMEOUT(6s). Currently these are not differentiated by metrics
# because the metrics are defined in `polkadot-node-core-pvf` which is a level below
# the relevant subsystems.
# That being said, we will take the simplifying assumption of testing only the
# 2s timeout.

# We do this check by ensuring all executions fall into bucket le="2" or lower.
# First, check if we have at least 1 sample, but we should have many more.
alice: reports histogram polkadot_pvf_execution_time has at least 1 samples in buckets ["0.01", "0.025", "0.05", "0.1", "0.25", "0.5", "1", "2"] within 30 seconds

# Check if we have no samples > 2s.
alice: reports histogram polkadot_pvf_execution_time has 0 samples in buckets ["1", "2", "3", "4", "5", "6", "8", "10", "12", "+Inf"] within 30 seconds
```
- file `test.toml`:
``` 
[settings]
timeout = 1000

[relaychain]
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

[relaychain.default_resources]
limits = { memory = "4G", cpu = "2" }
requests = { memory = "2G", cpu = "1" }

  [[relaychain.nodes]]
  name = "alice"
  args = [ "--alice", "-lparachain=debug,runtime=debug" ]

  [[relaychain.nodes]]
  name = "bob"
  args = [ "--bob", "-lparachain=debug,runtime=debug"]

[[parachains]]
id = 2000
genesis_wasm_path="./wasm/orig.wasm.hex"
cumulus_based = true

  [parachains.collator]
  name = "collator01"
  command = "moonbeam"
  prometheus_prefix = "moonbeam_substrate"
  args = ["-lparachain=debug"]
```
- The wasm file is exported through `moonbeam export-genesis-wasm > ./wasm/orig.wasm.hex`
3.Running the test using `zombienet -p native -c 1  test.zndsl`
4. The output shows the following command being executed: `bash -c moonbeam build-spec  --disable-default-bootnode > /tmp/zombie-ed08b1793ef499e0a6189d8183f…`
4. Straight afterwards i get the warning: `Warning message "Chain Spec for paraId 2000 was set to a file in raw format, can't customize`.

### Describe the results you received

raw file outputed instead of json

### Describe the results you expected

json file outputted from build-spec command

### Zombienet version

1.3.65

### Provider

Native

### Provider version

```yaml
## For binaries
polkadot 0.9.40-a2b62fb872b
polkadot-parachain 0.9.380-fe24f39507f 

## For Kubernetes/Podman
podman version 4.4.1

OR

kubectl version v0.26.3
cluster version 1.25.2
```

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by wirednkod** [comment]
Thank you @mikirov for reporting this. Can you please provide the configuration and test files that you are using?

**Comment by pepoviola** [comment]
Hi @mikirov, thanks for your feedback. In this case the moonbeam binary export a `raw` chain-spec in the default chain. Can you set the chain to `"moonbase-local"` to get a `plain` version. 

```toml
[[parachains]]
id = 2000
genesis_wasm_path="./wasm/orig.wasm.hex"
chain = "moonbase-local"

  [parachains.collator]
  name = "collator01"
  command = "moonbeam"
  prometheus_prefix = "moonbeam_substrate"
  args = ["-lparachain=debug"]
```

Thanks!

**Comment by mikirov** [comment]
I can and it removed the error, however I'm unable to produce any blocks in the parachain with this configuration. The relay chain nodes are producing blocks, however the collator is staying at 0. The collator logs say "wasm: unreachable" error when validating the block. Could it be that polkadot is not compatible with the specific moonbeam version?

**Comment by pepoviola** [comment]
> Could it be that polkadot is not compatible with the specific moonbeam version?

I'm not sure about it, does work without pass the `wasm` in the config?

**Comment by pepoviola** [comment]
Hi @mikirov, are you still working on this?
Thx!
