### ISSUE TITLE
Question: Is testing Host API, SCALE encoding/decoding, Trie proof verification possible?

### ISSUE THREAD

**Issue by vikinatora** [paritytech/zombienet#1276]
### Is your feature request related to a problem? Please describe.

Hey, our team is wondering if any of the testing vectors from the title are currently possible with Zombienet?

### Describe the solution you'd like

The team is trying to build a Host testing suite and we believe Zombienet could be used to run tests in a Host agnostic way.

### Describe alternatives you've considered

We've looked at polkadot-tests repo but we don't like the existing "adapter" approach as it couples the tests with every Host implementation

**Comment by pepoviola** [comment]
Hi @vikinatora, sorry about the delay. From zombienet's point of view we test polkadot as a black-box, we can customize the way we start the process (and the chain-spec) and interact through rpc, get metrics or even run scrips in the same `pod`. So, if you build a custom binary that we can run and expose a way to interact we can adjust the spawning/test-runnner to allow call the needed APIs. Please ping me if you have questions or need something from out team.

Thx!

**Comment by pepoviola** [comment]
Hi @vikinatora, closing here. Please re-open if you have questions.
Thx!!
