### ISSUE TITLE
Zombienet ignores --reserved-nodes arg for collators

### ISSUE THREAD

**Issue by skunert** [paritytech/zombienet#1360]
### Issue Description

We have a test in cumulus `0002-pov_recovery` that specifies some relay chain arguments for the collator. It is supposed to start with a `--reserved-nodes` flag. However apparently the CLI flag that was specified in the test toml is not passed to the actual node.

From the logs:
```
test-parachain --name two --node-key 3fc4ccfe745870e2c0d99f71f30ff0656c8dedd41cc1d7d3d376b0dbe685e2f3 --chain /cfg/rococo-local-2000.json --base-path /data --listen-addr /ip4/0.0.0.0/tcp/30333/ws --prometheus-external --rpc-cors all --unsafe-rpc-external --rpc-methods unsafe --prometheus-port 9615 --rpc-port 9944 -lparachain::availability=trace,sync=debug,parachain=debug,cumulus-pov-recovery=debug,cumulus-consensus=debug --disable-block-announcements --bootnodes /ip4/10.24.23.119/tcp/30333/ws/p2p/12D3KooWRkZhiRhsqmrQ28rt73K7V3aCBpqKrLGSXmZ99PTcTZby --relay-chain-rpc-url ws://ferdie.zombie-b4eaaaff1ff0d70aeb3d08be83227b36.svc.cluster.local:9944 -- --base-path /relay-data --chain /cfg/rococo-local.json --execution wasm --port 39937 --rpc-port 45669
```

- [Full logs link](https://grafana.teleport.parity.io/explore?orgId=1&left=%7B%22datasource%22:%22PCF9DACBDF30E12B3%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22PCF9DACBDF30E12B3%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22%7Bnamespace%3D%5C%22zombie-b4eaaaff1ff0d70aeb3d08be83227b36%5C%22,pod%3D%5C%22two%5C%22%7D%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%221695108131286%22,%22to%22:%221695109522247%22%7D%7D) 
- [Job link](https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3739273)
- [Test toml](https://github.com/paritytech/polkadot-sdk/blob/master/cumulus/zombienet/tests/0002-pov_recovery.toml#L75)

### Steps to reproduce the issue

- happens on Ci

### Describe the results you received

--reserved-nodes is not passed

### Describe the results you expected

--reserved-nodes is passed

### Zombienet version

CI version

### Provider

Kubernetes

### Provider version

```yaml
-
```

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by pepoviola** [comment]
Hi @skunert, thanks for reporting I will take a look asap.
