### ISSUE TITLE
chore(nix): flake deps to be up to date with package.lock solution

### ISSUE THREAD

**Issue by dzmitry-lahoda** [paritytech/zombienet#1365]
### Is your feature request related to a problem? Please describe.

when js deps update, they break nix as it became unverified (deps vendor hash different).

unfortunately NIX not yet integrated SRI from NPM.

so need to make nix lock and js lock to be in sync

https://github.com/paritytech/zombienet/blob/d57fe654dcf870df9025806bfc6aa989582199a1/flake-module.nix#L11

### Describe the solution you'd like

so solution can be:
1. CI job to fail merge if nix not updated (requires nix action in CI + cache)
2. nix shell command to generate new hash and put into code (it is up to user to commit updated file)

good: nix will not be broken
bad: will require non nix devs to be aware of nix

### Describe alternatives you've considered

Wait NIX to support NPM SRI
```[tasklist]
### Tasks
```

**Comment by dzmitry-lahoda** [comment]
unfortunately company shifted works for now from polkadot to cosmos and ethereum, so i doubt will work on this next 3 month.

**Comment by dzmitry-lahoda** [comment]
also would be nice to update to latest nix as NPM support improved

**Comment by dzmitry-lahoda** [comment]
alternative is to use https://github.com/nix-community/napalm - will donate 100 USD in crypto for solution without hash

**Comment by pepoviola** [comment]
Hi @dzmitry-lahoda, closing here since this is now auto-updated thanks to https://github.com/paritytech/zombienet/pull/1600.
