### ISSUE TITLE
allow to collect zipkin span info with grafana tempo

### ISSUE THREAD

**Issue by drahnr** [paritytech/zombienet#140]
When launching a node, tracking jaeger spans aka zipkin spans to the _locally_ spawned grafana cluster for the `containerized` and `native` targets, and for a provided url for `native` and `kubernetes` targets.

**Comment by pepoviola** [comment]
`jaeger-agent` and needed config added in https://github.com/paritytech/zombienet/pull/149/files. I will  write the documentation of this feature before close this one.
Thanks!

**Comment by drahnr** [comment]
There is also related work in the https://github.com/paritytech/polkadot-introspector/issues/25

**Comment by pepoviola** [comment]
> There is also related work in the [paritytech/polkadot-introspector#25](https://github.com/paritytech/polkadot-introspector/issues/25)

Yes, we can talk about the assertion expression to match.

**Comment by pepoviola** [comment]
Hi @drahnr, zipkin span support was added by https://github.com/paritytech/zombienet/pull/171.
Closing here, thanks!!
