### ISSUE TITLE
Error when trying to spawn network in kubernetes 

### ISSUE THREAD

**Issue by wirednkod** [paritytech/zombienet#1412]
While trying to spawn a network in kubernetes the following error appeared:

```
➜  javascript git:(main) ✗ npm run zombie -- spawn ../tests/chaos/0001-delay.toml

> zombienet@0.1.0 zombie
> node ./packages/cli/dist/cli.js spawn ../tests/chaos/0001-delay.toml

╔════════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ 🧟 Zombienet 🧟    │ Initiation                                                                                         ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Provider           │ kubernetes                                                                                         ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Namespace          │ zombie-ef4976230e7e09608e35a4bb97d075d0                                                            ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Temp Dir           │ /var/folders/7q/3ws1fn9d0pn961zh9fk5vgm40000gn/T/zombie-ef4976230e7e09608e35a4bb97d075d0_-40811-d… ║
╚════════════════════╧════════════════════════════════════════════════════════════════════════════════════════════════════╝
Error:  	 Error: Command failed with exit code 1: kubectl --kubeconfig /Users/wirednkod/.kube/config apply -f -
Error from server (NotFound): error when creating "STDIN": namespaces "zombie-b3b08c66fc8e8e48d2876049d4477f7e" not found
Error from server (NotFound): error when creating "STDIN": namespaces "zombie-b3b08c66fc8e8e48d2876049d4477f7e" not found
Error from server (NotFound): error when creating "STDIN": namespaces "zombie-b3b08c66fc8e8e48d2876049d4477f7e" not found
Error from server (NotFound): error when creating "STDIN": namespaces "zombie-b3b08c66fc8e8e48d2876049d4477f7e" not found

undefined
┌────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Node'              │ /var/folders/7q/3ws1fn9d0pn961zh9fk5vgm40000gn/T/zombie-ef4976230e7e09608e35a4bb97d075d0_-40811-d… │
│ s logs:            │                                                                                                    │
│ m                  │                                                                                                    │
└────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────┘

 Error:  	 Error: Command failed with exit code 1: kubectl --kubeconfig /Users/wirednkod/.kube/config delete podmonitor zombie-ef4976230e7e09608e35a4bb97d075d0 -n monitoring
Error from server (NotFound): podmonitors.monitoring.coreos.com "zombie-ef4976230e7e09608e35a4bb97d075d0" not found
```

After investigating a bit more with @emamihe he realised that the CLI was using a previously spawned namespace (`error when creating "STDIN": namespaces "zombie-b3b08c66fc8e8e48d2876049d4477f7e" not found`). 

We changed back to default by using the command:
```
kubectl config set-context --current --namespace default
```
And everything seemed to work normally again

**Comment by pepoviola** [comment]
Hi @wirednkod, I don't think this should categorize as `bug`. The main issue here was that you have the context of `kubectl` set to a different namespace (than `default`). This is something we can add as instruction to run zombienet and we can also check at start and print a warning but I think is more related to `docs`.
Thx!

**Comment by pepoviola** [comment]
TODO: Make clear in the docs that you need to be set in the `default` namespace to start working with zombienet. Also note that this is the default behavior of `kubectl` so if someone change the context is because is aware of this.

**Comment by Neyromancer** [comment]
hey guys, may i take this issue?

I am very new to the project and i've just started to look around so it could take some time as.

**Comment by Neyromancer** [comment]
Hello, could anybody validate/review [PR](https://github.com/paritytech/zombienet/pull/1442) on updating docs plz?

**Comment by Neyromancer** [comment]
Hello @wirednkod @pepoviola, i think i corrected all the comments left for [PR](https://github.com/paritytech/zombienet/pull/1442) if everything is fine then let's merge it

**Comment by Neyromancer** [comment]
Hello, why when i use mdbook build i get a lot more changes then my updates to *.md files could produce?
Could it relat to the version of the mdbook tool? If so should i accept all the changes and add them as new html book?

**Comment by Neyromancer** [comment]
updated docs ([PR #1503](https://github.com/paritytech/zombienet/pull/1503)) files from new mdbook version (v0.4.35)

**Comment by Neyromancer** [comment]
Thank you for letting me to participate in the project and for your active collaboration however i will not be able to continue.

**Comment by pepoviola** [comment]
Hey @wirednkod, I will close this one. We can re-open if needed later.
Thx!
