### ISSUE TITLE
Deploy collators only infrastructure.

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/zombienet#1416]
### Is your feature request related to a problem? Please describe.

When an infrastructure is triggered locally with zombienet, the architecture remains static, meaning that new collators and/or new parachains cannot be added once the network was launched already (this is my understanding at least).

### Describe the solution you'd like

Once the relay chain is up and running, triggered from Zombienet, we can trigger a different zoimbienet process where we can add:

- New collators to a registered and running parachain from the previous zombienet execution.
- New parachain with it's set of collators (including it's registration process).

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by wirednkod** [comment]
Thank you @hbulgarini . This is a functionality that will be addressed with the upcoming [Zombienet-SDK](https://github.com/paritytech/zombienet-sdk). There are already some working minimum examples.

**Comment by pepoviola** [comment]
We will close this one and I will ping you when is ready to test in new `sdk` (Our idea is to have this feature in native by the end of the week).
