### ISSUE TITLE
Can't spawn zombienetwork

### ISSUE THREAD

**Issue by Daanvdplas** [paritytech/zombienet#1435]
### Issue Description

Zombienetwork doesn't spawn successfully.

### Steps to reproduce the issue

Config is very minimal, just want to spawn two rococo nodes and one parachain validator.

### Describe the results you received

See logs

### Describe the results you expected

A running network

### Zombienet version

Latest

### Provider

Native

### Provider version

```yaml
Using binaries of polkadot (v1.1.0) and custom parachain-node-template (v1.1.0)
```

### Upstream Latest Release

Yes

### Screenshots

<img width="1440" alt="Screenshot 2023-10-19 at 13 19 26" src="https://github.com/paritytech/zombienet/assets/93204684/16f83b36-6e93-4b87-8567-f7a1fee016e5">

<img width="1153" alt="Screenshot 2023-10-19 at 13 23 35" src="https://github.com/paritytech/zombienet/assets/93204684/63b41c6e-bf77-41c9-b1e8-c12e6b6f30de">

**Comment by pepoviola** [comment]
Hi @Daanvdplas,  Can you check if all the nodes are running? you can also check the logs of each one (the path to the logs should be printed in the spawn phase). Also, can you share the config to try on my end.
Thx!

**Comment by Daanvdplas** [comment]
config:
```
[relaychain]
chain = "rococo-local"
default_command = "./bin/polkadot"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 2000
addToGenesis = true
cumulus_based = true

  [parachains.collator]
  name = "parachain-collator01"
  command = "./target/release/parachain-template-node"
  ```

**Comment by wirednkod** [comment]
@Daanvdplas Just checked with your configuration (I am using the `polkadot-parachain` command for the collator) and everything seems to work fine and network is spawned. Can you please elaborate what is the `parachain-template-node` you are using and the rest of setup (e.g. do have you inside the same directory as `polkadot`, the `polkadot-execute-worker` and `polkadot-prepare-worker` binaries)

**Comment by Daanvdplas** [comment]
> do have you inside the same directory as polkadot, the polkadot-execute-worker and polkadot-prepare-worker binaries

This is something new for me, I'll have a look and come back!

**Comment by Daanvdplas** [comment]
Thanks it works now!

**Comment by wirednkod** [comment]
> > do have you inside the same directory as polkadot, the polkadot-execute-worker and polkadot-prepare-worker binaries
> 
> This is something new for me, I'll have a look and come back!

FWIW this is an addition that arrived with polkadot v1.0

**Comment by Daanvdplas** [comment]
https://substrate.stackexchange.com/questions/10263/running-zombienet-with-release-polkadot-v1-0-0
