### ISSUE TITLE
extrinsic-based tests

### ISSUE THREAD

**Issue by bernardoaraujor** [paritytech/zombienet#144]
Recently we started the [Ecosystem Performance Benchmarks](https://github.com/paritytech/ecosystem-performance-benchmarks) initiative. The idea came from a call the Ecosystem Success team had with @bkchr and some teams (Acala, Astar, Enjin and Moonbeam) to discuss many topics around Parachain Performance.

The goal of this effort is to aggregate tests from the Polkadot Ecosystem into a single repository, where we can share insights into extrinsics performance.

However, after reading the [Test DSL specs](https://github.com/paritytech/zombienet/blob/main/docs/test-dsl-definition-spec.md), I'm unsure if the DSL currently allows for the kind of testing we wanted to do. So I'm writing this issue to clarify: would it be possible for us to use zombienet to compose batch extrinsic calls and collect data from their execution? Or is that something zombienet is just not meant to do?

**Comment by pepoviola** [comment]
Hi @bernardoaraujor, the `DSL specs` document is outdated and some assertions are missed. One of the missing features is to run custom javascript assertions, allowing to interact with the network through polkadotjs api.

This assertion allow users to pass a javascript file that must export a `run` function that will be called by zombienet with the `name` of the node, the network information and any other argument set in the assertion and can assert the return value.

Here is a simple examples https://github.com/paritytech/zombienet/blob/main/tests/0008-custom-js.feature

Also, I continue working on new features and we can add more assertions to abstract the cases you need to simplify the feature file and reduce the number of custom logic you need to write.

Thanks!

**Comment by bernardoaraujor** [comment]
I was focused only on `docs` and `examples` directories, I missed `tests`.
Maybe it would be less confusing is `examples` and `tests` were the same directory?

Anyways thanks for the answer @pepoviola

**Comment by pepoviola** [comment]
> I was focused only on `docs` and `examples` directories, I missed `tests`. Maybe it would be less confusing if `examples` and `tests` were the same directory?
> 
> Anyways thanks for the answer @pepoviola

Yes, improve the docs and make the onboarding smooth is one of the ongoing tasks.
