### ISSUE TITLE
Filtering the `--alice` flag is too aggressive

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/zombienet#1448]
### Issue Description

I'm building a parachain with the [Tuxedo](https://github.com/Off-Narrative-Labs/Tuxedo) runtime framework instead of frame. My work is in this pr: https://github.com/Off-Narrative-Labs/Tuxedo/pull/130.

Unlike, FRAME, the Tuxedo runtime does not store the Aura keys in the chain spec, and therefore, zombienet cannot fetch them from the spec. It even prints a helpful warning about this `⚠ aura keys not found in runtimeConfig`.

This is because for now we just hard code the keys in the runtime. And we rely on the `--alice` flag to insert the keys into the keystore. We have a session key management system in mind to build eventually, but it still will not match the same format as FRAME.

I'm not requesting zombienet to add full support for the exotic stuff I'm trying, but I do **request that there is some way not to filter the `--alice` flag**.

For example, maybe when you detect that the aura keys are not in the spec (there is already a warning for that, remember) then you don't filter the keystore related flags. Or maybe you add an option to zombienet like `--dont-filter-cli-flags-i-know-what-im-doing`.

In the meantime, I was able to [hack around the problem](https://github.com/Off-Narrative-Labs/Tuxedo/pull/130/commits/eed24566b540b753f58d4c93e7dfe7bacdc22cdc) by adding another cli flag that does the same thing but has a different name. But ideally that won't be required long term.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Checkout the Tuxedo repository and build the collator
2. Build the polkadot validator
3. `zombienet -p native spawn tuxedo/zombienet.toml`

### Describe the results you received

The `--alice` flag is removed from my args even when I explicitly include it.

### Describe the results you expected

The flags I put in the config will be used (otherwise I wouldn't have put them there).

### Zombienet version

1.3.71

### Provider

Native

### Provider version

```yaml
## For binaries
polkadot v1.2.0
tuxedo parachain-template-node [eed24566b540b753f58d4c93e7dfe7bacdc22cdc](https://github.com/Off-Narrative-Labs/Tuxedo/pull/130/commits/eed24566b540b753f58d4c93e7dfe7bacdc22cdc)
```

### Upstream Latest Release

Yes

### Additional information

The Tuxedo parachain work is supported by a [w3f grant](https://github.com/w3f/Grants-Program/pull/1932). As was Tuxedo itself by a [previous grant](https://github.com/w3f/Grants-Program/pull/1517)

**Comment by pepoviola** [comment]
Hi @JoshOrndorff, nice to hear from you :) Yes, we may have a too aggressive filtering logic trying to minimize the friction and reduce the issues on parsing/generating the end cmd to execute. Using a flag like `--dont-filter-cli-flags-i-know-what-im-doing` and allow expert mode sounds good, but we can also check if the node name **is** alice and is set to be a validator before filtering `--<well known name>` flag. Did the last approach resolve your case?

**Comment by JoshOrndorff** [comment]
Nice to see you as well!

I didn't totally understand your proposed alternative approach. Can you detail it a little bit?

In the end, I just need some reliable way to make sure that the `--alice` flag actually ends up in the cli parameters that get passed to the parachain binary. Anything that makes that possible is good for me.

**Comment by pepoviola** [comment]
Hi @JoshOrndorff, sorry about the delay. The change that I have in mind is to `not filter` flags like `--<well know account` (e.g alice, bob, etc) if the node name match with the account (and is a validator) in the network definition.

For example, if you use this network definition like this

```toml
[relaychain]
default_image = "docker.io/parity/polkadot:latest"
default_command = "/tmp/polkadot-sdk/target/release/polkadot"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  args = [ "--alice" ]

  [[relaychain.nodes]]
  name = "bob"
  validator = false
  args = [ "--bob" ]

  [[relaychain.nodes]]
  name = "david"
  args = [ "--dave" ]
```

We match the flag with the node name and we don't remove the flag for `alice` but we remove it for `bob` and `david` (since bob is set to not be a validator and david didn't match with the flag). I think this behavior will work on your use-case right?

Thx!

**Comment by pepoviola** [comment]
Hi @JoshOrndorff, the fix landed in `main` and I will create a new release later today.
Thx!!

**Comment by muraca** [comment]
Hey @pepoviola here to confirm that everything works as expected. Thanks!

Before:
![Before](https://github.com/paritytech/zombienet/assets/56828990/90c05a9d-49a1-41d6-97e9-216285f4b063)

After:
![After](https://github.com/paritytech/zombienet/assets/56828990/109896eb-3dd8-47c1-a760-405e3e38f80e)

**Comment by pepoviola** [comment]
Thanks @muraca!!
