### ISSUE TITLE
Is there a way to specify the chain spec as a path to a file to be used for the collator?

### ISSUE THREAD

**Issue by sebastianmontero** [paritytech/zombienet#1589]
### Is your feature request related to a problem? Please describe.

I would like to test a runtime upgrade, so I would like to start the parachain using the original chain spec file, so that I can then test the runtime upgrade, is this possible? Or what is the way to go about this?

### Describe the solution you'd like

I would like to start the parachain using the original chain spec file

**Comment by pepoviola** [comment]
Hey @sebastianmontero, you can set the path to the chain-spec of the parachain using the chain_spec_path key at parachain level. Let me know if you have questions or need help.

Thanks!!

**Comment by sebastianmontero** [comment]
Thanks @pepoviola! That seems to have worked, but I do see a warning saying `Chain Spec for paraId 2000 was set to a file in raw format, can't customize. ` is that a problem?

**Comment by pepoviola** [comment]
Hi @sebastianmontero, thanks for your feedback. When you supply a `chain-spec` file in raw format zombiener can't make some customizations (e.g adding keys for collators, balances, etc) and that why that warning in show. We still change some keys like `para_id`/ `paraId` if those are present.

Related to the `plain` version and the error, that look like a bug. Can you post your config and chain-spec plain file here to reproduce?
Thx!

**Comment by sebastianmontero** [comment]
Thanks @pepoviola! 
If the parachainId is changed, what would be the reason that in the pallet parachaininfo -> parachainid I still see the original parachainId?

Here is the config file:

```
[relaychain]
default_image = "parity/polkadot:latest"
default_command = "polkadot"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 2000
cumulus_based = true
chain_spec_path = "/vsc-workspace/hashed-substrate-parachain/resources/md5-collator-spec.json"

  # run charlie as parachain collator
  [[parachains.collators]]
  name = "charlie"
  validator = true
  command = "../target/release/hashed-parachain"

```

And here is the chain-spec:
https://github.com/hashed-io/hashed-substrate-parachain/blob/feature/bump-v1.3.0-with-migrations/resources/md5-collator-spec.json

**Comment by sebastianmontero** [comment]
Just wanted to add that I was having an issue when performing the runtime upgrade, the parachain stopped producing blocks after calling the enactAuthorizedUpgrade, and the way I manged to solve the issue was by setting in the config file the parachain id to the one in the chain-spec.

**Comment by pepoviola** [comment]
Thanks for adding the update @sebastianmontero! I will close here this one and please re-open if needed.
Thanks again for your feedback!
