### ISSUE TITLE
Is there any way to adding signed extensions in test script

### ISSUE THREAD

**Issue by sweatpotato13** [paritytech/zombienet#1603]
### Is your feature request related to a problem? Please describe.

Is there any way to add custom signed extension?

```typescript
export const run = async (nodeName: any, networkInfo: any, args: any) {
    const {wsUri, userDefinedTypes} = networkInfo.nodesByName[nodeName];
    const api = await zombie.connect(wsUri, userDefinedTypes);

    const acc = args[0] === "alice" ? ALICE : BOB;
    const balance = await api.query.system.account(acc);

    console.log(`Current balances for ${args[0]} is ${balance.data.free}`);
    return balance.data.free;
}
```

`zombie.connect` get types only

### Describe the solution you'd like

Maybe can add `signedExtension` params in connect function

**Comment by pepoviola** [comment]
Hey @sweatpotato13, thanks for your feedback!! The `connect` method is just a helper to easily connect inside `js` test but the `ApiPromise` and `WsProvider` are also exposed to use, so you can construct your connection using those and passing the params that you need. Something like this should work.

```ts
const {wsUri, userDefinedTypes} = networkInfo.nodesByName[nodeName];
const provider = new zombie .WsProvider(wsUri);
const api = new zombie.ApiPromise({ provider, types: userDefinedTypes, signedExtension });
await api.isReady;
```

Thanks!!
