### ISSUE TITLE
Error: Cannot find tx.balances.transfer

### ISSUE THREAD

**Issue by 7flash** [paritytech/zombienet#1620]
### Issue Description

When running polkadot normally I can follow these docs to enable palettes, but how to do with zombienet?

https://docs.substrate.io/tutorials/build-application-logic/add-a-pallet/

### Steps to reproduce the issue

Steps to reproduce the issue
1. run
```
./zombienet-macos -p native spawn ./zombienet/examples/0000-test-config-small-network.json
```

2. run
```
polkadot-js-api tx.balances.transfer 5HpG9w8EBLe5XCrbczpwq5TSXvedjrBGCwqxK1iQ7qUsSWFc 1 --seed "//Alice" --ws ws://localhost:59587
```

### Describe the results you received

```
2023-12-25 12:32:58        API/INIT: rococo/1005000: Not decorating runtime apis without matching versions: ParachainHost/9 (1/2/3/4/5 known)
2023-12-25 12:32:58        API/INIT: rococo/1005000: Not decorating unknown runtime apis: 0xfbc577b9d747efd6/1
Error: Cannot find tx.balances.transfer, your chain doesn't have the transfer exposed in the balances pallet
```

### Describe the results you expected

Expected to work with existing polkadot config with palettes enabled?

### Zombienet version

master branch

### Provider

Native

### Provider version

```yaml
## For binaries
polkadot 0.9.40-a2b62fb872b
polkadot-parachain 0.9.380-fe24f39507f 

## For Kubernetes/Podman
podman version 4.4.1

OR

kubectl version v0.26.3
cluster version 1.25.2
```

### Upstream Latest Release

Yes

**Comment by pepoviola** [comment]
Hi @7flash, thanks for your feedback. A couple of questions:
1. Are you using the example config from the repo? (./zombienet/examples/0000-test-config-small-network.json)
2. If 1. is true, did you compile `polkadot` and the binary is available in your $PATH?
3. You can change the `default_command` key in the config to make sure you are using the binary that you compiled.

Thanks!

**Comment by 7flash** [comment]
> Hi @7flash, thanks for your feedback. A couple of questions:
> 
> 1. Are you using the example config from the repo? (./zombienet/examples/0000-test-config-small-network.json)
> 2. If 1. is true, did you compile `polkadot` and the binary is available in your $PATH?
> 3. You can change the `default_command` key in the config to make sure you are using the binary that you compiled.
> 
> Thanks!

Yes that's right, so.. how do I enable balance palette?

**Comment by pepoviola** [comment]
Hi @7flash, sorry about the delay. You need to use one of the available methods (e.g `transferKeepAlive`, `transferAllowDeath`). You can always `spawn` the network and use polkadotjs links to interact with the network


<img width="1476" alt="image" src="https://github.com/paritytech/zombienet/assets/363911/42308725-82c7-4a49-9925-cc088ccb07cd">


Closing here, please re-open if needed.
Thx!
