### ISSUE TITLE
Error parsing spec file

### ISSUE THREAD

**Issue by mrcnski** [paritytech/zombienet#1635]
I'm getting the following error locally on `1.89`:

```
Error:  	 Error: Command failed with exit code 1: bash -c polkadot build-spec --chain /tmp/zombie-56452b0a167e74116df664060b4b83d1_-2929080-1ijy9cSFfiUP/rococo-local-plain.json --disable-default-bootnode  --raw > /tmp/zombie-56452b0a167e74116df664060b4b83d1_-2929080-1ijy9cSFfiUP/rococo-local-raw.json
Error:
   0: Other: Error parsing spec file: expected value at line 339 column 5
```

This doesn't happen on `1.86`. I just downgraded to that, so this isn't a blocking issue for me right now.

If it helps, the branch I'm testing is https://github.com/paritytech/polkadot-sdk/pull/2477.

Thanks!

**Comment by pepoviola** [comment]
Hi @mrcnski, thanks for reporting. Can you share the toml file to reproduce locally?
Thanks!

**Comment by mrcnski** [comment]
Oh yeah! The file is https://github.com/Jpserrat/polkadot-sdk/blob/jpserrat/clone-instead-of-fork/polkadot/zombienet_tests/functional/0002-parachains-disputes.toml and the command I'm running is

```
$ zombienet --provider=native test zombienet_tests/functional/0002-parachains-disputes.zndsl
```

Thanks!
