### ISSUE TITLE
Unable to fetch metrics

### ISSUE THREAD

**Issue by dudo50** [paritytech/zombienet#1640]
### Issue Description

When launching network I am unable to fetch metrics. Tried both nightly and stable toolchains as suggested in issue here:
https://substrate.stackexchange.com/questions/9044/running-a-local-network-with-zombienet-doesnt-work

Nothing seems to help.

### Steps to reproduce the issue

I followed the substrate tutorial
https://docs.substrate.io/test/simulate-parachains/

### Describe the results you received

Network eventually closes

### Describe the results you expected

Launched network

### Zombienet version

Latest

### Provider

Native

### Provider version

```yaml
Latest
```

### Upstream Latest Release

Yes

### Additional environment details

Macos binary

### Additional information

My config:
```

[relaychain]

default_command = "./polkadot-v1.0.0"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"

  [[relaychain.nodes]]
  name = "bob"

  [[relaychain.nodes]]
  name = "charlie"

  [[relaychain.nodes]]
  name = "dave"

[[parachains]]
id = 1000
cumulus_based = true

  [parachains.collator]
  name = "parachain-A-1000-collator01"
  command = "./parachain-template-node-v1.0.0"
```

I use standard parachain template (with customized pallet, but I am able to launch network with 1 relay chain and 1 parachain manually) I need to launch network with 2 parachains to test XCM but unable via zombienet..

### Screenshots

<img width="933" alt="Screenshot 2024-01-02 at 18 26 06" src="https://github.com/paritytech/zombienet/assets/55763425/a5a59708-150e-4c48-8e26-f18f66665f68">

<img width="933" alt="Screenshot 2024-01-02 at 18 32 03" src="https://github.com/paritytech/zombienet/assets/55763425/bc4f42c6-9e0f-4450-adce-b9978b82b32b">

I launch via
DEBUG=zombie* zombienet-macos -p native -c 1 spawn config.toml

because without -c 1 tag it was giving me error pointed in this issue:  https://github.com/paritytech/zombienet/issues/1639

**Comment by dudo50** [comment]
Following debug logs, I can see, that Parachain is running, but the Polkadot node returns strange errors:
<img width="1298" alt="Screenshot 2024-01-02 at 18 44 34" src="https://github.com/paritytech/zombienet/assets/55763425/20ae1225-25fb-49e2-94e0-3729ff252eb5">

**Comment by dudo50** [comment]
I am using [Polkadot v1.3.0](https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-v1.3.0) Polkadot

**Comment by pepoviola** [comment]
Hi @dudo50, thanks for reporting. Can you please send me the full log of one of the relaychain nodes? 
Thx!

**Comment by dudo50** [comment]
@pepoviola  hope this helps:
<img width="933" alt="Screenshot 2024-01-02 at 18 32 03" src="https://github.com/paritytech/zombienet/assets/55763425/eff50d9a-bf62-42f1-9720-63509eee203c">

I've tired to freshly recompile bot did not work

**Comment by dudo50** [comment]
Ok so I resolved this, binaries should not be moved from ./target/release folder as suggested by the tutorial here:  https://docs.substrate.io/test/simulate-parachains/

The config actually needs path to be given to binaries in the target folder.

Closing this.
