### ISSUE TITLE
Unrecognized arg `-d` for `undying-collator` `export-genesis-state` subcommand is provided

### ISSUE THREAD

**Issue by maksimryndin** [paritytech/zombienet#1698]
### Issue Description

Latest version of zombienet runs `undying-collator` subcommand `export-genesis-state` with the deprecated arg `-d` (or at least in the wrong position - for a subcommand `export-genesis-state` instead of the command)
Old versions of zombienet (for example, 1.3.82) work smoothly

cc @mrcnski @s0me0ne-unkn0wn

### Steps to reproduce the issue

Steps to reproduce the issue
Following the instruction here https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/doc/testing.md#behavior-tests-3

### Describe the results you received

Cannot run an integration test with a zombienet cli (see the screenshot)

### Describe the results you expected

Integration tests run

### Zombienet version

1.3.91

### Provider

Native

### Provider version

```yaml
## For binaries
polkadot 1.6.0-757ae372f7f

execute-worker 1.6.0
commit: 757ae372f7f

prepare-worker 1.6.0
commit: 757ae372f7f

undying-collator 1.0.0
```

### Upstream Latest Release

Yes

### Additional environment details

Linux instance-20240122-0924 5.15.0-1045-oracle #51-Ubuntu SMP Fri Sep 22 10:55:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Oracle cloud VPS

### Screenshots

<img width="806" alt="Screenshot 2024-01-23 at 09 04 31" src="https://github.com/paritytech/zombienet/assets/16288656/726eef12-c9d6-4e0f-afbd-a337d416823a">

**Comment by pepoviola** [comment]
Hi @maksimryndin, thanks for reporting this issue. As you said, the `undying` collator doesn't support that flag and we should fix the cmd generation. We should also ensure that the `adder` collator doesn't behave the same way. I will be working on this asap.
Thx!
