### ISSUE TITLE
Advance multiple blocks

### ISSUE THREAD

**Issue by JuaniRios** [paritytech/zombienet#1702]
### Is your feature request related to a problem? Please describe.

My blockchain has extrinsics that I can only call after the chain has advanced a certain amount of blocks.

### Describe the solution you'd like

A command to make your local net advance `x` amount of blocks, while still calling the on_initialize, on_idle, and on_finalize hooks, since I need those too. So not just replacing the block number on storage

### Describe alternatives you've considered

Chopsticks has this feature, although I haven't tested it since I'm only using zombienet for local node testing for now: https://arc.net/l/quote/mvgoirsm

### Additional context

Would be nice to also be able to define in the .toml config if we want to start the net at a certain block.

**Comment by pepoviola** [comment]
Hi @JuaniRios, thanks for your feedback! The concept and features of zombienet and chopsticks are different and we focus on spawning the whole network and allow users to interact with them. 

The way zombienet was thought is to run the nodes as black-box, we can only interact with them through the exposed way. So we can't fast-forward blocks. One thing we can do is start the network from a db-snapshot but I don't think that cover your use case right?


Thanks again for your feedback!

**Comment by JuaniRios** [comment]
Hi @pepoviola , thanks for the response!

What about telling zombienet to spawn your network at a block different than 0?

**Comment by pepoviola** [comment]
> Hi @pepoviola , thanks for the response!
> 
> What about telling zombienet to spawn your network at a block different than 0?

Hi @JuaniRios, you can achieve that by using a db-snapshot file that zombienet will inject in the nodes. Is possible to set the file in the `toml` configuration. If that cover your use case ping me and I can help you to explore this option.
Thx!

**Comment by JuaniRios** [comment]
Hi @pepoviola, I tried using the `genesis_state_path = "./raw-spec.json` config and the chain starts with the desired block number, but as soon as I start producing blocks it is replaced with block number 0.
Is there any other config item for the db-snapshot you mentioned?

You can message me on telegram `@JuaniRios99` to discuss this off-github if you like.

**Comment by pepoviola** [comment]
> Hi @pepoviola, I tried using the `genesis_state_path = "./raw-spec.json` config and the chain starts with the desired block number, but as soon as I start producing blocks it is replaced with block number 0. Is there any other config item for the db-snapshot you mentioned?
> 
> You can message me on telegram `@JuaniRios99` to discuss this off-github if you like.

Hi @JuaniRios, sorry about the delay. Did you manage to start from the db_snapshot? ping me in element if you need help.
Thx!

**Comment by JuaniRios** [comment]
@pepoviola I didn't :(
Pinged you already, did you receive my message?

**Comment by pepoviola** [comment]
Hey @JuaniRios, no. I didn't receive the invite. Can you post your config here?
Thx!

**Comment by pepoviola** [comment]
Closing here @JuaniRios, please ping me in element if you need and we can check it together.
Thx!
