### ISSUE TITLE
Support for modifying bitvec values from the chainspec

### ISSUE THREAD

**Issue by alindima** [paritytech/zombienet#1705]
I need to modify a HostConfiguration value from the chainspec in a zombienet test. The problem is that I need to flip a bit in a [BitVec](https://docs.rs/bitvec/latest/bitvec/vec/struct.BitVec.html).

Alternatively, I need to be able to call an extrinsic on the relay chain with the sudo key, in order to flip this bit.

Any help is appreciated!

**Comment by pepoviola** [comment]
Hi @alindima, thanks for your feedback. Can you send me an example of the chain-spec and the value you want to update? Also, zombienet don't modify the sudo account defined in the spec so most of the times you van just use Alice.

Thanks!!

**Comment by alindima** [comment]
Here's an excerpt of the network config file:

```
[settings]
timeout = 1000
bootnode = true

[relaychain.genesis.runtimeGenesis.patch.configuration.config]
  max_validators_per_core = 5
  needed_approvals = 10
  # I need to set a bit here.
  # node_features = ?

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "rococo-local"
default_command = "polkadot"
```

Here's the HostConfiguration field defined: https://github.com/paritytech/polkadot-sdk/blob/84a246c24a5d3c410a2e4f7d63c0215decddb2b1/polkadot/runtime/parachains/src/configuration.rs#L266
And the type is a BitVec: https://github.com/paritytech/polkadot-sdk/blob/84a246c24a5d3c410a2e4f7d63c0215decddb2b1/polkadot/primitives/src/vstaging/mod.rs#L56

Here's the exposed extrinsic for setting it: https://github.com/paritytech/polkadot-sdk/blob/84a246c24a5d3c410a2e4f7d63c0215decddb2b1/polkadot/runtime/parachains/src/configuration.rs#L1220

> Also, zombienet don't modify the sudo account defined in the spec so most of the times you van just use Alice.

Cool. I just don't know how I could write a js script for doing that. There's no docs about that AFAICT and I haven't written JS in a while :D

Thanks!

**Comment by pepoviola** [comment]
Hi @alindima, thanks for the info! I checked how the field is displayed in rococo-local chain spec ( I think is using an empty bitvec)

```json
            "node_features": {
              "bits": 0,
              "data": [],
              "head": {
                "index": 0,
                "width": 8
              },
              "order": "bitvec::order::Lsb0"
            },
```
Also, looks that we are using the default `serde` serialization and maybe we should add a custom logic to allow to easily set the value from the chain-spec.

Thx!

**Comment by alindima** [comment]
yeah, would be good if we could have an easy way of setting this when building the chainspec. but I guess it's quite difficult to abstract the BitVec into the toml format.

I think setting this with sudo and the extrinsic would be simpler (as we only pass an index as input). If you could help me with writing a script that does that for zombienet, I think that would suffice. thanks!

**Comment by pepoviola** [comment]
Hey @alindima, yes. I can write an small `js` that set the value through an extrinsic. To be in the same page, the flow will be:
- start the whole network
- run the js script for set the BitVec value

Can you send me the index to set?

Thx!

**Comment by alindima** [comment]
yes. The index doesn't matter, I can customise it (set it to 1).
This is the extrinsic: https://github.com/paritytech/polkadot-sdk/blob/84a246c24a5d3c410a2e4f7d63c0215decddb2b1/polkadot/runtime/parachains/src/configuration.rs#L1220 (on the configuration pallet).

Just `set_node_feature(1, true)`

**Comment by pepoviola** [comment]
Hey @alindima, sorry about the delay. This script will send the extrinsic using zombienet dsl like this

```
# configure relay chain
alice: js-script ./set-nodeFeature.js  return is 0 within 600 secs
```

And the script (js)

```js
async function run(nodeName, networkInfo, _jsArgs) {
  const { wsUri, userDefinedTypes } = networkInfo.nodesByName[nodeName];
  const api = await zombie.connect(wsUri, userDefinedTypes);

  await zombie.util.cryptoWaitReady();

  // account to submit tx
  const keyring = new zombie.Keyring({ type: "sr25519" });
  const alice = keyring.addFromUri("//Alice");
  await api.tx.sudo
  .sudo(api.tx.configuration.setNodeFeature(1, true))
  .signAndSend(alice, ({ status, isError }) => {
    if (status.isInBlock) {
      console.log(
        `Transaction included at blockhash ${status.asInBlock}`,
      );
      if (finalization) {
        console.log("Waiting for finalization...");
      } else {
        unsub();
        return resolve();
      }
    } else if (status.isFinalized) {
      console.log(
        `Transaction finalized at blockHash ${status.asFinalized}`,
      );
      unsub();
      return resolve();
    } else if (isError) {
      console.log(`Transaction error`);
      reject(`Transaction error`);
    }        
  });

  return 0;
}

module.exports = { run };

```

But this should be run as part of a testing suite, let me know if you want to just spawn the network and run script later.

Thx!

**Comment by alindima** [comment]
thanks! I'll try that out soon and let you know if it works for me!

**Comment by alindima** [comment]
Hi! I get this error when putting this into a zombinet test:

```
UnhandledRejection:      RpcError: 1014: Priority is too low: (2174005775598 vs 2174005775598): The transaction has too low priority to replace another transaction already in the pool.
```

**Comment by alindima** [comment]
Nevermind, I was running the script from another validator (not alice). Seems to be doing what I need now. Thanks!
