### ISSUE TITLE
Adding relay chain genesis configuration items causes the network to fail to start

### ISSUE THREAD

**Issue by sebastianmontero** [paritytech/zombienet#1707]
### Issue Description

When adding the following configuration items to the network file:
```
[relaychain.genesis.runtime.configuration.config]
scheduling_lookahead = 2

[relaychain.genesis.runtime.configuration.config.async_backing_params]
max_candidate_depth = 3
allowed_ancestry_len = 2
````
the network fails to start with the following error: `Error parsing spec file: expected value at line 199 column 5`

### Steps to reproduce the issue

Try to start a network using the following network file:

Here  is the whole network file I'm using:
```
[relaychain]
default_image = "parity/polkadot:latest"
default_command = "polkadot"
chain = "rococo-local"

[relaychain.genesis.runtime.configuration.config]
scheduling_lookahead = 2

[relaychain.genesis.runtime.configuration.config.async_backing_params]
max_candidate_depth = 3
allowed_ancestry_len = 2

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 2000
cumulus_based = true
chain = "dev"

  [[parachains.collators]]
  name = "charlie"
  validator = true
  command = "./target/release/hashed-parachain"
  args = ["-lparachain=debug"]
```
  

### Describe the results you received

The network fails to start with the following error: `Error parsing spec file: expected value at line 199 column 5`

### Describe the results you expected

The network to start correctly with the configuration items applied

### Zombienet version

1.3.91

### Provider

Native

### Provider version

```yaml
1.3.91
```

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by pepoviola** [comment]
Hey @sebastianmontero, thanks for reporting. Which version of polkadot are you using, you need to check the `json` structure to match the fields you want to update. In the latest version to change those configurations you need to use

```toml
[relaychain.genesis.runtimeGenesis.patch.configuration.config]
scheduling_lookahead = 2

[relaychain.genesis.runtimeGenesis.patch.configuration.config.async_backing_params]
max_candidate_depth = 3
allowed_ancestry_len = 2
```

Can you try with this config?

Thx!

**Comment by sebastianmontero** [comment]
Hi @pepoviola, that worked! Thanks!
