### ISSUE TITLE
`ExportGenesisState` renamed to `ExportGenesisHead` in Polkadot-SDK 1.6.0

### ISSUE THREAD

**Issue by rphmeier** [paritytech/zombienet#1712]
### Issue Description

ZombieNet still uses `ExportGenesisState` and should be able to handle nodes which only have an `ExportGenesisHead` command.

At the moment, chains build using Polkadot-SDK 1.6.0 cannot use ZombieNet without continuing to expose an `ExportGenesisState` command.

### Steps to reproduce the issue

run ZombieNet with a chain built using Polkadot-SDK 1.6.0 which does have `ExportGenesisHead` and does not have `ExportGenesisState`.

### Describe the results you received

n/a

### Describe the results you expected

n/a

### Zombienet version

1.3.91

### Provider

Native

### Provider version

```yaml
N/A
```

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by rphmeier** [comment]
Thanks @pepoviola !

**Comment by pepoviola** [comment]
Hi @rphmeier, I just release a new version https://github.com/paritytech/zombienet/releases/tag/v1.3.92 that includes this fix.

Thanks!
