### ISSUE TITLE
Err: Can not create the forwarding to the tracing collator

### ISSUE THREAD

**Issue by AuroraLantean** [paritytech/zombienet#178]
Regarding Substrate's Zombienet https://github.com/paritytech/zombienet

I setup a folder with the following file structure:
- zombienet-linux ... this is downloaded from the Zombienet repo release page, then made into executable

- 001-small-network.toml ... this is copied from https://github.com/paritytech/zombienet#configuration-files-and-examples -> A minimal configuration example with two validators and one parachain:

    [settings]
    timeout = 1000
    
    [relaychain]
    default_image = "paritypr/polkadot-debug:master"
    chain = "rococo-local"
    
      [[relaychain.nodes]]
      name = "alice"
    
      [[relaychain.nodes]]
      name = "bob"
    
    [[parachains]]
    id = 100
    
      [parachains.collator]
      name = "collator01"
      image = "paritypr/colander:4131-ccd09bbf"
      command = "adder-collator"

Then I ran it according to their Github repo readme:

    minikube start
    ./zombienet-linux spawn ./001-small-network.toml 

Then I received a error message along with other terminal output: `Err: Can not create the forwarding to the tracing collator`

	launching collator01 pod with image paritypr/colander:4131-ccd09bbf
		 with command: /cfg/zombie-wrapper.sh adder-collator --chain /cfg/rococo-local.json --name collator01 --rpc-cors all --unsafe-rpc-external --rpc-methods unsafe --unsafe-ws-external --no-mdns --node-key 5e123980fad4770d9ab5b7df7bbee8499943822a8555d11995e8203210065342 --no-telemetry --bootnodes /ip4/172.17.0.7/tcp/30333/ws/p2p/12D3KooWQCkBm1BYtkHpocxCwMgR8yjitEeHGx8spzcDLGt2gkBm --listen-addr /ip4/0.0.0.0/tcp/30333/ws --base-path /data
		collator01 pod is ready!
	collator01 running

		 You can follow the logs of the node by running this command: 

			 kubectl logs -f collator01
child process exited

	 Err: Can not create the forwarding to the tracing collator

-----------------------------------------

	 Network launched 🚀🚀

		 In namespace zombie-d24c33d968bc53980b678efe8f82f35c with kubernetes provider

		 Node name: alice

		 Node direct link: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A33239#/explorer

		 Node prometheus link: http://127.0.0.1:38401/metrics

---

		 Node name: bob

		 Node direct link: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A35105#/explorer

		 Node prometheus link: http://127.0.0.1:44355/metrics

---

	 Parachain ID: 100

		 Node name: collator01

		 Node direct link: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A35531#/explorer

		 Node prometheus link: http://127.0.0.1:33107/metrics

---
Is that error normal or How can I solve that error?

**Comment by pepoviola** [comment]
Hi @AuroraLantean, thanks for reporting this issue. This is a bug since ZombieNet is trying to get the `forwarding-port` for the tracing collector service without validate **if** the service is available. 

I will fix asap, but shouldn't cause issues to both spawn or test networks.

Thanks!
