### ISSUE TITLE
Coretime Example

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/zombienet#1784]
### Is your feature request related to a problem? Please describe.

I have no idea how to get a zombienet running with coretime.

### Describe the solution you'd like

Example of zombie net configuration and setup commands to run a coretime parachain similar to **Kusama Coretime**: wss://kusama-coretime-rpc.polkadot.io

And ideally with `fast-runtime` runtime enabled.

### Describe alternatives you've considered

Chopsticks but they seem to not support light client rpc methods.

**Comment by pepoviola** [comment]
Sounds good @ryanleecode, I will add an example of running rococo with coretime.

Thanks!

**Comment by pepoviola** [comment]
Hi @ryanleecode, sorry about the delay. You can take inspiration from this [smoke test](https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/zombienet_tests/smoke/0004-coretime-smoke-test.toml) in polkadot-sdk. Please ping me if you have questions 👍 .

Thanks!

**Comment by ryanleecode** [comment]
cc @bee344
