### ISSUE TITLE
--force option is ignored

### ISSUE THREAD

**Issue by lvndry** [paritytech/zombienet#1795]
### Issue Description

I run the command `./zombienet-linux-x64 --provider native --force setup polkadot` however I'm still prompted `Do you want to continue (y/n) ?`
The documentation says we should use `--force` to avoid this prompt

### Steps to reproduce the issue

Steps to reproduce the issue
1. Run `./zombienet-linux-x64 --provider native --force setup polkadot`

### Describe the results you received

I was prompted `Do you want to continue (y/n) ?`

### Describe the results you expected

I expected the command the execute with a default response of yes at every prompt

### Zombienet version

v1.3.100

### Provider

Native

### Provider version

```yaml
## For binaries
polkadot 0.9.40-a2b62fb872b
polkadot-parachain 0.9.380-fe24f39507f
```

### Upstream Latest Release

Yes

### Additional environment details

Command ran in ubuntu:24.04 Docker image

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by pepoviola** [comment]
Hi @lvndry, thanks for your feedback and open this issue. The option to bypass the confirmations is -y or --yes, that why force isn't working.
Your command should be

./zombienet-linux-x64 --provider native setup --yes polkadot

Can you please try with this.

Thanks!!

**Comment by lvndry** [comment]
Thanks that was it!

**Comment by pepoviola** [comment]
Great, closing now. Thanks for the feedback!
