### ISSUE TITLE
Zombienet unable to copy chainspec from parachain pod

### ISSUE THREAD

**Issue by timbrinded** [paritytech/zombienet#1815]
### Issue Description

When trying to run a zombienet work StorageHub, network spawn hangs during the `zombie::kube::chain-spec waiting for chain-spec` phase.

> [!NOTE]  
> This only applies to kubernetes provider, this works fine with native.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Run the config here in this git [minimalRepro.toml](https://gist.github.com/timbrinded/e4ce39a443f8275bf8b1a4b28dfa4819#file-minimalrepro-toml) with something like: `./zombienet spawn minimalRepo.toml`
2. wait

### Describe the results you received

> [!CAUTION]
> Process stalls at waiting for chain spec from storage hub node. Eventually times out

See full logs at gist [spawnLogs.txt](https://gist.github.com/timbrinded/e4ce39a443f8275bf8b1a4b28dfa4819#file-spawnlogs-txt)

### Describe the results you expected

Launched network

### Zombienet version

1.3.105

### Provider

Kubernetes

### Provider version

```yaml
kubectl version 1.28.3
```

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by timbrinded** [comment]
This was because how docker image was created :face_exhaling:

**Comment by pepoviola** [comment]
Hi @timbrinded, thanks for open the issue. I think we can improve the error detection. Did you have the error in the pod?
Thanks!
