### ISSUE TITLE
Can we test solochain with zombienet?

### ISSUE THREAD

**Issue by ashi20192020** [paritytech/zombienet#1823]
I am working on a live solo chain. I have to test a scenario where I want to hit HTTP API through off chain-worker. Unfortunately it's not possible to test in mock environment.

We can take an example of [official Substrate Offchain example](https://github.com/paritytech/polkadot-sdk/blob/74decbbdf22a7b109209448307563c6f3d62abac/substrate/frame/examples/offchain-worker/src/lib.rs#L583) where we are hitting price api. I want to test whether we are able to hit price api through off chain.

I just wanted to check if it is possible through zombienet.

**Comment by pepoviola** [comment]
Hi @ashi20192020, sorry about the delay. That kind of scenarios are supported with zombienet. You can spawn a new (`ephemeral`) network and use our custom-js assertion to run any js code and assert on the output. 
Check https://paritytech.github.io/zombienet/cli/test-dsl-definition-spec.html and there are a few examples [here](https://github.com/paritytech/zombienet/blob/main/tests/0010-histogram-smoke-test.zndsl).

Thanks!

**Comment by pepoviola** [comment]
> @pepoviola Thanks for your answer. Is there any way to start solo chain node using zombienet?

Hi @ashi20192020, sorry about the delay. Yes, you can start a solochain defined as relaychain only in the network definition.

ping me if you need help with this.

Thx!

**Comment by pepoviola** [comment]
Hi @ashi20192020, closing here. Please re-open if needed.
Thx!!
