### ISSUE TITLE
Zombienet registers para id as parachain even though `onboard_as_parachain` set to false

### ISSUE THREAD

**Issue by ParthDesai** [paritytech/zombienet#1831]
### Issue Description

In zombienet, while registering a para id as part of configuration json, even if `onboard_as_parachain` is set to false, that para id is still registered as parachain as well as a  bulk core assignment in core time.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Create a zombienet configuration with at least one para id registered
2. Set `onboard_as_parachain` to false
3. Run the zombienet test network

### Describe the results you received

The para id is registered in relay chain as parachain with core assignment for that para id as bulk.

### Describe the results you expected

The para id should not be registered in relay chain as parachain with no core assignment existing for that para id. 

### Zombienet version

@zombienet/orchestrator: v0.0.86

### Provider

Native

### Provider version

```yaml
## For binaries
polkadot 0.9.40-a2b62fb872b
polkadot-parachain 0.9.380-fe24f39507f 

## For Kubernetes/Podman
podman version 4.4.1

OR

kubectl version v0.26.3
cluster version 1.25.2
```

### Upstream Latest Release

No

### Additional environment details

Environment: Local

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by pepoviola** [comment]
Hi @ParthDesai, thanks formyour feedback. You need to set the para with this keys as false.

```
add_to_genesis = false
register_para = false
onboard_as_parachain = false
```

And the para will not be registered.

Thanks!!
