### ISSUE TITLE
allow override imagePullPolicy to IfNotPresent

### ISSUE THREAD

**Issue by dzmitry-lahoda** [paritytech/zombienet#190]
because on `kind` there is a lot of hassle with `Always`. 

see https://iximiuz.com/en/posts/kubernetes-kind-load-docker-image/

**Comment by pepoviola** [comment]
Hi @dzmitry-lahoda, sounds good. I will add as a `settings` option.
Thanks!

**Comment by pepoviola** [comment]
Hi @dzmitry-lahoda,  fixed in #311. You can set the policy with the setting config image_pull_policy (default is Always)

```
image_pull_policy?: "IfNotPresent" | "Never" | "Always";
```

And that setting will be used for each pod.

Thanks!
