### ISSUE TITLE
allow to generate yaml output instead of apply 

### ISSUE THREAD

**Issue by dzmitry-lahoda** [paritytech/zombienet#191]
so I can review and change YAML definitions combined generates. 

like 
```
spawn --output 
```

actually, once i get output, i doubt i need `zombienet` and can proceed with `kustomize` or `helm`.

i see that `zombienet` starts `pods` in sequence. not sure if that is good. problem with that k8s has no assumption on order.

also `k8s` has `nodeports` to allow to define bootnodes in p2p environments (i hosted `fluence` nodes like that).

**Comment by pepoviola** [comment]
Hi @dzmitry-lahoda, thanks for your feedback! The `yaml` definition is stored in the `tmp` directory for each network. You can see an output like this indicating the location

```
Using temporary directory: /var/folders/rz/1cyx7hfj31qgb98d8_cg7jwh0000gn/T/zombie-f5891fbf5e5212cefbccd8b6191a0e04_-51420-q5SIJ2nQjjZq
```

Related to the order, zombienet starts the pods in sequence or batchs if you use the `-c` option, because for some configurations we need to get info from the running pods before spawn others.

Thanks again for your feedback.

**Comment by dzmitry-lahoda** [comment]
thanks for the folder, really useful to debug. 

dependency steams from need to know "public" IP addresses?

**Comment by pepoviola** [comment]
> dependency steams from need to know "public" IP addresses?

Yes, that can be one example to customize the bootnodes or other command arguments.

Thanks!

**Comment by pepoviola** [comment]
Hi @dzmitry-lahoda, closing here. Feel free to re-open if you have questions.
Thanks for your feedback.

**Comment by dzmitry-lahoda** [comment]
i hosted [fluenc](https://fluence.network/) stuff. it has the same problem. I solved it by having service on top of each pod. With service, you know DNS name ahead, regardless IP.

**Comment by pepoviola** [comment]
Hi @dzmitry-lahoda, thanks again for the feedback. Having a `service` on top of each pod is something that is in the roadmap for exploring. The approach we take with zombienet is manage from outside with an `orchestrator` because we want to support multiple providers and not only k8s.

Thanks!
