### ISSUE TITLE
how to build a docker image with my parachain and adder-collator binary?

### ISSUE THREAD

**Issue by AuroraLantean** [paritytech/zombienet#196]
In my Zombienet example network definition file, I have replaced :
`docker.io/paritypr/polkadot-debug:master`
with
`docker.io/parity/polkadot:v0.9.18`

so now my Zombienet example network definition file is the following:
```
    [relaychain]
    default_image = "docker.io/parity/polkadot:v0.9.18"
    default_command = "polkadot"
    default_args = [ "-lparachain=debug" ]
    
    chain = "rococo-local"
    
      [[relaychain.nodes]]
      name = "alice"
      validator = true
    
      [[relaychain.nodes]]
      name = "bob"
      validator = true
    
    [[parachains]]
    id = 2000
    
      [parachains.collator]
      name = "collator01"
      image = "docker.io/paritypr/colander:master"
      command = "adder-collator"
      
    [types.Header]
    number = "u64"
    parent_hash = "Hash"
    post_state = "Hash"
```
Now. I need to make a docker image to replace   ` docker.io/paritypr/colander:master`

But my new image should have adder-collator binary for adder-collator command to work.

So how can I add that adder-collator to my docker image?

That colander image is hosted here https://hub.docker.com/layers/colander/paritypr/colander/master/images/sha256-3c76e13d988aec875150e024d027af45aefc12f2de98f97db686e558a3d30513?context=explore

**Comment by pepoviola** [comment]
Hi @AuroraLantean, the `adder-collator` is very simple collator used for testing purposes and is compiled from the polkadot repo

```
cargo build --profile testnet --verbose -p test-parachain-adder-collator
```

And then *injected*  into the image using this [Dokerfile](https://github.com/paritytech/polkadot/blob/master/scripts/ci/dockerfiles/collator_injected.Dockerfile) and published under `paritypr`.

Did you need a custom version?

Thanks!

**Comment by AuroraLantean** [comment]
Hi @pepoviola I need to run my ZombieNet test... Do I need a custom version ?

did you mean to run that command above in Polkadot repo, get the adder-collator binary, then copy & paste it into my parachain repo, then make a docker image from my repo, then use it in my ZombieNet network definition file and run my ZombieNet tests? Is that right? Thanks

**Comment by pepoviola** [comment]
Hi @AuroraLantean, you can use the binary produced by your parachain repo ( is based on the [substrate parachain template](https://github.com/substrate-developer-hub/substrate-parachain-template)? 
Thanks!

**Comment by AuroraLantean** [comment]
yes, my parachain is based on the substrate parachain template. 
Good news I got it working!
```
  [parachains.collator]
  name = "collator01"
  image = "gcr.io/paid-network-202104/collator:latest"
  command = "target/release/parachain-collator"
```
