### ISSUE TITLE
parallel test actions

### ISSUE THREAD

**Issue by bernardoaraujor** [paritytech/zombienet#207]
For `polkadot-stps` we need to dispatch transactions against many nodes in parallel.
For example, right now this is what our tests look like
```
alice: is up within 600 secs

# Sending the extrinsics
alice: js-script ./utils.js with "send_balance_transfers" return is 0 within 600 secs
```

Now imagine there's other nodes `bob`, `carol`, `dave`, ...
We need a way to run `send_balance_transfers` for all the nodes in parallel. Currently, if I just add new lines, the actions will happen sequentially, which misses the point of what we are trying to measure.

**Comment by bredamatt** [comment]
Any status on this? I am encountering the same situation myself :)

**Comment by pepoviola** [comment]
HI @bredamatt, this is not yet available since we are working in the `sdk` that will include this feature. At the moment if you want to run `parallel` assertions you need to use a `group` and we ensure that the assertion run in all the nodes in the group.
Thanks!
