### ISSUE TITLE
Create extended test configuration from chain snapshot

### ISSUE THREAD

**Issue by sandreim** [paritytech/zombienet#225]
This seems to be a tractable problem as per the retreat discussions, but there might be dragons and a huge amount of work, but it would be really worth it if we are able to improve up debugability/reproducibility. 

IMO, we can take the state/db from a Kusama for example to create a scaled down ephemeral version of it on which we can run CI integration tests; or just to reproduce issues that are not reproducible with the current approach of spawning a new chain. We should also include parachains with their respective binaries and state.

One of the big challenges would be to replace the validator keys, or alternatively we could disable all signature checking or just do dummy checking to be as close as possible to what happens in the real network. 

@pepoviola @eskimor - please add anything relevant here that would be useful for prototyping this.

**Comment by pepoviola** [comment]
Hi @sandreim / @eskimor, we add the feature to use a `db snapshot` for spawning the nodes in on of the latest versions of zombienet. We can work in trying to replace the keys to allow us to spawn the network and make progress.

I may need some directions in order to research/trying this approach.

Thanks!!

**Comment by pepoviola** [comment]
Hi @sandreim / @eskimor, `db_snapshot` are already available as configuration field for `nodes`. Closing here, please re-open if you have questions.

Thanks!!
