### ISSUE TITLE
TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by sandreim** [paritytech/zombienet#236]
There seems to be an issue with using `westend-local` chainspec along with these chnges:
https://github.com/paritytech/polkadot/pull/5535/commits/4800be1ed29317d6ba136446ee2d421e12e73aa5

https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/1631506

**Comment by pepoviola** [comment]
This should works with the current version of zombienet. Closing here.
Thanks!
