### ISSUE TITLE
Allow combining checks in tests.

### ISSUE THREAD

**Issue by cheme** [paritytech/zombienet#237]
Some tests eg:
```
alice: parachain 2000 block height is at least 10 within 300 seconds
alice: parachain 2001 block height is at least 10 within 300 seconds
alice: parachain 2002 block height is at least 10 within 300 seconds
alice: parachain 2003 block height is at least 10 within 300 seconds
alice: parachain 2004 block height is at least 10 within 300 seconds
alice: parachain 2005 block height is at least 10 within 300 seconds
alice: parachain 2006 block height is at least 10 within 300 seconds
alice: parachain 2007 block height is at least 10 within 300 seconds
```

could be combined under a `Promise::all` to run globally under 300 seconds (currently if something goes wrong the CI will run quite long).

On one of my branches, I also did find it useful to combine some test behind a `Promise::race` as I needed to check something in one of the validator nodes logs but did not know which.

I think such combination could be limited to a single level for simplicity, I hacked it for the `race` case in https://github.com/paritytech/zombienet/commit/4fcc5c98a9beba068020b617b1b8af4166968bc0 by just combining tests in between `RACE` and `ENDRACE`.

**Comment by pepoviola** [comment]
Hi @cheme, closing here. Combined tests are supported for `groups` and in the new version (https://github.com/paritytech/zombienet-sdk).

Thanks!!
