### ISSUE TITLE
New users suggestions on k8s

### ISSUE THREAD

**Issue by NukeManDan** [paritytech/zombienet#241]
https://www.jambit.com/en/latest-info/toilet-papers/minikube-vs-kind-vs-k3s-which-local-kubernetes-cluster-should-i-use/

I am new to k8s and just figuring out how to get things configured, I am going to try out [k3d](https://k3d.io/) with the [k3x](https://github.com/inercia/k3x) GUI
 - https://k3d.io/v5.4.0/usage/advanced/podman/ or podman over docker

Assuming this works out - might be good to include a bit more nuance in configuring things for the 1st time people like myself ;) 

### related to https://github.com/substrate-developer-hub/substrate-docs/issues/1098

**Comment by pepoviola** [comment]
Hi @NukeManDan, thanks for the suggestion. We have the plan to add `docker` as provider and I think will be easy to onboarding people with that since is the most common solution out there for running containers.

Thanks!

**Comment by pepoviola** [comment]
Closing here since we are moving to https://github.com/paritytech/zombienet-sdk and will have docker implemented there.
Thanks for your feedback @NukeManDan 🙌
