### ISSUE TITLE
Failing to match log lines

### ISSUE THREAD

**Issue by sandreim** [paritytech/zombienet#242]
I'm trying to get this PR merged but the new test keeps failing: https://github.com/paritytech/polkadot/pull/5310 

It seems that I cannot match the node startup log lines:
https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/1644594

The string `Database: ParityDb` is present in the log: https://grafana.parity-mgmt.parity.io/goto/V1cJLd3nz?orgId=1

**Comment by pepoviola** [comment]
Hi @sandreim, fixed in the last version of zombienet but this test (https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/1649585) is now failing because of the finality lag.

Closing here.
Thanks!!
