### ISSUE TITLE
DSL: support for running js scripts inside pods

### ISSUE THREAD

**Issue by sandreim** [paritytech/zombienet#246]
This is a helpful feature that opens up many options for data collection and testing done much closer to the running node.
We could for example run a node CPU profiler as part of the test.

@pepoviola I think this can work across all providers using the same DSL and no other config changes. Is this correct ?

There are some dependencies for this to play nicely. We need to bake in the nodejs installation during the docker debug image build.

**Comment by pepoviola** [comment]
Hi @sandreim, yes I think this could works for all the providers. Did you want to use nodejs to use `polkadotjs` or are any other tool you have in mind? As a first draft we can just allow to run any `command` that the node support (e.g bash scripts).

Thanks!

**Comment by sandreim** [comment]
> Hi @sandreim, yes I think this could works for all the providers. Did you want to use nodejs to use `polkadotjs` or are any other tool you have in mind? As a first draft we can just allow to run any `command` that the node support (e.g bash scripts).
> 
> Thanks!

That draft would be good, but soon we would need to be able to pull in other container images of tools that we could use as part of the test.

**Comment by pepoviola** [comment]
Hi @sandreim, draft is already implemented for `k8s` provider.
Thx!

**Comment by pepoviola** [comment]
Hi @sandreim,  I think from zombienet side we need to allow users to run binaries/scripts in the pods but without have a list of available options. We provide a general way to run arbitrary commands, the deps for run those is a task that need to be managed by the `images` creators.

**Comment by pepoviola** [comment]
Hi @sandreim, closing here. We already have support for run `js scripts` extenally and `bash/binaries` inside the pods.
Please re-open/ping me if something is needed.

Thanks!!
