### ISSUE TITLE
Network fails to start with Podman

### ISSUE THREAD

**Issue by crystalin** [paritytech/zombienet#257]
I'm testing zombienet with `podman` (version 3.4.2) and can't run the basic example, I'm not sure how to troubleshoot it:
```
└--╼ node dist/cli.js -p podman spawn examples/0001-small-network.toml 

         Using provider: podman

         Launching network under namespace: zombie-02cfbcd1
                 Using temporary directory: /tmp/zombie-02cfbcd1_-22926-53EgcilrKiYT

         Monitor: prometheus - url: http://127.0.0.1:36097

         Monitor: tempo - url: http://127.0.0.1:38713

         Monitor: grafana - url: http://127.0.0.1:45381

        launching temp pod with image docker.io/paritypr/polkadot-debug:master
                 with command: bash -c polkadot build-spec --chain rococo-local --disable-default-bootnode > /cfg/rococo-local-plain.json
```
It is stuck there forever

**Comment by pepoviola** [comment]
Hi @crystalin, thanks for reporting :) I just trying with podman `3.0.1` and works as expected. Can you check the logs of the `temp` pod when is stuck there?

Thanks!

**Comment by crystalin** [comment]
@pepoviola thank you for looking at it.
I'm really a newbie concerning podman, can you tell me how to properly get the logs so I can paste them here ?

**Comment by pepoviola** [comment]
> @pepoviola thank you for looking at it. I'm really a newbie concerning podman, can you tell me how to properly get the logs so I can paste them here ?

You can check the logs with this command

```
podman logs temp_pod-temp
```

Can you paste the logs here, so I can check why is stuck there 👍

**Comment by crystalin** [comment]
```
podman logs temp_pod-temp
```
It returns nothing (I tried when it was running/stuck and also after killing it)

**Comment by tobbelobb** [comment]
I'm on podman version 3.4.4 and see a similar behavior:

![Screenshot from 2022-10-01 18-30-26](https://user-images.githubusercontent.com/5753253/193419440-713c927f-ab75-481e-82c8-62aa93a58d26.png)

The podman logs tell me it's waiting for tar:

![Screenshot from 2022-10-01 18-36-44](https://user-images.githubusercontent.com/5753253/193419454-c21ee0c5-7a96-449f-9803-8c072df70fc2.png)

I forced it to stop waiting by fiddling with `make_transfer_container()`, and got this error:
```bash
$ node dist/cli.js -p podman spawn examples/0001-small-network.toml
...
Error: ENOENT: no such file or directory, copyfile '/tmp/zombie-922c5be6_-328968-rT47IK5tVg9Y/temp/cfg/rococo-local-plain.json' -> '/tmp/zombie-922c5be6_-328968-rT47IK5tVg9Y/rococo-local-plain.json'
```
I tried again, this time copying the `rococo-local-plain.json` into the right place manually. It worked for a little longer, but then I got:
```bash
$ node dist/cli.js -p podman spawn examples/0001-small-network.toml
...
Error: ENOENT: no such file or directory, copyfile '/tmp/zombie-7e6a3fea_-552529-2Maz0OQx7HSX/temp-collator/cfg/genesis-state' -> '/tmp/zombie-7e6a3fea_-552529-2Maz0OQx7HSX/100/genesis-state'
```
So the `genesis-state` file is also missing. I suspect some kind of error with permissions or something.

**Comment by pepoviola** [comment]
Thanks @tobbelobb, I will look asap.
