### ISSUE TITLE
Is ZombieNet going to provide a centralized parachain registry

### ISSUE THREAD

**Issue by crystalin** [paritytech/zombienet#258]
In order to make zombienet the tools for XCM future developers, there should be an easy way for people to be able to spin-up a complete network with multiple parachains:
`... spawn --parachains moonbeam,acala rococo-config.toml`
Which would be able to combine the parachain config, taken from a registry (in this repo or somehwere else (could even be on-chain :p) and spawn them within the given relay network

It could also stay in the form of toml file, where we would provide a large range of popular parachains combinations.

**Comment by rphmeier** [comment]
This is a good idea. I think we should at least create a place for it and then ask parachain teams to keep it updated

**Comment by pepoviola** [comment]
> In order to make zombienet the tools for XCM future developers, there should be an easy way for people to be able to spin-up a complete network with multiple parachains: `... spawn --parachains moonbeam,acala rococo-config.toml` Which would be able to combine the parachain config, taken from a registry (in this repo or somehwere else (could even be on-chain :p) and spawn them within the given relay network
> 
> It could also stay in the form of toml file, where we would provide a large range of popular parachains combinations.

Hi @crystalin, sorry about the delay. This is a great idea and we are exploring the best way to move forward to create the registry and improve the `dx`. I will post a proposal soon in the [forum](https://forum.polkadot.network/) to open the discussion with the community.

Thanks!

**Comment by pepoviola** [comment]
Hi @crystalin, I will close this one for now. We already add the decorators logic enabling chain-spec customization by `parachains` and we have the registry as one of the goals for the new version of zombienet.

Thanks!
