### ISSUE TITLE
[Deno compat] Decouple cli 

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#270]
In order to support Deno we need to decouple the cli parsing, where we use `nunjucks` to its own module that produce a `json` representation of both `ComputedNetwork` and `test specs`.

With this `zombienet` will have two packages, the `cli` and the `library` enabling a more easy integration since the library will work with a well defined json specs files for both `spawning` the network and producing the `tests suite`.

Also, this will allow us to move the `DSL` to its own grammar and improve the `dx`.

- [x] Create `ComputeNetwork` spec.
- [x] Create `test def` spec.
- [x] Create `cli` module.
- [x] Wire `cli` module to library module.
- [x] Revisit https://github.com/paritytech/zombienet/pull/262 to check compatibility.

CC @harrysolovay

**Comment by wirednkod** [comment]
I think that:
- Create cli module.
- Wire cli module to library module.
will be completed once #475 is merged

**Comment by pepoviola** [comment]
Ping @harrysolovay, we finished the decoupling tasks and now you can use the `orchestrator` directly (without the cli methods). If you want we can coordinate a meet to work in the integration with you or Matias.
Closing here.
Thanks!!

**Comment by harrysolovay** [comment]
Extraordinary news!
