### ISSUE TITLE
[feat] Be able to deploy only Parachains without a Relay Chain node

### ISSUE THREAD

**Issue by NachoPal** [paritytech/zombienet#271]
It seems it always expect in the config file a Relay Chain node. In some cases is useful to be able to deploy only some Parachains collators.

**Comment by pepoviola** [comment]
Hi @NachoPal, sounds interesting. When zombienet create the para chain-spec file its set the `relay_chain` field, what would be the appropriated value in this case?

Thanks!

**Comment by NachoPal** [comment]
`[relaychain]` would be still necessary in the config file. You can get its chain_spec.json and info to be used by the parachain from there.

However, `[[relaychain.nodes]]` wouldn't be mandatory.

To summarise:
- Relay chain specs are needed
- To define its nodes is not

**Comment by pepoviola** [comment]
Hi @NachoPal, sorry about the delay. I think this could be done in the current version with the needed config (e.g chain-spec for relay-chain side). If you still need to run it please ping me.

Thanks!!
