### ISSUE TITLE
Missing Dockerfile for parachain / collator

### ISSUE THREAD

**Issue by bredamatt** [paritytech/zombienet#275]
To deploy in `k8s`, you need a container. 

Whilst `zombienet` works just fine with the pre-made images, it would be great with an example of a `Dockerfile` that allows you to build a new container for a parachain. 

I have come across a few `Dockerfile` examples in various repositories owned by Parity, but I can't seem to make them work. For example, the two-step build process in the `substrate` repo seems to complain half-way through because of a few parameters passed to the compilation process.

It would be great to see an example that we can use for the `substrate-node-template`, since that way, we can iteratively push the image and use it with `zombienet`.

**Comment by pepoviola** [comment]
Hi @bredamatt, thanks for the feedback. You can check docker directory in this  [repo](https://github.com/pepoviola/substrate-parachain-template-zombienet) and use one of the two options to build the image. 
The `injected` one just inject the already compiled binary and the other one compile the parachain binary in a builder container.

Also, you don't need to push the images, you can use your local registry for spawning the nodes in your machine.

Let me know if you have more questions 👍 

Thanks again for the feedback!

**Comment by bredamatt** [comment]
Thanks @pepoviola ! Exactly what I was looking for. Will test now and report back to you.

**Comment by pepoviola** [comment]
Hi @bredamatt, no there isn't any requirement. Zombienet just try to run the pods in the cluster. Did you try run the image using docker to check that the regestry works?

Thanks!

**Comment by bredamatt** [comment]
Hey, so I've tried pushing the image and run it locally, and that works. I tried  till got:

```
$ docker run localhost:5000/parachain-test --help
parachain-collator 0.1.0-unknown
Anonymous
Parachain Collator Template
```

However, when I specify that in the config, I get this:

```
$ k logs temp-collator -n zombie-7e89f36344dc0d904fd1036da0c8b630
Defaulted container "temp-collator" out of: temp-collator, transfer-files-container (init)
Error from server (BadRequest): container "temp-collator" in pod "temp-collator" is waiting to start: image can't be pulled
```

The state:

```
temp-collator   0/1     Pending           0          0s
temp-collator   0/1     Pending           0          0s
temp-collator   0/1     Init:0/1          0          0s
temp            0/1     Completed         0          110s
temp-collator   0/1     Init:0/1          0          4s
temp-collator   0/1     PodInitializing   0          8s
temp-collator   0/1     ErrImagePull      0          20s
```

**Comment by bredamatt** [comment]
Works 👍🏼 ⚡
