### ISSUE TITLE
[feature/enhancement] ability to pause/resume/reboot node during test

### ISSUE THREAD

**Issue by acatangiu** [paritytech/zombienet#277]
Many many more test scenarios could be verified if **during test** we could:
- pause/resume subset of running nodes
- stop/restart/reboot subset of running nodes
- start new nodes (sometimes after initial nodes deployment)

**Comment by pepoviola** [comment]
Hi @acatangiu,
                           Currently pause/resume and restart are supported only using `k8s` provider. The syntax is the following


```
nodeName: pause
nodeName: resume

nodeName: restart [after x secs]
```

Start new nodes is not supported at the moment but is something we can add to the roadmap.

Thanks!

**Comment by pepoviola** [comment]
Hi @acatangiu, closing here since this will be part of `v2` (SDK).
Thanks!
