### ISSUE TITLE
Make grafana links more prominent

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#281]
Currently we are printing the links to grafana for each node in the spawn flow. To make more easy to check them we should also print at the end of the test/spawn with some legend like

```
Hey one of your test failed, to see the full logs of the nodes please go to 
alice: XY
bob: YX
...
```

**Update** Also, when the job/test fails we should grab all the node's logs and expose them as artifacts so external contributors can check them.

cc @bkchr

**Comment by bkchr** [comment]
Thank you! One problem I also foresee is that our grafana is private. Aka external contributors don't have any access to it :see_no_evil: (That is probably some extra issue)

**Comment by pepoviola** [comment]
Yes, that true. One thing we can implement is on failure jobs grab all the logs from the nodes and expose as `artifacts` in gitlab, that way the external contributors can check them at least in the raw format. What do you think?

**Comment by bkchr** [comment]
Yeah that sounds like a good idea :)

**Comment by pepoviola** [comment]
Great, updated to implement that too. Thanks!

**Comment by bkchr** [comment]
These grafana links should also include the correct time frame. Currently when opening the link it will only show the last 3 hours. Meaning that if the job was running 4 hours ago, you don't see any log at the beginning. We should probably be able to just take the job start time as start point to show the logs.

**Comment by pepoviola** [comment]
Hi @bkchr, those changes landed main. I will create a new pr for bumping the zombienet version in cumulus and store the logs as artifacts.

Thanks!

**Comment by bkchr** [comment]
Thank you!

**Comment by bkchr** [comment]
> Yes, that true. One thing we can implement is on failure jobs grab all the logs from the nodes and expose as `artifacts` in gitlab, that way the external contributors can check them at least in the raw format. What do you think?

@pepoviola was this ever implemented?
