### ISSUE TITLE
Found argument '--parachain-id' which wasn't expected

### ISSUE THREAD

**Issue by gregdhill** [paritytech/zombienet#284]
Support for the `--parachain-id` flag was deprecated [here](https://github.com/paritytech/cumulus/pull/739) and there doesn't seem to be a way to prevent `zombienet` from adding this to the collators.

**Comment by pepoviola** [comment]
Hi @gregdhill, thanks for the feedback! Can you share the `toml` config file you are using? Zombienet only use `parachain-id` flag when `cumulus_based` isn't set (or is set to false) in the parachain config.

Thanks!

**Comment by pepoviola** [comment]
Hi @gregdhill, closing here. Please re-open fi you have another question. Thanks!
