### ISSUE TITLE
0002-parachains-disputes test times out

### ISSUE THREAD

**Issue by eskimor** [paritytech/zombienet#287]
Not sure, this is the right place to report this. But above test keeps failing on CI. I just tried it locally (native) with current master and I am getting similar issues:

```
        launching bob
                 with command: malus dispute-ancestor --fake-validation approval-invalid --chain /run/user/1000/zombie-416cefa640b059ba0fc4ac698f9a566d_-1241965-OdBd20fVxYhg/bob/cfg/rococo-local.json --name bob --rpc-cors all --unsafe-rpc-external --rpc-methods unsafe --unsafe-ws-external --no-mdns --node-key 81b637d8fcd2c6da6359e6963113a1170de795e4b725b84d1e0b4cfd9ec58ce9 --no-telemetry --prometheus-external --validator --prometheus-port 35031 --rpc-port 42575 --ws-port 43173 --listen-addr /ip4/0.0.0.0/tcp/32829/ws --base-path /run/user/1000/zombie-416cefa640b059ba0fc4ac698f9a566d_-1241965-OdBd20fVxYhg/bob/data
Error: Timeout(30) for node : bob
    at NativeClient.<anonymous> (/snapshot/zombienet/dist/providers/native/nativeClient.js:266:19)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/zombienet/dist/providers/native/nativeClient.js:5:58)

         Node's logs are available in /run/user/1000/zombie-416cefa640b059ba0fc4ac698f9a566d_-1241965-OdBd20fVxYhg/logs

```

Command used:

```
zombienet-linux-1.2.54 -m -p native test zombienet_tests/functional/0002-parachains-disputes.feature
```

With target/release in $PATH. The mentioned logs directory is empty.

CI error: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/1735394

It is not the same, in fact it is possible that the PR for this job actually has some issue and I am doing something different wrong when running locally. Anyhow, any help greatly appreciated.

**Comment by pepoviola** [comment]
Hi @eskimor, thanks for report this. I checked the logs (from the malus node) and see this `panic`

```
2022-08-11 05:48:27 | Thread 'tokio-runtime-worker' panicked at 'Signature check for imported approval votes failed! This is a serious bug!', node/core/dispute-coordinator/src/import.rs:451
```
You can check them with this [link](https://grafana.parity-mgmt.parity.io/goto/w-p5rHiVk?orgId=1).

Relative to the `native` provider, looks like a different issue since the node fails to start within the timeout, we can debug that together is you want.

Thanks!

**Comment by eskimor** [comment]
Awwwwwwwwweeeesome! Thanks a ton! For the native issue, I would be happy to debug that!

**Comment by eskimor** [comment]
Hmm, ok I think I fixed that bug. Now I don't see anything suspicious in the logs, still test is failing with timeouts: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/1736516 .. anything obvious?

**Comment by pepoviola** [comment]
Hi @eskimor, I run this test locally and the finalization seems stalled 

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/363911/184264907-32948cc7-5f19-422a-a6bb-7aea22b876fd.png">

That cause the failure of these tests

```
# Ensure parachains made progress.
alice: parachain 2000 block height is at least 10 within 200 seconds
alice: parachain 2001 block height is at least 10 within 200 seconds
alice: parachain 2002 block height is at least 10 within 200 seconds
alice: parachain 2003 block height is at least 10 within 200 seconds
```

**Comment by eskimor** [comment]
Resolved on call, thanks @pepoviola ! (Apparently I had an older version downloaded after all)
