### ISSUE TITLE
Run JavaScript Js scripts in Zombienet tests and assert on the completeness or return value

### ISSUE THREAD

**Issue by AuroraLantean** [paritytech/zombienet#309]
@pepoviola 
Could you give an example of how to assert on the completeness or return value?

My feature file:
```
Description: Small Network test
Network: ./z05-small-network.toml
Creds: config

# well know functions
alice: is up
bob: is up
alice: parachain 2000 is registered within 225 seconds

alice: js-script ./01-custom.js return is greater than 1 within 200 seconds
```
My Js file... 01-custom.js:
```
console.log("hello!!!");
return 2;
```
Then I got this error:
```
    ✔ alice: is up (147ms)
    ✔ bob: is up (88ms)
2022-08-24 18:46:43        API/INIT: Not decorating unknown runtime apis: 0xe5bdc752b8ec2ba1/1, 0x91a3c6922fd0a608/1, 0xb69782c4499462e5/1
    ✔ alice: parachain 2000 is registered within 225 seconds (2734ms)
hello!!!

     Error running script: ./01-custom.js
         undefined is not a function

    1) alice: js-script ./01-custom.js return is greater than 1 within 200 seconds
```
How can I assert on the completeness or return value?

https://substrate.stackexchange.com/questions/4424/how-to-run-javascript-js-scripts-in-zombienet-tests-and-assert-on-the-completene

**Comment by pepoviola** [comment]
Hi @AuroraLantean, I just echo here the reply of https://substrate.stackexchange.com/a/4431/279 

thanks for your feedback! 
The `custom js` script must `export` a function call `run` that zombienet will call as part of the assertion.

You can check as example https://github.com/paritytech/zombienet/blob/main/tests/0008-custom.js

```
async function run(nodeName, networkInfo, args) {
    const {wsUri, userDefinedTypes} = networkInfo.nodesByName[nodeName];
    const api = await zombie.connect(wsUri, userDefinedTypes);
    const validator = await api.query.session.validators();
    return validator.length;
}

module.exports = { run }
```

I will also update the documentation to make notice of this requirement, let me know if you have other questions.

Thanks!

**Comment by AuroraLantean** [comment]
Hi @pepoviola , may I know if I can run the TypeScript version of the 0008-custom.js ?
Because TypeScript really helps debugging super fast, much better than JavaScript. Okay? Thanks

**Comment by pepoviola** [comment]
Hi @AuroraLantean, at the moment zombienet only support javascript because just import the file and call the `run` function. But we can add support for typescript compilation on the fly in the future. What do you think @wirednkod ?

Thanks!

**Comment by wirednkod** [comment]
> Hi @AuroraLantean, at the moment zombienet only support javascript because just import the file and call the `run` function. But we can add support for typescript compilation on the fly in the future. What do you think @wirednkod ?

This actually sounds like a good feature TBH - and should not be hard to implement 👍🏽

**Comment by wirednkod** [comment]
This can close now in favor of #345
