### ISSUE TITLE
Run Bash scripts/Bash commands in Zombienet tests and assert on the completeness or return value

### ISSUE THREAD

**Issue by AuroraLantean** [paritytech/zombienet#310]
Can I make deploying Ethereum contracts via Hardhat an assertion as part of the test ?

see reference about Hardhat https://hardhat.org/hardhat-runner/docs/guides/deploying

**Comment by AuroraLantean** [comment]
I see you have an example here: https://github.com/paritytech/zombienet/blob/main/tests/0008-custom-scripts.feature

**Comment by pepoviola** [comment]
Hi @AuroraLantean, thanks for your feedback! Are you using the `kubernets` provider? (at the moment is the only supported to use this assertion). You will not see the `echo`s in the logs of zombienet since the script is uploaded to the node/s and run there. At the moment is only available to assert on the completeness of the script (exit code should be 0). 
Did you need to return a value from the script?

Thanks!

**Comment by AuroraLantean** [comment]
Hi @pepoviola Thanks for quick reply I do not need the return a value from the script, but I need to know if the Ethereum smart contract script runs successfully... 
So how can I assert on the completeness?

**Comment by pepoviola** [comment]
> Hi @pepoviola Thanks for quick reply I do not need the return a value from the script, but I need to know if the Ethereum smart contract script runs successfully... So how can I assert on the completeness? is this way below?
> 
> ```
> alice: run ./0008-custom.sh within 200 seconds
> ```

Yes, exactly. That line will assert on the completeness. You can also check the logs in the pod maybe send the output to a log file to review later in the pod.

e.g
```
echo "inside deployEthereumContracts.sh" > /tmp/custom.log

echo $?
if [ $? -eq 0 ]; then
    echo OK >> /tmp/custom.log
else
    echo FAIL >> /tmp/custom.log
fi
```

Thanks!

**Comment by AuroraLantean** [comment]
Hi @pepoviola I found out the following line will run custom.sh inside the `alice` validator:
```alice: run ./custom.sh within 200 seconds```
but that will be complicated because I want to run a bash command to deploy Ethereum smart contracts via Hardhat cli tool...

Can I run that custom.sh in the environment where I ran my Zombienet command?
