### ISSUE TITLE
 Run Bash scripts outside of Alice or Bob

### ISSUE THREAD

**Issue by AuroraLantean** [paritytech/zombienet#316]
Hi @pepoviola I found out the following line will run custom.sh inside the alice validator:
alice: run ./custom.sh within 200 seconds

but that will be complicated because I need another repository with Ethereum smart contracts and a bunch of test files... Can I run the bash script in the same environment where I ran my Zombienet command? 

And I will need to call my collator's EVM RPC URL from that outside environment.
Can I do that?
Thank you

**Comment by pepoviola** [comment]
Hi @AuroraLantean, for that case you can use the `custom-js` assertion. That one run un the same environment of zombienet. You can use a `js` script to run bash commands. Let me know if this workaround works for you.

Thanks!

**Comment by AuroraLantean** [comment]
Thank you @pepoviola ,
I got it working with this plugin to run bash scripts:
```
const shell = require("shelljs");
shell.exec("./zombienet_tests/01-deploy-zombienet.sh");
```
