### ISSUE TITLE
How to write network file using native parachain and polkadot binaries?

### ISSUE THREAD

**Issue by AuroraLantean** [paritytech/zombienet#330]
Hi @pepoviola , may I know how to run Zombienet tests with natively built parachain and polkadot validator?
It seems in the Readme it is not very clear on how to set that up?

Can I use the same test file(.feature file) ?

My current network file:
```
[relaychain]
default_image = "docker.io/parity/polkadot:{{POLKADOT_VERSION}}"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 2000
cumulus_based = true

  [parachains.collator]
  name = "collator01"
  image = "{{COLLATOR_URL}}"
  command = "hero-collator"
  args = ["-lparachain=debug"]
  
[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
```
How can I change the relayer and parachain images to local native binaries?

**Comment by pepoviola** [comment]
Hi @AuroraLantean,  when you use the `native` provider the `image` and `default_image` are not used and zombienet will use the `command` and `default_command` to spawn the nodes as local process. One easy way to not change the network configuration file (`.toml`) is to have the binaries for `polkadot` and `hero-collator` (in you example) in your `PATH` so zombienet can start the process. Other option is to put the relative or absolute path to those binaries in the `command/default_command` field.

Let me know if you have issues to make it works, thanks!

**Comment by AuroraLantean** [comment]
Okay thank you!
For my fixed network file above:
`default_command = "polkadot"` => Rename my built polkadot validator binary to "polkadot"
`command = "parachain-collator"` => Rename my built parachain collator binary to "parachain-collator"

Then add the binaries above into my terminal PATH:
```
export PATH="/path/to/built/binary_folder/:$PATH"
```
Check if my binaries can be accessed in PATH:
```
polkadot --version
parachain-collator --version
```
Then run my Zombienet feature file with native provider:
```
zombienet-linux1256 -p native test zombienet_tests/z05a-small-network.feature
```
