### ISSUE TITLE
Integrate chain state / RPC queries into the test spec

### ISSUE THREAD

**Issue by drahnr** [paritytech/zombienet#34]
Currently we rely entirely on prometheus metrics for asserts.

This will soon be insufficient for more involved test cases, hence we need a way to introspect the chain state.

We should start with subscribing to chain events `Event`.

**Comment by pepoviola** [comment]
Hi @drahnr, I implemented a new syntax to run a `custom js` function:

```
alice: js-script ./0008-custom.js return is greater than 1 within 200 seconds
```

This will allow us to make any assertions from a simple js script (e.g query the chain state). Is not ideal but we can use until we have more concreted use cases to create ergonomic abstractions.

Thanks!

**Comment by pepoviola** [comment]
Hi @drahnr, closing this one. Please re-open if more integrations are needed.
Thanks!!
