### ISSUE TITLE
Add support for typescript compilation on the fly for tests

### ISSUE THREAD

**Issue by wirednkod** [paritytech/zombienet#345]
Following where this appeared in #309 's [comment](https://github.com/paritytech/zombienet/issues/309#issuecomment-1231253582) by [@AuroraLantean[(https://github.com/AuroraLantean), we should add TS support for tests.

This could be implemented, based on extension and use `tsc` to build on the fly

**Comment by wirednkod** [comment]
The idea behind it (in order to be also backward compatible) comes down to:

<table>
<tr>
	<td>User is able to</td>
	<td>Program reacts with</td>
<tr>
	<td>a) Add .js extension</td>
	<td>As it works currently (no removal of `.js`)
<tr>
	<td>b) Add .ts extension</td>
	<td>Generates .js and runs the test on the .js file - at the end it removes the .js extension</td>
<tr>
	<td>c) provides filename without extension</td>
	<td>Runs (b), if not found runs (a), if non of the two found throws error</td>
</table>

This makes it also backward compatible

cc @pepoviola

**Comment by pepoviola** [comment]
> The idea behind it (in order to be also backward compatible) comes down to:
> 
> User is able to	Program reacts with
> a) Add .js extension	As it works currently (no removal of `.js`)
> b) Add .ts extension	Generates .js and runs the test on the .js file - at the end it removes the .js file that was created
> c) provides filename without extension	Runs (b), if not found runs (a), if non of the two found throws error
> This makes it also backward compatible
> 
> cc @pepoviola

Hi @wirednkod, yes. Make sense to me 👍 .

Thanks!
