### ISSUE TITLE
Add support for new weights.

### ISSUE THREAD

**Issue by ruseinov** [paritytech/zombienet#349]
Failing build: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/1796094
cc @shawntabrizi

**Comment by pepoviola** [comment]
> Failing build: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/1796094 cc @shawntabrizi

Hi @ruseinov, thanks for report this one. I will check asap.
Thanks!

**Comment by ruseinov** [comment]
Very welcome!

**Comment by pepoviola** [comment]
Hi @ruseinov, fixed in last version `v1.2.59`. I need to update the cumulus pr to use this version.
Thanks!
