### ISSUE TITLE
`jaeger` spans

### ISSUE THREAD

**Issue by drahnr** [paritytech/zombienet#35]
As an additional mean of information input, we could also use the existing `jaeger`-`Span` annotations, mapped to `prometheus` metrics. https://github.com/paritytech/dot-jaeger already did this successfully to a smaller extent.

Must be integrated into the test definition as well.

**Comment by pepoviola** [comment]
Hi @drahnr, closing this one since https://github.com/paritytech/zombienet/pull/171 add support for spans. Let me know if something else is needed with spans.

Thanks!!
