### ISSUE TITLE
Add setup to `bin` or link from `zombienet` command for easy setup with bin

### ISSUE THREAD

**Issue by wirednkod** [paritytech/zombienet#350]
In order to make the running of setup easier (at the moment a clone of repo is needed to run), we should extend the:
```
 "bin": {
    "zombienet": "dist/cli.js"
  },
```
to something like:
```
"bin": {
    "zombienet": "dist/cli.js",
    "zombienet-setup: "dist/setup.js"
  },
```
This way a user can download the asset and setup without the need of cloning the repo.
It would be more efficient to add a link for setup to the existing `zombienet` command meaning that if user runs something like:
```
> zombienet setup -b polkadot polkadot-parachain
```
he will be able to setup the environment.

**Comment by pepoviola** [comment]
Yes, we should add the `setup` subcommand to cli. Thanks!!
