### ISSUE TITLE
Modified json has invalid types

### ISSUE THREAD

**Issue by crystalin** [paritytech/zombienet#371]
When reading the genesis json file (with JSON.parse) and then rewriting (with JSON.stringify), it gets the wrong type (which I suppose it is when reading the json file)

original:
```
[
  "0x773539d4ac0e786233d90a233654ccee26a613d9",
  1208925819614629174706176
]
```

modified genesis:
```
[
  "0x773539d4ac0e786233d90a233654ccee26a613d9",
  1.2089258196146292000000000000000000000000
]
```

**Comment by pepoviola** [comment]
Thanks for reporting @crystalin, I will fix asap, the bug is related to how bignumbers are parsed.

Thanks!
