### ISSUE TITLE
Parachains don't produce blocks in `kusama-local` tests

### ISSUE THREAD

**Issue by sandreim** [paritytech/zombienet#379]
This currently blocks slashing testing: https://github.com/paritytech/polkadot/pull/5978
As far as I can see, the issue is that there are no leases for the parachains. Here are some screenshots from my native and scaled down variant of the test:

<img width="1774" alt="Screenshot 2022-09-13 at 14 00 37" src="https://user-images.githubusercontent.com/54316454/189887881-35dbfa25-8e8f-4683-b940-e04dd258938a.png">
<img width="1710" alt="Screenshot 2022-09-13 at 14 14 12" src="https://user-images.githubusercontent.com/54316454/189887885-0dba4786-15bd-4d5b-bf4c-d996421decf3.png">

**Comment by pepoviola** [comment]
Hi @sandreim, I will close here since the block production issue was related to not being compiled with `fast-runtime` feature.

Thanks!
