### ISSUE TITLE
Moonbeam compatibility changes break non-Moonbeam consumers of parachainStaking 

### ISSUE THREAD

**Issue by atomaka** [paritytech/zombienet#385]
In #375 , changes were made to allow compatibility with Moonbeam. Part of these changes assume that if the runtime configuration contains`parachainStaking`, an eth account will be added as a candidate generating an invalid config for chains using polkadot addresses:

```Error: Service(Other("Error parsing spec file: Base 58 requirement is violated at line 75 column 13"))```

Since the block that introduced the issue is marked with a `TODO`, I didn't attempt to implement a solution.

**Comment by pepoviola** [comment]
Hi @atomaka, thanks for reporting. I will fix asap, and to give you more context we are trying to support different teams from the ecosystem and we are working in a refactoring to easily add support for the customizations from new parachains.

Thanks!

**Comment by atomaka** [comment]
No hurry necessary, @pepoviola! We're happy to lock at 1.2.63 until it's resolved.

**Comment by irsal** [comment]
Hey @pepoviola - any updates on this? We're trying to test something via xcmp with moonbase alpha.

**Comment by pepoviola** [comment]
Hi @atomaka / @irsal, this is already fixed in `main` by https://github.com/paritytech/zombienet/pull/415. That `pr` introduce a decorator logic to enable each parachain to override the needed methods to customize their chain spec.

Please re-open if you have questions.

Thanks!
