### ISSUE TITLE
Expose utils/fs package

### ISSUE THREAD

**Issue by crystalin** [paritytech/zombienet#399]
Functions like `readNetworkConfig` would be useful when starting the zombienet with javascript `zombie.start(creds, readNetworkConfig("config.json"))`.

in the exemple https://github.com/paritytech/zombienet/blob/main/tests/dispute-valid-block.json which is used in https://github.com/paritytech/zombienet/blob/main/tests/dispute-valid-block.test.js#L5 , the test uses `require` but the variables are not replaced in that case.

**Comment by pepoviola** [comment]
Hi @crystalin, we breakdown zombienet into diff `packages` and now you can get function like `readNetworkConfig` from the [`@zombienet/utils`](https://www.npmjs.com/package/@zombienet/utils) package.

Closing here, please re-open if you have questions.
Thanks!!
