### ISSUE TITLE
Publish regular version to npm

### ISSUE THREAD

**Issue by crystalin** [paritytech/zombienet#400]
We are starting to use zombienet in our CI and need to have recent version. It seems the latest one on npm is 1.2.48 (3 month old).
I tried installing the npm package from github instead but it is not working properly.

So publishing regular update should be a good thing :)

**Comment by crystalin** [comment]
(Using `npm link` method is also a solution when done locally but would prefer not to include this hack in the CI)

**Comment by wirednkod** [comment]
Thank you @crystalin 
I will create a auto-deploy process for every new package to be also released to npm.

**Comment by crystalin** [comment]
Thank you, in the meantime, can you also publish the 1.2.68 please ?

**Comment by pepoviola** [comment]
> Thank you, in the meantime, can you also publish the 1.2.68 please ?

Hi @crystalin, published 👍. We will keep publishing new releases until we get the auto-publish process in place.

Thanks!!

**Comment by crystalin** [comment]
@pepoviola sorry to bother you, can we get a version 69 being released (to include the fix for cleaning timers on exit) please ?

**Comment by pepoviola** [comment]
> @pepoviola sorry to bother you, can we get a version 69 being released (to include the fix for cleaning timers on exit) please ?

Hi @crystalin, done  `v1.2.69`. Sorry about the delay.
Thanks!
