### ISSUE TITLE
`chain_spec_path` property for parachains is ignored

### ISSUE THREAD

**Issue by dastanbeksamatov** [paritytech/zombienet#409]
I assumed that when you provide `chain_spec_path` to parachain configuration, it should override manual chain spec generation and just copy provided file to the temp folder. But `parachains.chain_spec_path` argument's value is not passed to chain spec generation method `setupChainSpec()` [here](https://github.com/paritytech/zombienet/blob/main/src/paras.ts#L53). This makes `chain_spec_path` argument for parachain configuration useless.

**Comment by pepoviola** [comment]
Hi @dastanbeksamatov, thanks for reporting! Yes, this is a bug and will be fixed asap.
Thanks!
