### ISSUE TITLE
HRMP channels not opening

### ISSUE THREAD

**Issue by bernardoaraujor** [paritytech/zombienet#449]
I'm doing some work based on this [config file](https://github.com/paritytech/trappist/blob/51-asset-registry/xcm-playground.toml).

If I start it with zombienet 1.2.55, the HRMP channels open.
If I start it with latest (1.2.71), the HRMP channels are not open.

**Comment by wirednkod** [comment]
Thank you Bernardo.

Due to #243 , PR #390 changed some config items to snake_case (starting at `v1.2.67`). Can you alter the `[[hrmpChannels]]`  to `[[hrmp_channels]]` and let me know if that fixes the issue?

**Comment by pepoviola** [comment]
Can we close this one @bernardoaraujor?
Thanks!
