### ISSUE TITLE
Silently failing for invalid CLI parameters

### ISSUE THREAD

**Issue by crystalin** [paritytech/zombienet#466]
If you try to run a configuration with cli parameters that are not allowed (like using `--state-pruning 256` on `polkadot-v0.9.26`), the zombie fails and doesn't report any error, nor log.

In order to find the issue it is required to use DEBUG=zombie and run the command manually. Ex:
```
error: Found argument '--state-pruning' which wasn't expected, or isn't valid in this context

        Did you mean '--unsafe-pruning'?

        If you tried to supply `--state-pruning` as a value rather than a flag, use `-- --state-pruning`

USAGE:
    polkadot --chain <CHAIN_SPEC> --name <NAME> --rpc-cors <ORIGINS> --unsafe-rpc-external --rpc-methods <METHOD SET> --unsafe-ws-external --no-hardware-benchmarks --log <LOG_PATTERN>... --unsafe-pruning

For more information try --help
```

**Comment by pepoviola** [comment]
Hi @crystalin, this should be handled correctly now in `main` and will be part of the next release.
Thanks!
