### ISSUE TITLE
Missing dependency in latest version

### ISSUE THREAD

**Issue by crystalin** [paritytech/zombienet#506]
After installing the latest verison (with npm `npm install --save @parity/zombienet@latest` ) running `zombienet` generates:
```
 Cannot find module '@parity/zombienet-dsl-parser-wrapper'
 Cannot find module 'toml
 Cannot find module 'cli-table3
 Cannot find module 'axios
 Cannot find module 'napi-maybe-compressed-blob
...
 ```

**Comment by pepoviola** [comment]
Hi @crystalin, we are splitting the functionality is diff modules under `@zombienet` npm scope.

@zombienet/orchestrator -> expose fns to spawn/test
@zombienet/utils -> expose utils fns.

I currently checking this bug and others related. There is also a `legacy` version (1.2.x) with the latest fixes that countinue works as a single module.

Thanks!

**Comment by wirednkod** [comment]
I think #509 should close this
