### ISSUE TITLE
Feature: Support raw chain

### ISSUE THREAD

**Issue by crystalin** [paritytech/zombienet#507]
It would be great if we can pass an already configured raw chain to the node (specially the parachain ones). 
Zombienet would not try to modify the genesis/state of the specs.

Use case: When replaying exported state (raw) from an existing chain

**Comment by pepoviola** [comment]
Sounds good, I will work on this for the new version.

**Comment by pepoviola** [comment]
Hi @crystalin, sorry about the delay. The latest version `v1.3.22` include the support for using `raw` format in the chain-spec for paras. Also, I talked with @girazoki about the latest changes we introduce in zombienet. We split the code in diff modules and now is more easy to use as a library (with the @zombienet/orchestrator module) and build a custom test-runner.

Ping me if you have questions, thanks!!

**Comment by crystalin** [comment]
@pepoviola, sounds great. I'm going to try it soon :)
