### ISSUE TITLE
Logs not displaying the whole file path.

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/zombienet#515]
With the new tables the file path for logs was shrink and i cannot copy/paste as before:

<img width="887" alt="Screenshot 2022-10-27 at 12 10 05" src="https://user-images.githubusercontent.com/12089572/198258115-50488997-2db5-4473-95c3-1560a3c76c29.png">

it would be nice to wrap it all as the `Commands` section

**Comment by pepoviola** [comment]
@wirednkod can you wrap the logs line command and make it multi-line?
Thanks!

**Comment by wirednkod** [comment]
@pepoviola absolutely. Can do that today. 
Thank you @hbulgarini for reporting that
