### ISSUE TITLE
[SDK] Building block `Network`

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#525]
`Network` high-level specs:

- We should allow to use a builder pattern to construct the network and the `build` method should create all the needed configuration to spawn the network.

- `spawn` method should check that all the needed artifacts are ready, and if not we should `build` internally.

- `info` method should return all the running config info (endpoints/chain-spec paths/ log paths/etc)

- `destroy` method should tear-down all the network and clean-up all the resources. (we want to allow to save the logs/database for a later analysis)

-  `rebuild` should allow to rebuild the `network` instance from the same json we get from `info`.

```rust
```

**Comment by wirednkod** [comment]
Moved to https://github.com/paritytech/zombienet-sdk/issues/2
