### ISSUE TITLE
Add equilibrium test in CI

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#570]
https://github.com/equilibrium-eosdt

Image: https://hub.docker.com/r/equilab/eq-para/tags

**Comment by pepoviola** [comment]
We need to ping the equilibrium team to add some an easy way to identify their parachain using `chain name`.

**Comment by wirednkod** [comment]
> We need to ping the equilibrium team to add some an easy way to identify their parachain using `chain name`.

cc @MucTepDayH16  : can you help us with this? We cannot find some recently active repo in Equilibrium team or someone to contact.

**Comment by pepoviola** [comment]
Closing here, please ping us @MucTepDayH16 since we require an small change in your side to make it works.

**Comment by mn13** [comment]
Hey guys! @pepoviola Equilibrium published here https://github.com/eq-lab/equilibrium
What kind of change do you need?

**Comment by pepoviola** [comment]
Hey @mn13, thanks for your answer. Did you publish an image from that repo? We need an image that allow us to build the chain spec with `--chain equilibrium-local`. Thanks!
