### ISSUE TITLE
Support `substrate` node in zombienet

### ISSUE THREAD

**Issue by michalkucharczyk** [paritytech/zombienet#581]
I am trying to run `zombienet` with `substrate` nodes:
```
[relaychain]
default_image = "docker.io/parity/substrate:latest"
default_command = "substrate"
```

The following error is reported:
```
Error fetching metrics from: http://127.0.0.1:35467/metrics 
```

The substrate node does not support `--jaeger-agent` argument.
```
error: Found argument '--jaeger-agent' which wasn't expected, or isn't valid in this context

  If you tried to supply '--jaeger-agent' as a value rather than a flag, use '-- --jaeger-agent'
```

**Comment by pepoviola** [comment]
This is fixed by https://github.com/paritytech/zombienet/pull/582

`substrate` need this config

```
enable_tracing = false
```

cc @wirednkod we should review this default (true) for v2.
