### ISSUE TITLE
Create validation error for config `image` provided

### ISSUE THREAD

**Issue by wirednkod** [paritytech/zombienet#585]
Following #584 a new validation should be added for the image paths given, in order to provide an error if path does not fit the validation `url.extension/path`

**Comment by wirednkod** [comment]
You can do that. you need to remove the:
```
image = "/bin/parachain-v0.9.30-1000"
```
and add that to your PATH for `adder collator`.
If you do so then the `relay chain` will use the docker image while the `adder collator` will run natively

**Comment by pepoviola** [comment]
@wirednkod / @sacha-l, providers can not be mixee at the moment. So, you run all in k8s or native but not both at the same time.
Thanks!

**Comment by wirednkod** [comment]
@pepoviola  Thank you for clarification
@sacha-l I mis-tested with all local settings. Apologies

**Comment by sacha-l** [comment]
Thanks for clarifying guys. An easy enhancement to add to this issue: checks that user is using one provider type for all nodes passed to the config file, if not throws an error with description.

**Comment by pepoviola** [comment]
Another update, I think we should emit a `warning` for every key defined in the `toml` file that we don't expect. For example in #616 we should handle better the definition and let the user know about we will not use the `default_args` for parachains.
