### ISSUE TITLE
add ability to specify start timeout string  or command

### ISSUE THREAD

**Issue by dzmitry-lahoda** [paritytech/zombienet#589]
Currently default timeout greps for `Listening for new connections|Running JSON-RPC`. 

Even if I set cumulus_based = false;

Simples way to handle that is for example to disable check, by specifying

```toml
startup_command="true"
```
so that `true` cli command invoked to detect start

**Comment by pepoviola** [comment]
Hi @dzmitry-lahoda, thanks for reporting. I will change this behavior in the native provider and mark as ready a node when

- The `pid` of the spawned process is running.
- The metric `process_start_time_seconds` in the node can be retrieved.

I think is not needed to add a config related to this check at the moment.

Thanks!

**Comment by dzmitry-lahoda** [comment]
thanks. hope this works.

so imho making native to be as close as k8s/podman/(docker compose what ever) is best.

**Comment by pepoviola** [comment]
Hi @dzmitry-lahoda, last version refactor the way we check if the node is _live_ and don't use anymore the regex. I will close this one and please re-open if you have questions or find something that isn't working as expected.
Thanks!!
