### ISSUE TITLE
do not author blocks if offline by default on collators

### ISSUE THREAD

**Issue by dzmitry-lahoda** [paritytech/zombienet#591]
actual: force_authoring=true for collators is default
expected:false
why: it reports false positives about well connected running net. false should be default. or at least there should be document how to make it false
notes:
https://github.com/paritytech/substrate/blob/108d8eed88e71b5bb676a23fe983174fabf43c35/client/consensus/babe/src/lib.rs#L399

**Comment by pepoviola** [comment]
Yes, at the moment is always `true`. We can remove this behavior and let users set by passing the `--force-authoring` argument to the collator.

Thanks!
