### ISSUE TITLE
with native provider command_with_args is ignored if command set

### ISSUE THREAD

**Issue by dzmitry-lahoda** [paritytech/zombienet#593]
given
```
[[parachains]]
add_to_genesis = true
chain = "dali-dev"
cumulus_based = true
id = 2087
[[parachains.collators]]
command = "../../target/release/composable"
command_with_args = "../../target/release/composable --collator --ferdie --force-authoring --tmp --base-path=etc --rpc-cors all --unsafe-rpc-external 123sdasd --rpc-methods unsafe --unsafe-ws-external -- --execution wasm --chain /cfg/rococo-local.json --bootnodes /dns/bootnode/tcp/30333/ws/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
name = "bob"
```

expected: error to start asking to remove command
actual: command_with_args is not used

**Comment by dzmitry-lahoda** [comment]
actually `command_with_args` was ignored event if there was not command command . it just retained `command` out of `command_with_args`, but not args. better fails fast and tell that `args` are not used

**Comment by pepoviola** [comment]
Hi @dzmitry-lahoda, thanks for reporting. Yes, `commands_with_args` is ignored for collators. I will fix this asap.
Thanks!
