### ISSUE TITLE
how to express parachain balances genesis?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [paritytech/zombienet#605]
```json
{
        "palletBalances": {
          "balances": [
            [
              "15cYfYawEbmY15SPj1eGmQdmp5x3qXE42YMDDsQ3xL1PTfJ8",
              1000000000000000000
            ],
            [
              "15oickhybx6tDqDArGH7p8vx1FxkMAMjhqLSHB7KDQC8Xmcm",
              1000000000000000000
            ],
            [
              "15GVxRkyRW7ieaMzdqtr8ngk4dZGvBs3PU97naxMMZVGdY5u",
              1000000000000000
            ]
          ]
        }
}
```
tells when converting to TOML
```
Invalid JSON input. Array values can't have mixed types
```

I am trying to do 

```
[[parachains.genesis.runtime.runtime_genesis_config.balances.balances]]
0 = "15cYfYawEbmY15SPj1eGmQdmp5x3qXE42YMDDsQ3xL1PTfJ8"
1 = 1000000000000000000
```

Sure it not works. But how?

**Comment by pepoviola** [comment]
That `json` can be converted to `toml` like this

```toml
[palletBalances]
balances = [
  [
  "15cYfYawEbmY15SPj1eGmQdmp5x3qXE42YMDDsQ3xL1PTfJ8",
  1_000_000_000_000_000_000
  ],
  [
  "15oickhybx6tDqDArGH7p8vx1FxkMAMjhqLSHB7KDQC8Xmcm",
  1_000_000_000_000_000_000
  ],
  [
  "15GVxRkyRW7ieaMzdqtr8ngk4dZGvBs3PU97naxMMZVGdY5u",
  1_000_000_000_000_000
  ]
]
```

Can you try?
Thanks!

**Comment by dzmitry-lahoda** [comment]
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/757125/203070456-adbf0c83-7b3b-4c33-811c-ee5642f4eb6d.png">
this one worked with simple number

**Comment by dzmitry-lahoda** [comment]
this fails 

<img width="769" alt="image" src="https://user-images.githubusercontent.com/757125/203071609-3096cd62-6862-4975-b612-1cf262cda531.png">

**Comment by dzmitry-lahoda** [comment]
worked

```
[parachains.genesis.runtime.balances.balances.0]
0 = "5GF8HUxZ1tCHWVZMoGVqDWe8EtdnKznHEbaguRQNqvMkw34H"
1 = 1_123_000_000_000_000_000
```

but 
```
[parachains.genesis.runtime.balances.balances.16]
0 = "5GF8HUxZ1tCHWVZMoGVqDWe8EtdnKznHEbaguRQNqvMkw34H"
1 = 1_123_000_000_000_000_000
```

not. so replacing array object works, but not adding.

imho should follow JSON/YAML patch (read around k8s patch json kustomzie)

**Comment by dzmitry-lahoda** [comment]
<img width="1572" alt="image" src="https://user-images.githubusercontent.com/757125/203077851-7bf525af-62fb-423b-97d6-b2a5c05a1c79.png">

**Comment by dzmitry-lahoda** [comment]
It fails to parse TOML file at all.

**Comment by dzmitry-lahoda** [comment]
This 
```
  [
  "15cYfYawEbmY15SPj1eGmQdmp5x3qXE42YMDDsQ3xL1PTfJ8",
  1000000000000000
  ],
```
is not valid TOML file

**Comment by pepoviola** [comment]
> ```toml
> [palletBalances]
> balances = [
>   [
>   "15cYfYawEbmY15SPj1eGmQdmp5x3qXE42YMDDsQ3xL1PTfJ8",
>   1000000000000000
>   ],
>   [
>   "15oickhybx6tDqDArGH7p8vx1FxkMAMjhqLSHB7KDQC8Xmcm",
>   1000000000000000
>   ],
>   [
>   "15GVxRkyRW7ieaMzdqtr8ngk4dZGvBs3PU97naxMMZVGdY5u",
>   1000000000000000
>   ]
> ]
> ```
> 
> 

Hi @dzmitry-lahoda, the `toml` [spec](https://toml.io/en/v1.0.0#integer) don't mention `big` numbers and using a rust parser produce the correct `value`.  But, let me check if works  with `zombienet` since use the big number js library.

Thanks!!


<img width="499" alt="image" src="https://user-images.githubusercontent.com/363911/203108051-680fcc53-899b-44c1-8f81-3359b9534877.png">

<img width="948" alt="image" src="https://user-images.githubusercontent.com/363911/203108118-54aa9e79-32bf-4aec-a1ae-fb903f9c038c.png">

**Comment by pepoviola** [comment]
Hi @dzmitry-lahoda closing here, please re-open if necessary.
Thanks!!
