### ISSUE TITLE
Add `yaml` suport in the `cli` module

### ISSUE THREAD

**Issue by dzmitry-lahoda** [paritytech/zombienet#606]
Imho using yaml instead of toml would make much more sense:
1. easier to map json to yaml (because json is subset of yaml)
2. k8s and docker are yaml
3. it can express heterogenous arrays
4. people in ops are good yaml and its templating

what do you think?

**Comment by pepoviola** [comment]
Hi @dzmitry-lahoda, thanks for the suggestion. We are planning to create a new `sdk` for v2 and leave the v1 as legacy. But we can include support for `yaml` in the `cli` module in the same way we do for `toml` (at the end is translate to json to interact with the orchestrator).

I will try to add this new feature.

Thanks!!
