### ISSUE TITLE
arm linux zombienet client

### ISSUE THREAD

**Issue by dzmitry-lahoda** [paritytech/zombienet#617]
- we run kusama, statemine, karura and composable with polkalauncher in arm linux VM in m1 macs 
- we need arm client to run these in zombienet

**Comment by pepoviola** [comment]
Hi @dzmitry-lahoda, thanks for reporting. We can add an `arm` version for linux to our release pipeline.
Thanks!!

**Comment by pepoviola** [comment]
Hi @dzmitry-lahoda, last version already includes a binary for linux-arm. 
https://github.com/paritytech/zombienet/releases/tag/v1.3.22

Thanks!
