### ISSUE TITLE
Is there a way to find the full set of configuration properties that can be set in the `config.toml` file?

### ISSUE THREAD

**Issue by lisa-parity** [paritytech/zombienet#619]
I think it would be nifty to provide reference documentation that listed all of the properties that can be set in a configuration file with a brief description and example.
I'd be happy to help with this because zombienet is a super useful tool, but I'm not sure how I can find the supported configuration options.

**Comment by wirednkod** [comment]
Thank you for the interest lisa. Currently we are keeping an md configuration in the following link: https://paritytech.github.io/zombienet/ . Let us know if that provides sufficient information

**Comment by lisa-parity** [comment]
Thanks, @wirednkod , https://paritytech.github.io/zombienet/network-definition-spec.html is exactly what I was looking for!

**Comment by pepoviola** [comment]
Hi @lisa-parity, closing here. Please re-open if you have questions. 
Thanks!
