### ISSUE TITLE
Robonomics parachain on zombienet times out

### ISSUE THREAD

**Issue by rafat2** [paritytech/zombienet#620]
I have a minimum zombienet configuration with two validators on local rococo testnet and a robonomics parachain node.

```
[relaychain]
default_command = "./bin/polkadot"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

    [[relaychain.nodes]]
    name = "alice"
    validator = true

    [[relaychain.nodes]]
    name = "bob"
    validator = true

[[parachains]]
id = 2048
chain = "main-dev"

    [parachains.collator]
    name = "alice"
    chain = "main-dev"
    command = "./bin/robonomics"
    args = ["-lparachain=debug","--force-authoring"]
```

The relay chain spawns alright but the robonomics parachain fails with

```
Error: Timeout(60) for node : alice-1
at NativeClient.<anonymous> (/snapshot/javascript/packages/orchestrator/dist/providers/native/nativeClient.js)
at Generator.next (<anonymous>)
at fulfilled (/snapshot/javascript/packages/orchestrator/dist/providers/native/nativeClient.js)
```

Chain versions

robonomics 2.6.0-84120838070

polkadot 0.9.28-314298c32ac

I have tried the similar configuration with other parachains and it works.

**Comment by wirednkod** [comment]
Thank you @rafat2 for reporting this. Can you please us some more information?
- Are you running with a release of zombienet or with a cloned repo?
- if the latter can you please paste your node version?

Thank you

**Comment by rafat2** [comment]
Hi @wirednkod Thanks for your quick reply. I am using zombient-linux version 1.3.18 ( latest release, I believe).

**Comment by wirednkod** [comment]
Can you please try adding in your `.toml` file just under the `[[parachains]]` the  `cumulus_based = true`.
See sample below where the `<---` is:

```rust
[[parachains]]
id = 1000
cumulus_based = true  // <-----

  [parachains.collator]
```

**Comment by rafat2** [comment]
It fails again with a different error.

```
TypeError: Cannot read properties of undefined (reading '0')
    at clearAuthorities (/snapshot/javascript/packages/orchestrator/dist/chain-spec.js)
    at /snapshot/javascript/packages/orchestrator/dist/paras.js
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/javascript/packages/orchestrator/dist/paras.js)
┌────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Node'              │ /tmp/zombie-8decca0cf5d024e678365b4902c84514_-15730-wHfsVc8N2CCh/logs                              │
│ s logs:            │                                                                                                    │
│ m                  │                                                                                                    │
└────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────┘
Error: Command failed with exit code 2: /bin/bash -c kill -9
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
    at makeError (/snapshot/javascript/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/snapshot/javascript/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 2: /bin/bash -c kill -9 ',
  command: '/bin/bash -c kill -9 ',
  escapedCommand: '"/bin/bash" -c "kill -9 "',
  exitCode: 2,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
UnhandledRejection: Error: Command failed with exit code 2: /bin/bash -c kill -9
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```

**Comment by pepoviola** [comment]
> It fails again with a different error.
> 
> ```
> TypeError: Cannot read properties of undefined (reading '0')
>     at clearAuthorities (/snapshot/javascript/packages/orchestrator/dist/chain-spec.js)
>     at /snapshot/javascript/packages/orchestrator/dist/paras.js
>     at Generator.next (<anonymous>)
>     at fulfilled (/snapshot/javascript/packages/orchestrator/dist/paras.js)
> ┌────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────┐
> │ Node'              │ /tmp/zombie-8decca0cf5d024e678365b4902c84514_-15730-wHfsVc8N2CCh/logs                              │
> │ s logs:            │                                                                                                    │
> │ m                  │                                                                                                    │
> └────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────┘
> Error: Command failed with exit code 2: /bin/bash -c kill -9
> kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
>     at makeError (/snapshot/javascript/node_modules/execa/lib/error.js:60:11)
>     at handlePromise (/snapshot/javascript/node_modules/execa/index.js:118:26)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
>   shortMessage: 'Command failed with exit code 2: /bin/bash -c kill -9 ',
>   command: '/bin/bash -c kill -9 ',
>   escapedCommand: '"/bin/bash" -c "kill -9 "',
>   exitCode: 2,
>   signal: undefined,
>   signalDescription: undefined,
>   stdout: '',
>   stderr: 'kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]',
>   failed: true,
>   timedOut: false,
>   isCanceled: false,
>   killed: false
> }
> UnhandledRejection: Error: Command failed with exit code 2: /bin/bash -c kill -9
> kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
> ```


Hi @rafat2, thanks for your feedback. Does your chain make any special customization on the chain-spec? Sounds like we should add the parachain to the decorators registry to have a custom behavior of zombienet.

Thanks!

**Comment by rafat2** [comment]
Hi @pepoviola , I am using a pre-built Robonomics binary and I believe this is their version tree https://github.com/airalab/robonomics/tree/841208380709e338c8ae0a4b15ea5772d73252dd

**Comment by pepoviola** [comment]
Hi @rafat2, I checked the `chain-spec` generated by running
```
./robonomics build-spec --chain main-dev
``` 
And we need to `decorate` some of the functions that zombienet use for customize the file. (e.g the keys, staking, authorities keys). 

Thanks!

**Comment by rafat2** [comment]
Thanks. I guess I'll have to take this up with the robonomics team. I'll re-open this if there are any further issues.

**Comment by amacar** [comment]
Any updates @rafat2 , did you manage to run it using newer zombienet version eventually?
