### ISSUE TITLE
Enable Github discussions

### ISSUE THREAD

**Issue by qdm12** [paritytech/zombienet#621]
Hello there,

I'm an engineer working on Gossamer, the Polkadot host written in Go. I have attended the talk by @pepoviola at Sub0 Lisbon on the zombienet and that was very useful. We have a few questions on that, and I was thinking a Github discussion would be most appropriate (public, shared versus matrix chats) to establish what Github issues we can create on this repository and/or our repository. Would you be up to enabling such feature in this repository settings? It might also be useful to help user configuring the zombienet, eventually.

Thanks!

**Comment by wirednkod** [comment]
Hey @qdm12 

This is a great idea and we were discussing it with @pepoviola . Thank you for bringing it up.
I just activated [discussions](https://github.com/paritytech/zombienet/discussions) - please feel free to share something about yourself and your ideas 🙏🏽 🎉
