### ISSUE TITLE
Feedback on W3F-RFP: Designing UpChain

### ISSUE THREAD

**Issue by taqtiqa-mark** [paritytech/zombienet#634]
A review of the proposed RFP [Designing UpChain](https://github.com/w3f/Grants-Program/pull/1309) suggested to...

> check if there are synergies with Zombienet, which plans to have runtime update testing

Appreciate any feedback.

**Comment by pepoviola** [comment]
Looks like is already merged, sorry about the delay. Closing here.
Thanks!
