### ISSUE TITLE
Support large genesis file

### ISSUE THREAD

**Issue by crystalin** [paritytech/zombienet#640]
If the genesis is too big, you can't use it with ZombieNet:
`RangeError [ERR_FS_FILE_TOO_LARGE]: File size (8689689103) is greater than 2 GiB`

(You can take https://s3.us-east-2.amazonaws.com/snapshots.moonbeam.network/moonriver/latest/moonriver-state.json for ex)

**Comment by pepoviola** [comment]
Hi @crystalin, thanks for reporting. This is because we read the json into memory. We can implement `streams` or also check if the file is in raw mode and only make the needed replacements. I will work in the fix and ping you for testing.

Thanks!!
