### ISSUE TITLE
Does db snapshots work for cumulus collators?

### ISSUE THREAD

**Issue by samelamin** [paritytech/zombienet#671]
Looking at the code it seems like snapshots cannot be supported because we are writing the snapshot file to the `chains` dir but for collators, we also have the `relay-data` directory. A snapshot for a parachain needs both directories

https://github.com/paritytech/zombienet/blob/HEAD/javascript/packages/orchestrator/src/providers/native/nativeClient.ts#L283-L284

https://github1s.com/paritytech/zombienet/blob/HEAD/javascript/packages/orchestrator/src/providers/podman/podmanClient.ts#L383-L384

```
[Relaychain] Bootnode with peer id `12D3KooWQCkBm1BYtkHpocxCwMgR8yjitEeHGx8spzcDLGt2gkBm` is on a different chain (our genesis: 0x2d46…5d89 theirs: 0x2540…b2b2)  
```

**Comment by pepoviola** [comment]
Hi @samelamin, thanks for reporting this issue and provide feedback. I think the simplest solution is to match the `node` role to extract the data in the correct directory.
Thanks!

**Comment by samelamin** [comment]
No worries @pepoviola I have sent a pr so feel free to review it when you get a chance. 

Wouldnt it be simpler to extract both at the root? because otherwise you need to match the node role as well as prepare the snapshot differently for both relay and parachain. 

While if we extract at the root, everything remains consistent?

**Comment by pepoviola** [comment]
Hi @samelamin, thanks for the [pr](https://github.com/paritytech/zombienet/pull/673/files). I would review and check it asap.
Thanks!! 

cc: @michalkucharczyk if we change this we will need to update the CI test for substrate.

**Comment by pepoviola** [comment]
Hi @samelamin, closing here since the pr is already merged and included in the latest version.
Thansk!
