### ISSUE TITLE
Improve Timeout output

### ISSUE THREAD

**Issue by wirednkod** [paritytech/zombienet#678]
Improve Timeout output, to provide more information on which test failed, and `expect` was failed

At the moment the outcome looks like:
```
Error:  
		 Timeout(600), "getting desired metric value 20 within 600 secs".
	 Error:  
		 Timeout(600), "getting desired metric value 20 within 600 secs".
	Hey one or more of your test failed, to see the full logs of the nodes please go to:
```

**Comment by pepoviola** [comment]
@wirednkod, we should also implement an abort logic for the promises.

**Comment by pepoviola** [comment]
@wirednkod this is already done right?
