### ISSUE TITLE
yarn complains of incorrect dependency version in @zombienet/cli

### ISSUE THREAD

**Issue by hamidra** [paritytech/zombienet#687]
When using @zombienet/cli in a repo initiated with yarn it complains of incorrect dependency version.

to reproduce:
```bash 
yarn add --non-interactive  @zombienet/cli
```

it failed with the following issue:
```bash
yarn add v1.22.17
[1/4] 🔍  Resolving packages...
error Couldn't find any versions for "napi-maybe-compressed-blob-win32-x64-msvc" that matches "0.0.7"
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

this prevents zombienet from being used in ci/cd workflows, which are run in non-ineractive mode.

The issue does not happen when using npm. but yarn is a widely used package manager and I assume projects who use yarn should also be able to use zombienet!

**Comment by hamidra** [comment]
Checking the published packages the issue seems to be [here](https://www.npmjs.com/package/napi-maybe-compressed-blob?activeTab=explore).
 If you check this the published package.json it refers  "napi-maybe-compressed-blob-win32-x64-msvc": "0.0.7", but that version is not published on npm.
 
https://www.npmjs.com/package/napi-maybe-compressed-blob?activeTab=explore

```
"optionalDependencies": {
    "napi-maybe-compressed-blob-win32-x64-msvc": "0.0.7",
    "napi-maybe-compressed-blob-darwin-x64": "0.0.7",
    "napi-maybe-compressed-blob-linux-x64-gnu": "0.0.7",
    "napi-maybe-compressed-blob-darwin-arm64": "0.0.7",
    "napi-maybe-compressed-blob-linux-arm64-gnu": "0.0.7"
  }
```

**Comment by pepoviola** [comment]
Hi @hamidra, this should be fixed in the last release of zombienet that includes `napi-maybe-compressed-blob` (0.0.11).
Thanks!!
