### ISSUE TITLE
Add command line options to use zombienet as generator for podman

### ISSUE THREAD

**Issue by dzmitry-lahoda** [paritytech/zombienet#692]
As far as my understanding, zombienet generates docker compose compatible file when running podman? 

Can command line option to be available to output file into location? 

So file can be used to run stuff manually? 

I know it is possible to copy k8s config from some temp folder.

So request to `zombienet generate --outdir=<WHATEVER>` and get generated all as needed in that folder. No run anything.

**Comment by pepoviola** [comment]
Hi @dzmitry-lahoda, at the moment zombienet create `pod` files that are used with `podman kube play` and I don't think those works with `docker compose`. We have in our roadmap add docker as `provider` (through docker compose). But we can include an option to generate the files and don't run the pods/process.

Thanks!!

**Comment by dzmitry-lahoda** [comment]
oh, nice. podman runs k8s like stuff.  i see. so then request is generator, not really compose files (it is separate request).

Idea is to use kustomise/nix on generated files to modify (or review/dryrun)

**Comment by pepoviola** [comment]
Hi @dzmitry-lahoda, I will close this one. Please re-open if you have questions.
Thanks!!
