### ISSUE TITLE
Artifact logs do not contain collator logs

### ISSUE THREAD

**Issue by skunert** [paritytech/zombienet#699]
When a job is ran, zombienet states `📓 Logs are also available in the artifacts' pipeline in gitlab`.
When I inspect the artifacts, I see only the ones from the validator however, no collator logs are included.

[Example test](https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2307678)

All nodes as listed
![image](https://user-images.githubusercontent.com/5718005/214287416-d20f4091-f45b-4b42-b072-7b97e947f741.png)

Artifacts
![image](https://user-images.githubusercontent.com/5718005/214287526-511c3654-554c-4a98-b2f9-9c40a9f87efa.png)

**Comment by pepoviola** [comment]
Thanks for reporting @skunert, I will take a look asap.
