### ISSUE TITLE
 parachain-template-node dies

### ISSUE THREAD

**Issue by sylvaincormier** [paritytech/zombienet#713]
Hi!
I am creating a zombie network  using polkadot 0.9.36
with substrate-parachain-template
I have tried with susbstrate parachain template 0.9.37 
Result
Status:   Error
Process: 940015, for node: parachain-template-node dies. 
Error: unexpected argument '--parachain-id' found 
 note: argument '--chain' exists
I then downgraded to try 0.9.32
Result:
error: Found argument '--parachain-id' which wasn't expected, or isn't valid in this context  
If you tried to supply '--parachain-id' as a value rather than a flag, use '--  --parachain-id'   

Any ideas?

**Comment by pepoviola** [comment]
Hi @sylvaincormier, thanks for open this issue. If the parachain collator is based on cumulus (like the parachain-template) you need to set the flag

```
cumulus_based = true
```
 in the parachain config like this line in examples 
 
 https://github.com/paritytech/zombienet/blob/main/examples/0004-small-network-cumulus.toml#L20

Thanks!!

**Comment by pepoviola** [comment]
Hi @sylvaincormier, closing here. Please re-open if you have questions.

Thanks!!
