### ISSUE TITLE
I was trying to run the parity zombienet with podman but getting error like this. Can anyone tell me what is the issue? How can I run zombienet in my linux machine with podman?

### ISSUE THREAD

**Issue by iamAbasu7** [paritytech/zombienet#732]
╔════════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ 🧟 Zombienet 🧟    │ Initiation                                                                                         ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Provider           │ podman                                                                                             ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Namespace          │ zombie-14dd2f0e                                                                                    ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Temp Dir           │ /tmp/zombie-14dd2f0e_-19309-ZvzqHCyMgWKJ                                                           ║
╚════════════════════╧════════════════════════════════════════════════════════════════════════════════════════════════════╝
Error: Command failed with exit code 125: podman play kube --network zombie-14dd2f0e /tmp/zombie-14dd2f0e_-19309-ZvzqHCyMgWKJ/prometheus.yaml
Trying to pull docker.io/prom/prometheus:latest...
Getting image source signatures
Copying blob sha256:225de5a6f1e724884cc9ebbe5671c3438d0fc76f4ce45c86a1c64a4522e6dcd3
Copying blob sha256:ebd656a24cc0eae2f499f8e044889caa32e276752eae9956e5bc45e0dd72f8bd
Copying blob sha256:5aaacfdc414583811746c269fefa4a1ea612a6369dbacd73ba1eb8ed27231ef3
Copying blob sha256:5420b5446248895f5558b6b8a76959ccf53302a4351a12f2521c0ae76ccc6b7e
Copying blob sha256:e6170f30a38d0665f12cfd95757f05c82cb2973411a98ac763d9a7e3487a21a5
Copying blob sha256:8a2ab86e3ff18da541fa5f1f24c1403b8c93cbecaff64aed7ee041f7ef0f992d
Copying blob sha256:3dab14bd0e8c4860e0cb33184590b962a8328d60944f715c2c7aa1dfd169bd6d
Copying blob sha256:5bce46b63ac9290da01d0ff9186041ab5259c50c5c045d21a83549db656dfc92
Copying blob sha256:4399114b4c59be45238d2958ccaef1fa50ac18f83d2c1bb585e15a4af273b31f
Copying blob sha256:7e5bc43c7502f110c53cc8f597f2e44fa60c2dacf3698e51e2fbae4450cd0efd
Copying blob sha256:00cd3198f364b3bfbb53226de45f7dc8a231bc9456c386ec03e5f96da61aa110
Copying blob sha256:cbd4b912d9ee779013eac17bd4001dc44ded3824d80111980c9d84eb21d3a139
Copying config sha256:8cfcb66f43649bbe426a25511440c645018b9cf5ddcf05aacef582a052ad474b
Writing manifest to image destination
Storing signatures
time="2023-02-15T11:10:53+05:30" level=error msg="error unmounting /home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/merged: invalid argument"
a container exists with the same name ("prometheus") as the pod in your YAML file; changing pod name to prometheus_pod
error starting container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error mounting storage for container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error creating overlay mount to /home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/merged, mount_data=",lowerdir=/home/antar/.local/share/containers/storage/overlay/l/LUPOMEIMTFQ2IJ4T6E54YD4WHU,upperdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/diff,workdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/work": using mount program /usr/bin/fuse-overlayfs: /usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libfuse3.so.3: version `FUSE_3.12' not found (required by /usr/bin/fuse-overlayfs)
/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/bin/fuse-overlayfs)
/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/fuse-overlayfs)
: exit status 1
error starting container 44695f7394731124ba1964aa0d2406a9cb9bd84783b8a42d5590e3b6d97f608d: a dependency of container 44695f7394731124ba1964aa0d2406a9cb9bd84783b8a42d5590e3b6d97f608d failed to start: container state improper
Error: failed to start 2 containers
[error starting container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error mounting storage for container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error creating overlay mount to /home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/merged, mount_data=",lowerdir=/home/antar/.local/share/containers/storage/overlay/l/LUPOMEIMTFQ2IJ4T6E54YD4WHU,upperdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/diff,workdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/work": using mount program /usr/bin/fuse-overlayfs: /usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libfuse3.so.3: version `FUSE_3.12' not found (required by /usr/bin/fuse-overlayfs)
/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/bin/fuse-overlayfs)
/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/fuse-overlayfs)
: exit status 1]
[error starting container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error mounting storage for container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error creating overlay mount to /home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/merged, mount_data=",lowerdir=/home/antar/.local/share/containers/storage/overlay/l/LUPOMEIMTFQ2IJ4T6E54YD4WHU,upperdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/diff,workdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/work": using mount program /usr/bin/fuse-overlayfs: /usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libfuse3.so.3: version `FUSE_3.12' not found (required by /usr/bin/fuse-overlayfs)
/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/bin/fuse-overlayfs)
/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/fuse-overlayfs)
: exit status 1 error starting container 44695f7394731124ba1964aa0d2406a9cb9bd84783b8a42d5590e3b6d97f608d: a dependency of container 44695f7394731124ba1964aa0d2406a9cb9bd84783b8a42d5590e3b6d97f608d failed to start: container state improper]
Pod:
e58172a841429598660c1d0defbfff35734ed3f3ee48c755613764d1af5b1cea
Container:
44695f7394731124ba1964aa0d2406a9cb9bd84783b8a42d5590e3b6d97f608d

    at makeError (/snapshot/javascript/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/snapshot/javascript/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 125: podman play kube --network zombie-14dd2f0e /tmp/zombie-14dd2f0e_-19309-ZvzqHCyMgWKJ/prometheus.yaml',
  command: 'podman play kube --network zombie-14dd2f0e /tmp/zombie-14dd2f0e_-19309-ZvzqHCyMgWKJ/prometheus.yaml',
  escapedCommand: 'podman play kube --network zombie-14dd2f0e "/tmp/zombie-14dd2f0e_-19309-ZvzqHCyMgWKJ/prometheus.yaml"',
  exitCode: 125,
  signal: undefined,
  signalDescription: undefined,
  stdout: '[error starting container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error mounting storage for container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error creating overlay mount to /home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/merged, mount_data=",lowerdir=/home/antar/.local/share/containers/storage/overlay/l/LUPOMEIMTFQ2IJ4T6E54YD4WHU,upperdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/diff,workdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/work": using mount program /usr/bin/fuse-overlayfs: /usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libfuse3.so.3: version `FUSE_3.12\' not found (required by /usr/bin/fuse-overlayfs)\n' +
    "/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/bin/fuse-overlayfs)\n" +
    "/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/fuse-overlayfs)\n" +
    ': exit status 1]\n' +
    '[error starting container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error mounting storage for container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error creating overlay mount to /home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/merged, mount_data=",lowerdir=/home/antar/.local/share/containers/storage/overlay/l/LUPOMEIMTFQ2IJ4T6E54YD4WHU,upperdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/diff,workdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/work": using mount program /usr/bin/fuse-overlayfs: /usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libfuse3.so.3: version `FUSE_3.12\' not found (required by /usr/bin/fuse-overlayfs)\n' +
    "/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/bin/fuse-overlayfs)\n" +
    "/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/fuse-overlayfs)\n" +
    ': exit status 1 error starting container 44695f7394731124ba1964aa0d2406a9cb9bd84783b8a42d5590e3b6d97f608d: a dependency of container 44695f7394731124ba1964aa0d2406a9cb9bd84783b8a42d5590e3b6d97f608d failed to start: container state improper]\n' +
    'Pod:\n' +
    'e58172a841429598660c1d0defbfff35734ed3f3ee48c755613764d1af5b1cea\n' +
    'Container:\n' +
    '44695f7394731124ba1964aa0d2406a9cb9bd84783b8a42d5590e3b6d97f608d\n' +
    '\n',
  stderr: 'Trying to pull docker.io/prom/prometheus:latest...\n' +
    'Getting image source signatures\n' +
    'Copying blob sha256:225de5a6f1e724884cc9ebbe5671c3438d0fc76f4ce45c86a1c64a4522e6dcd3\n' +
    'Copying blob sha256:ebd656a24cc0eae2f499f8e044889caa32e276752eae9956e5bc45e0dd72f8bd\n' +
    'Copying blob sha256:5aaacfdc414583811746c269fefa4a1ea612a6369dbacd73ba1eb8ed27231ef3\n' +
    'Copying blob sha256:5420b5446248895f5558b6b8a76959ccf53302a4351a12f2521c0ae76ccc6b7e\n' +
    'Copying blob sha256:e6170f30a38d0665f12cfd95757f05c82cb2973411a98ac763d9a7e3487a21a5\n' +
    'Copying blob sha256:8a2ab86e3ff18da541fa5f1f24c1403b8c93cbecaff64aed7ee041f7ef0f992d\n' +
    'Copying blob sha256:3dab14bd0e8c4860e0cb33184590b962a8328d60944f715c2c7aa1dfd169bd6d\n' +
    'Copying blob sha256:5bce46b63ac9290da01d0ff9186041ab5259c50c5c045d21a83549db656dfc92\n' +
    'Copying blob sha256:4399114b4c59be45238d2958ccaef1fa50ac18f83d2c1bb585e15a4af273b31f\n' +
    'Copying blob sha256:7e5bc43c7502f110c53cc8f597f2e44fa60c2dacf3698e51e2fbae4450cd0efd\n' +
    'Copying blob sha256:00cd3198f364b3bfbb53226de45f7dc8a231bc9456c386ec03e5f96da61aa110\n' +
    'Copying blob sha256:cbd4b912d9ee779013eac17bd4001dc44ded3824d80111980c9d84eb21d3a139\n' +
    'Copying config sha256:8cfcb66f43649bbe426a25511440c645018b9cf5ddcf05aacef582a052ad474b\n' +
    'Writing manifest to image destination\n' +
    'Storing signatures\n' +
    'time="2023-02-15T11:10:53+05:30" level=error msg="error unmounting /home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/merged: invalid argument"\n' +
    'a container exists with the same name ("prometheus") as the pod in your YAML file; changing pod name to prometheus_pod\n' +
    'error starting container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error mounting storage for container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error creating overlay mount to /home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/merged, mount_data=",lowerdir=/home/antar/.local/share/containers/storage/overlay/l/LUPOMEIMTFQ2IJ4T6E54YD4WHU,upperdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/diff,workdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/work": using mount program /usr/bin/fuse-overlayfs: /usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libfuse3.so.3: version `FUSE_3.12\' not found (required by /usr/bin/fuse-overlayfs)\n' +
    "/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/bin/fuse-overlayfs)\n" +
    "/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/fuse-overlayfs)\n" +
    ': exit status 1\n' +
    'error starting container 44695f7394731124ba1964aa0d2406a9cb9bd84783b8a42d5590e3b6d97f608d: a dependency of container 44695f7394731124ba1964aa0d2406a9cb9bd84783b8a42d5590e3b6d97f608d failed to start: container state improper\n' +
    'Error: failed to start 2 containers',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Error: Command failed with exit code 125: podman play kube --network zombie-14dd2f0e /tmp/zombie-14dd2f0e_-19309-ZvzqHCyMgWKJ/prometheus.yaml
Trying to pull docker.io/prom/prometheus:latest...
Getting image source signatures
Copying blob sha256:225de5a6f1e724884cc9ebbe5671c3438d0fc76f4ce45c86a1c64a4522e6dcd3
Copying blob sha256:ebd656a24cc0eae2f499f8e044889caa32e276752eae9956e5bc45e0dd72f8bd
Copying blob sha256:5aaacfdc414583811746c269fefa4a1ea612a6369dbacd73ba1eb8ed27231ef3
Copying blob sha256:5420b5446248895f5558b6b8a76959ccf53302a4351a12f2521c0ae76ccc6b7e
Copying blob sha256:e6170f30a38d0665f12cfd95757f05c82cb2973411a98ac763d9a7e3487a21a5
Copying blob sha256:8a2ab86e3ff18da541fa5f1f24c1403b8c93cbecaff64aed7ee041f7ef0f992d
Copying blob sha256:3dab14bd0e8c4860e0cb33184590b962a8328d60944f715c2c7aa1dfd169bd6d
Copying blob sha256:5bce46b63ac9290da01d0ff9186041ab5259c50c5c045d21a83549db656dfc92
Copying blob sha256:4399114b4c59be45238d2958ccaef1fa50ac18f83d2c1bb585e15a4af273b31f
Copying blob sha256:7e5bc43c7502f110c53cc8f597f2e44fa60c2dacf3698e51e2fbae4450cd0efd
Copying blob sha256:00cd3198f364b3bfbb53226de45f7dc8a231bc9456c386ec03e5f96da61aa110
Copying blob sha256:cbd4b912d9ee779013eac17bd4001dc44ded3824d80111980c9d84eb21d3a139
Copying config sha256:8cfcb66f43649bbe426a25511440c645018b9cf5ddcf05aacef582a052ad474b
Writing manifest to image destination
Storing signatures
time="2023-02-15T11:10:53+05:30" level=error msg="error unmounting /home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/merged: invalid argument"
a container exists with the same name ("prometheus") as the pod in your YAML file; changing pod name to prometheus_pod
error starting container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error mounting storage for container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error creating overlay mount to /home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/merged, mount_data=",lowerdir=/home/antar/.local/share/containers/storage/overlay/l/LUPOMEIMTFQ2IJ4T6E54YD4WHU,upperdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/diff,workdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/work": using mount program /usr/bin/fuse-overlayfs: /usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libfuse3.so.3: version `FUSE_3.12' not found (required by /usr/bin/fuse-overlayfs)
/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/bin/fuse-overlayfs)
/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/fuse-overlayfs)
: exit status 1
error starting container 44695f7394731124ba1964aa0d2406a9cb9bd84783b8a42d5590e3b6d97f608d: a dependency of container 44695f7394731124ba1964aa0d2406a9cb9bd84783b8a42d5590e3b6d97f608d failed to start: container state improper
Error: failed to start 2 containers
[error starting container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error mounting storage for container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error creating overlay mount to /home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/merged, mount_data=",lowerdir=/home/antar/.local/share/containers/storage/overlay/l/LUPOMEIMTFQ2IJ4T6E54YD4WHU,upperdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/diff,workdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/work": using mount program /usr/bin/fuse-overlayfs: /usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libfuse3.so.3: version `FUSE_3.12' not found (required by /usr/bin/fuse-overlayfs)
/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/bin/fuse-overlayfs)
/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/fuse-overlayfs)
: exit status 1]
[error starting container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error mounting storage for container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error creating overlay mount to /home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/merged, mount_data=",lowerdir=/home/antar/.local/share/containers/storage/overlay/l/LUPOMEIMTFQ2IJ4T6E54YD4WHU,upperdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/diff,workdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/work": using mount program /usr/bin/fuse-overlayfs: /usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libfuse3.so.3: version `FUSE_3.12' not found (required by /usr/bin/fuse-overlayfs)
/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/bin/fuse-overlayfs)
/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/fuse-overlayfs)
: exit status 1 error starting container 44695f7394731124ba1964aa0d2406a9cb9bd84783b8a42d5590e3b6d97f608d: a dependency of container 44695f7394731124ba1964aa0d2406a9cb9bd84783b8a42d5590e3b6d97f608d failed to start: container state improper]
Pod:
e58172a841429598660c1d0defbfff35734ed3f3ee48c755613764d1af5b1cea
Container:
44695f7394731124ba1964aa0d2406a9cb9bd84783b8a42d5590e3b6d97f608d

    at makeError (/snapshot/javascript/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/snapshot/javascript/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 125: podman play kube --network zombie-14dd2f0e /tmp/zombie-14dd2f0e_-19309-ZvzqHCyMgWKJ/prometheus.yaml',
  command: 'podman play kube --network zombie-14dd2f0e /tmp/zombie-14dd2f0e_-19309-ZvzqHCyMgWKJ/prometheus.yaml',
  escapedCommand: 'podman play kube --network zombie-14dd2f0e "/tmp/zombie-14dd2f0e_-19309-ZvzqHCyMgWKJ/prometheus.yaml"',
  exitCode: 125,
  signal: undefined,
  signalDescription: undefined,
  stdout: '[error starting container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error mounting storage for container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error creating overlay mount to /home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/merged, mount_data=",lowerdir=/home/antar/.local/share/containers/storage/overlay/l/LUPOMEIMTFQ2IJ4T6E54YD4WHU,upperdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/diff,workdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/work": using mount program /usr/bin/fuse-overlayfs: /usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libfuse3.so.3: version `FUSE_3.12\' not found (required by /usr/bin/fuse-overlayfs)\n' +
    "/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/bin/fuse-overlayfs)\n" +
    "/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/fuse-overlayfs)\n" +
    ': exit status 1]\n' +
    '[error starting container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error mounting storage for container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error creating overlay mount to /home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/merged, mount_data=",lowerdir=/home/antar/.local/share/containers/storage/overlay/l/LUPOMEIMTFQ2IJ4T6E54YD4WHU,upperdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/diff,workdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/work": using mount program /usr/bin/fuse-overlayfs: /usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libfuse3.so.3: version `FUSE_3.12\' not found (required by /usr/bin/fuse-overlayfs)\n' +
    "/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/bin/fuse-overlayfs)\n" +
    "/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/fuse-overlayfs)\n" +
    ': exit status 1 error starting container 44695f7394731124ba1964aa0d2406a9cb9bd84783b8a42d5590e3b6d97f608d: a dependency of container 44695f7394731124ba1964aa0d2406a9cb9bd84783b8a42d5590e3b6d97f608d failed to start: container state improper]\n' +
    'Pod:\n' +
    'e58172a841429598660c1d0defbfff35734ed3f3ee48c755613764d1af5b1cea\n' +
    'Container:\n' +
    '44695f7394731124ba1964aa0d2406a9cb9bd84783b8a42d5590e3b6d97f608d\n' +
    '\n',
  stderr: 'Trying to pull docker.io/prom/prometheus:latest...\n' +
    'Getting image source signatures\n' +
    'Copying blob sha256:225de5a6f1e724884cc9ebbe5671c3438d0fc76f4ce45c86a1c64a4522e6dcd3\n' +
    'Copying blob sha256:ebd656a24cc0eae2f499f8e044889caa32e276752eae9956e5bc45e0dd72f8bd\n' +
    'Copying blob sha256:5aaacfdc414583811746c269fefa4a1ea612a6369dbacd73ba1eb8ed27231ef3\n' +
    'Copying blob sha256:5420b5446248895f5558b6b8a76959ccf53302a4351a12f2521c0ae76ccc6b7e\n' +
    'Copying blob sha256:e6170f30a38d0665f12cfd95757f05c82cb2973411a98ac763d9a7e3487a21a5\n' +
    'Copying blob sha256:8a2ab86e3ff18da541fa5f1f24c1403b8c93cbecaff64aed7ee041f7ef0f992d\n' +
    'Copying blob sha256:3dab14bd0e8c4860e0cb33184590b962a8328d60944f715c2c7aa1dfd169bd6d\n' +
    'Copying blob sha256:5bce46b63ac9290da01d0ff9186041ab5259c50c5c045d21a83549db656dfc92\n' +
    'Copying blob sha256:4399114b4c59be45238d2958ccaef1fa50ac18f83d2c1bb585e15a4af273b31f\n' +
    'Copying blob sha256:7e5bc43c7502f110c53cc8f597f2e44fa60c2dacf3698e51e2fbae4450cd0efd\n' +
    'Copying blob sha256:00cd3198f364b3bfbb53226de45f7dc8a231bc9456c386ec03e5f96da61aa110\n' +
    'Copying blob sha256:cbd4b912d9ee779013eac17bd4001dc44ded3824d80111980c9d84eb21d3a139\n' +
    'Copying config sha256:8cfcb66f43649bbe426a25511440c645018b9cf5ddcf05aacef582a052ad474b\n' +
    'Writing manifest to image destination\n' +
    'Storing signatures\n' +
    'time="2023-02-15T11:10:53+05:30" level=error msg="error unmounting /home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/merged: invalid argument"\n' +
    'a container exists with the same name ("prometheus") as the pod in your YAML file; changing pod name to prometheus_pod\n' +
    'error starting container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error mounting storage for container 80f90840df638e66cf3b9fee45bac80f28ffef396599bb6451588d6ebbafe086: error creating overlay mount to /home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/merged, mount_data=",lowerdir=/home/antar/.local/share/containers/storage/overlay/l/LUPOMEIMTFQ2IJ4T6E54YD4WHU,upperdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/diff,workdir=/home/antar/.local/share/containers/storage/overlay/49975b5ce81a8a5506c8f58bfc47dd120c26d989de5c83e659e873496b6beebb/work": using mount program /usr/bin/fuse-overlayfs: /usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libfuse3.so.3: version `FUSE_3.12\' not found (required by /usr/bin/fuse-overlayfs)\n' +
    "/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/bin/fuse-overlayfs)\n" +
    "/usr/bin/fuse-overlayfs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/fuse-overlayfs)\n" +
    ': exit status 1\n' +
    'error starting container 44695f7394731124ba1964aa0d2406a9cb9bd84783b8a42d5590e3b6d97f608d: a dependency of container 44695f7394731124ba1964aa0d2406a9cb9bd84783b8a42d5590e3b6d97f608d failed to start: container state improper\n' +
    'Error: failed to start 2 containers',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
┌────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Node'              │ /tmp/zombie-14dd2f0e_-19309-ZvzqHCyMgWKJ/logs                                                      │
│ s logs:            │                                                                                                    │
│ m                  │                                                                                                    │
└────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────┘
![zombienet_err2](https://user-images.githubusercontent.com/88479559/218961836-a7aca165-39b5-4098-aff8-92014c18a993.png)
![zobienet_err1](https://user-images.githubusercontent.com/88479559/218961857-3b1b0f4e-8ca0-4809-8b17-75260b3fa381.png)

**Comment by pepoviola** [comment]
Hey @iamAbasu7, thanks for reporting. Looks like an error mounting a volume. Which version of podman are you using? Are you running as root?

Thanks!

**Comment by iamAbasu7** [comment]
Hi @pepoviola , I am using podman version 3.4.2. No I am not running as root, but I have tried once but it was throwing the same error.

**Comment by wirednkod** [comment]
Hi @iamAbasu7 . I have been testing podman for some days now. Can you please provide the `.toml` and the steps you are following to run the above? Thank you

**Comment by wirednkod** [comment]
Closing this as stale. Please reopen if issue persists;
