### ISSUE TITLE
When specifying chain as polkadot-local collator does not produce blocks

### ISSUE THREAD

**Issue by sebastianmontero** [paritytech/zombienet#734]
Hi,

I'm trying to test a parachain with the polkadot-local chain spec, but the collator does not produce blocks, why might this be? when using rococo-local the collator produces blocks correctly. This is the zombinet config file:

```
[relaychain]
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]

chain = "polkadot-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 100
cumulus_based = true

  [parachains.collator]
  name = "pba-collator"
  validator = true
  command = "./target/release/hashed-parachain"
  args = ["--force-authoring"]

```

Thanks

**Comment by pepoviola** [comment]
Hi @sebastianmontero, thanks for the feedback. Did you compile polkadot with the [fast-runtime](https://github.com/paritytech/polkadot/pull/4332) feature? By default the epoch for polkadot is 4hrs so you need to wait that time to see the parachain start producing blocks. If you compile with the fast-runtime the epoch is set to 2mins and you have a way to quickly see your parachain producing blocks.

Thanks!!

**Comment by sebastianmontero** [comment]
Thanks @pepoviola, no I just downloaded the polkadot binary, do you know if there is an already built polkadot binary with the fast-runtime feature?

**Comment by pepoviola** [comment]
> Thanks @pepoviola, no I just downloaded the polkadot binary, do you know if there is an already built polkadot binary with the fast-runtime feature?

Hi @sebastianmontero, not that I'm aware. You need to clone and compile the binary with that feature flag.
Thanks!!

**Comment by pepoviola** [comment]
Hi @sebastianmontero, closing here, Please re-open if needed.
Thanks!
