### ISSUE TITLE
Make `.zndsl` file extension mandatory for tests

### ISSUE THREAD

**Issue by wirednkod** [paritytech/zombienet#744]
Add a check for `.zndsl` extension of filename, when tests are running

**Comment by pepoviola** [comment]
This will need a `pr` in polkadot/cumulus/substrate to update the extension.

**Comment by wirednkod** [comment]
> This will need a `pr` in polkadot/cumulus/substrate to update the extension.

Just [opened one in cumulus](https://github.com/paritytech/cumulus/pull/2215). Substrate tests are already in `.zndsl` format while the polkadot ones were renamed [some time ago](https://github.com/paritytech/polkadot/pull/6073).
