### ISSUE TITLE
Dangling resources in K8S

### ISSUE THREAD

**Issue by emamihe** [paritytech/zombienet#746]
Hi @pepoviola 
There is an issue for cleaning up the process after the simulations test finished but then they will be ended up with lots of dangling resources in kubernetes including CronJobs and PodMonitors in different namespaces including default, gitlab and monitoring namespaces.

The reason behind for creation of Error faced pods is that after the CJ scheduled for terminating the needed resources. this time format recurs everyday based on the time set. so it is needed in the script after the running in scheduled time then it should also remove the supervisor CJ also in order to not repeating the re-running of the job.

and also the same happens for podmonitors which is mainly used for scraping the metrics into the local prometheus to have the visibility in grafana. the podmonitors which spins up in monitoring namespaces it sustains there and need to have some correction to terminate that resource as well.

**Comment by pepoviola** [comment]
fixed in https://github.com/paritytech/zombienet/pull/747 .
