### ISSUE TITLE
Create docker image for `arm64`

### ISSUE THREAD

**Issue by pedroapfilho** [paritytech/zombienet#753]
I was installing zombienet from docker hub to run it, but then I saw that it doesn't have support for `arm64`, making it very tricky to run.

This could be mitigated by having support for `arm64`, and adding documentation for how to run it properly.

**Comment by pedroapfilho** [comment]
Context, when I fetch the image from the hub: https://hub.docker.com/r/paritytech/zombienet and try to run it using:

```sh
docker run paritytech/zombienet:latest
```

it gives me:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

**Comment by wirednkod** [comment]
Thank you @pedroapfilho 

We have a [relative issue](https://github.com/paritytech/zombienet/issues/710) about this so I will close this as duplicate. You can follow the discussion on the other issue: https://github.com/paritytech/zombienet/issues/710
