### ISSUE TITLE
[bug] No way to teardown network with podman

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#757]
Since with `podman` provider zombienet is exiting after spawn and there is no easy way to teardown the network. Only with `podman rm ...` manually.

**Comment by pepoviola** [comment]
Hi @l0r1s, did you send SIGINT before complete launch? because iirc the issue is that the process exit after the network is spawned instead of keep alive as does with `native/k8s`.

Thanks!

**Comment by wirednkod** [comment]
@l0r1s not fixed yet - in my todo list
