### ISSUE TITLE
Add option to disable logs in `@zombienet/orchestrator`

### ISSUE THREAD

**Issue by tjjfvi** [paritytech/zombienet#787]
I'm attempting to use the programmatic API of `@zombienet/orchestrator` in Capi, and it works almost perfectly... except that it makes a lot of logs that we want to suppress. As a result, instead of being able to simply write
```ts
const network = await start("", config, options)
return network
```
We would have to instead write
```ts
const child = new Deno.Command(Deno.execPath(), {
  args: [
    "run",
    "-A",
    import.meta.resolve("./zombienet_worker.ts"),
    JSON.stringify([config, options]),
  ],
  stdout: "piped",
  stderr: "inherit",
}).spawn()
for await (const line of readLines(readerFromStreamReader(child.stdout.getReader()))) {
  if (!line.startsWith("capi_network = ")) continue
  const network = JSON.parse(line.slice("capi_network = ".length)) as Network
  return network
}

// zombienet_worker.ts
import { LaunchConfig, start } from "npm:@zombienet/orchestrator"

const [config, options] = JSON.parse(Deno.args[0]!) as [LaunchConfig, Parameters<typeof start>[2]]

const network = await start("", config, options)

console.log(`capi_network = ${JSON.stringify(network)}`)
```
This is far from ideal, but it would greatly simplify our zombienet integration in capi if we could bypass the CLI and use the API directly.

I see no way to disable the logs from `@zombienet/orchestrator` without modifying `console.log`, which would affect everything else in the realm. Ideally, the logs could be disabled by passing a parameter to the `start` function (or similar).

**Comment by pepoviola** [comment]
Hi @tjjfvi, thanks for the feedback! I think a nice way to approach to this is add the `quiet` option to the `start` function and suppress any output when is set to `true` (`false` by default).

@wirednkod  maybe we can add a `module` level flag to print or not in `cliTable`, wtdyt?

Thanks!!

**Comment by tjjfvi** [comment]
> I think a nice way to approach to this is add the `quiet` option to the `start` function and suppress any output when is set to `true` (`false` by default).

Yes, this would be perfect!

**Comment by tjjfvi** [comment]
Thanks for fixing this so quickly! When might this change get released?

**Comment by wirednkod** [comment]
> Thanks for fixing this so quickly! When might this change get released?

I am preparing next release at this moment @tjjfvi

**Comment by wirednkod** [comment]
> Thanks for fixing this so quickly! When might this change get released?

[Release 1.3.40](https://github.com/paritytech/zombienet/releases/tag/v1.3.40) is there
