### ISSUE TITLE
[para decorator] Error when running parachain 

### ISSUE THREAD

**Issue by sweatpotato13** [paritytech/zombienet#789]
When I running relay chain and parachain with zombienet, it comes error below

![SS](https://i.imgur.com/xZz8x5d.png)

I using parachain as [this](https://github.com/sweatpotato13/substrate-parachain-boilerplate/tree/manual-seal) repository

Is nimbus consensus is can be problem?

**Comment by pepoviola** [comment]
Hi @sweatpotato13, looks like the `chain-spec` generated is wrong (missing the `nimbus` field). Can you share your `toml` file? Also, can you check if the plain `chain-spec` contains this field?

Thanks!

**Comment by sweatpotato13** [comment]
[wisp-local-1001-rococo-local-plain](https://justpaste.it/6jiga)

It seems nimbus field doesnt exist... hmm

**Comment by pepoviola** [comment]
> [wisp-local-1001-rococo-local-plain](https://justpaste.it/6jiga)
> 
> It seems nimbus field doesnt exist... hmm

Thanks, yes. There is an `aura` field. Can you share your `toml` config?
Thanks!

**Comment by sweatpotato13** [comment]
```
[relaychain]
default_command = "../polkadot/target/release/polkadot"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 1001
chain = "wisp-local"
cumulus_based = true

	# run alice as parachain collator
	[[parachains.collators]]
	name = "alice"
	validator = true
	command = "./target/production/wisp"
	args = ["-lparachain=debug", "--alice"]
```

here is my zombienet toml config

**Comment by pepoviola** [comment]
Thanks! I don't see any `nimbus` field in here
https://github.com/sweatpotato13/substrate-parachain-boilerplate/blob/manual-seal/node/src/chain_specs/wisp.rs#L68

Did you manage to running locally?

Thanks!!

**Comment by sweatpotato13** [comment]
> Thanks! I don't see any `nimbus` field in here https://github.com/sweatpotato13/substrate-parachain-boilerplate/blob/manual-seal/node/src/chain_specs/wisp.rs#L68
> 
> Did you manage to running locally?
> 
> Thanks!!

Local will work fine with no issues. 
can also create Chainspecs as normal.

**Comment by sweatpotato13** [comment]
Any updates?

**Comment by pepoviola** [comment]
> ```json
> nimbus
> ```

Hi @sweatpotato13, sorry about the delay. In this case we need to add your network to our `parachains decorators registry` to override the `key`s management that zombienet does. 
Every key needs `aura`, `nimbus` and `vrf` ? 

Thanks!!

**Comment by pepoviola** [comment]
Hi @sweatpotato13, if you can send us the repo info and the customizations you need for your chain we can work on this one.
Thanks!
