### ISSUE TITLE
updating the image for getting rid of kubectl auth warning

### ISSUE THREAD

**Issue by emamihe** [paritytech/zombienet#803]
In order to get rid of the warning for auth in new k8s api server we need to update the image used for gitlab pipelines which is used here https://github.com/paritytech/zombienet/blob/main/scripts/ci/docker/zombienet_injected.Dockerfile 
I tried it once, but seems some artifacts are missing
```
Step 11/26 : COPY ./artifacts/packages ./packages
COPY failed: file not found in build context or excluded by .dockerignore: stat artifacts/packages: file does not exist
```
In order to update the the k8s to the latest version we need to do this. and just new build of the image can help since the new auth plugin is already included for installation of kubectl in the image:

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/33328203/226339030-acb9e7c0-77f6-48ff-a020-f93d70842fae.png">

**Comment by pepoviola** [comment]
Hi @emamihe , the `gke-gcloud-auth-plugin` should be installed in the image build in our CI

https://gitlab.parity.io/parity/mirrors/zombienet/-/jobs/2573917

Thanks!

**Comment by pepoviola** [comment]
Hi @emamihe, can we close this one now? The image should be updated.
