### ISSUE TITLE
Metric matching consistency

### ISSUE THREAD

**Issue by sandreim** [paritytech/zombienet#82]
Currently, we have these interfaces to parse/assert metrics:
- natural language to query metrics (for example block height, or peer count) - `Alice: reports peers count is at least 1 within 150 seconds`
- query by name - `alice: reports pvf_preparation_time_bucket{le="10"} is 1`

This provides a sugary syntax for the tests as in you write less, but behind the scenes the metric prefixes (`substrate`, `polkadot`) are being prepended to the metric names based on naming logic inside zombienet. 

We should follow the pattern in Polkadot/Substrate so that we explicitly define the metrics and not rely on any prefixes that are added later. It will make tests more explicit and decouples the zombienet implementation from the Polkadot/Substrate metrics.

**Comment by sandreim** [comment]
This is for later after we finish the Polkadot test suite and of course debatable.

**Comment by pepoviola** [comment]
Closing here, already built support for full prefix query.
Thx!
