### ISSUE TITLE
Make console output mutable in Moonbeam decorator

### ISSUE THREAD

**Issue by timbrinded** [paritytech/zombienet#885]
### Issue Description

As part of the Moonbeam decorator, we add some console logging for the genesis authority. Whilst this can be useful, can we add an option to mute this by default, or move the level to debug/trace?

https://github.com/paritytech/zombienet/blob/c535f7d06c6b50a939c4c6aeada6b4a5f07cb4fc/javascript/packages/orchestrator/src/paras-decorators/moonbeam.ts#L45

### Steps to reproduce the issue

Steps to reproduce the issue
1. run a zombie network via orchestrator, for a minimal moonbeam setup
  a. `await zombie.start("", path, { silent: true });` 
2. Regard the console output

### Describe the results you received

Something along the lines of this gets printed:
```
        👤 Added Genesis Authority alith - 5HEL3iLyDyaqmfibHXAXVzyQq4fBqLCHGMEYxZXgRAuhEKXX
[Object: null prototype] {
  mappings: [
    [
      '5HEL3iLyDyaqmfibHXAXVzyQq4fBqLCHGMEYxZXgRAuhEKXX',
      '0xf24FF3a9CF04c71Dbc94D0b566f7A27B94566cac'
    ]
  ]
}
```

### Describe the results you expected

No output unless otherwise requested. There is no other network information printed to console, this shouldn't be any different.

### Zombienet version

"@zombienet/orchestrator": "^0.0.34"

### Provider

Native

### Provider version

```yaml
polkadot 0.9.40-a2b62fb872b
moonbeam 0.30.0-3bb936c32e1
```

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Adds noise to logs but not a functional issue

### Screenshots

![image](https://user-images.githubusercontent.com/79199034/229473002-f733dc1c-e625-4f38-91da-845c226809b5.png)

**Comment by wirednkod** [comment]
Thank you for reporting this @timbrinded 
Will tackle it down

**Comment by wirednkod** [comment]
@timbrinded the "problem" is that you are using the `console.log` inside the moonbeam decorator instead of the zombienet's appoach of table logging, using the
```
import { CreateLogTable } from "@zombienet/utils";
```
If the logging is replaced with:
```
import { CreateLogTable, decorators } from "@zombienet/utils";

.....

  new CreateLogTable({
    colWidths: [30, 20, 70],
  }).pushToPrint([
    [
      decorators.cyan("👤 Added Genesis Authority"),
      decorators.green(node.name),
      decorators.magenta(chainSpec.genesis.runtime.authorMapping),
    ],
  ]);
  ```
  
  That will do the trick; The silent applies to the logs that are generated from the LogTable as can be seen [here](https://github.com/paritytech/zombienet/blob/main/javascript/packages/utils/src/tableCli.ts#L101-L103);
  
  Would you like me to alter the moonbeam code or you prefer to do it?

**Comment by timbrinded** [comment]
I saw that it was console.log, but happy for it to be moved to the idiomatic way of doing it. Thanks!
