### ISSUE TITLE
Multi-parachain environment with polkadot-parachain in latest zombienet release

### ISSUE THREAD

**Issue by girazoki** [paritytech/zombienet#891]
The following file passed to the latest zombienet release (1.3.43) is unable to create blocks for one of the chains. In particular, one of the head data is not inserted in the relay.

The same file with the 1.3.37 worked.

```
[settings]
timeout = 1000

[relaychain]
default_image = "paritypr/polkadot-debug:master"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"

  [[relaychain.nodes]]
  name = "bob"

  [[relaychain.nodes]]
  name = "charlie"

  [[relaychain.nodes]]
  name = "dave"

[[parachains]]
id = 1000

  [parachains.collator]
  name = "collator01"
  command = "polkadot-parachain"

[[parachains]]
id = 2000

  [parachains.collator]
  name = "collator02"
  command = "polkadot-parachain"
```

Cumulus release: v0.9.38
Polkadot release: v0.9.38

**Comment by pepoviola** [comment]
Hi @girazoki, I reviewed this and there is a bug (race condition) in the latest release. As workaround you can set the `-c 1` (concurrency for spawning to one) and will work as expected, just slower :(

I will fix this asap. Thanks again for reporting :)

**Comment by pepoviola** [comment]
Hi @girazoki, this should be fixed in the latest version. I will close here, please re-open or ping me if you have questions.

Thanks!
