### ISSUE TITLE
Custom chain spec modifications

### ISSUE THREAD

**Issue by Fahrrader** [paritytech/zombienet#892]
We'd like to further modify generated chain-specs before chains are launched with them, in particular using our tool [chainql](https://github.com/UniqueNetwork/chainql), with a possibility to edit both human-readable and raw specs. An example where this would be useful is to store some current data from another chain's storage into the chain spec to launch the test network with.

A way to implement this would be to allow custom CLI commands be stored in the network description (.toml / .json) and be executed with the chain spec **after** all other modifications to it that Zombienet already provides.

I'm ready to implement this and draft a PR, if you approve of this motion. If this warrants further discussion, I'm happy to talk. :)

**Comment by pepoviola** [comment]
As reference, questions about this issue are in the [pr](https://github.com/paritytech/zombienet/pull/909).
Thx!

**Comment by pepoviola** [comment]
Hi @Fahrrader, closing here. Thanks for your feedback and this initiative.
Thx!
