### ISSUE TITLE
[Request] Add custom port support for native provider

### ISSUE THREAD

**Issue by timbrinded** [paritytech/zombienet#896]
## Description
Currently the [network definition](https://paritytech.github.io/zombienet/network-definition-spec.html) file doesn't seem to support setting ports for parachain collators, but only the relaychain nodes. Setting parachain collator ports via the generic args array will error due to it already being set by the dynamic port assignment feature.

Whilst elaborate topologies should be implemented via podman/k8 setups, for simple `native` provider networks it is not unreasonable to have predictable port numbers on collator nodes (especially for parachain development teams). If there is already a way to achieve this, feel free to say what that method is.

## Suggestion

Allow us to override dynamic port behaviour for parachain collators, for example:

> Add `wsPort` | `rpcPort` | `p2pPort` to `Collator` interface type and update `cmdGenerator.ts` (or otherwise) to respect collator network spec overrides.

**Comment by timbrinded** [comment]
you're right @zzccppp 

closing!

**Comment by pepoviola** [comment]
Hi @timbrinded, the collator config allow to set the same ports as the relay-chain node.

```ts
ws_port?: number;
rpc_port?: number;
prometheus_port?: number;
p2p_port?: number;
```
Thanks!!
