### ISSUE TITLE
Native provider nodes not killed on error

### ISSUE THREAD

**Issue by timbrinded** [paritytech/zombienet#897]
### Issue Description

Node binaries launched via zombienet native provider, are not killed when the parent process is forcibly exited (process code 1,2 etc). This is problematic during developement as leftover processes can intefer with test runs unless you remember to kill them off manually before launching new tests.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Launch the most basic example network e.g. `zombienet spawn ./examples/0000-test-config-small-network.toml --provider native`
2. Kill the zombienet process in another tab e.g. `pkill node`
3. Check for running binaries e.g. `pgrep polkadot`

### Describe the results you received

The two nodes launched by zombienet are still running

### Describe the results you expected

I was expecting the nodes to be spawned as `ChildProcess`es to zombienet, with onExit triggers so that when it dies, the nodes die with them too. (chop off the head and the body should wither). 

### Zombienet version

1.3.43

### Provider

Native

### Provider version

```yaml
polkadot 0.9.40-a2b62fb872b
```

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### Screenshots
![Screencast from 04-04-23 13_49_15](https://user-images.githubusercontent.com/79199034/229798929-f732bbeb-3d7c-4ca4-a20f-f3b6375b4881.gif)

**Comment by pepoviola** [comment]
Hi @timbrinded, we added the `SIGTERM` handler as part of the reference `pr`.  Using `pkill node` should work as expected. Also, worth notice that we can't listen the `SIGKILL` signal, so if you use `kill -9 <pid>` the spawned process will continue running.
Ping me if you have questions, thanks!!
