### ISSUE TITLE
[Feature Request] Ability to test against bad network conditions

### ISSUE THREAD

**Issue by melekes** [paritytech/zombienet#903]
**In the future, it would be nice for zombienet to provide an API for injecting network issues.** 

Zombienet clusters and internal testnets are usually spawned within a single data center, where network speeds are often close to optimal. Unfortunately, in the real world things are not so ideal. Therefore, I'd propose to extend zombienet functionality w/ ability to simulate bad & adversary network conditions. Sort of how [Jepsen](https://jepsen.io/) provides an [API for splitting the network into halves (or majorities)](https://jepsen-io.github.io/jepsen/jepsen.nemesis.html#var-partition-halves). 

Here is the list of things I think we want in the first approximation:

1. introduce latency, packet loss & jitter (`tc & netem` on Linux) for all connections of the given peer
2. isolate the single peer from the rest of the network for the given period (`iptables` on Linux)
3. partition the network into two groups (halves, majority & minority) (`iptables` on Linux)

(1) can be simplified into multiple predefined options: "slow", "50_loss", etc.

_Slightly unrelated, but killing random nodes (chaos engineering; using tools like https://github.com/asobti/kube-monkey) also sound like a good idea to me._

Curious to hear your thoughts on this 🙏

How hard would it be to implement something like this? Are there existing tools for Kubernetes that give you control over network? What zombienet API would look like?

---- 
UPDATE:

Adding individual issues to track progress:

- [ ] https://github.com/paritytech/zombienet/issues/927
- [ ] https://github.com/paritytech/zombienet/issues/928
- [ ] https://github.com/paritytech/zombienet/issues/929

**Comment by pepoviola** [comment]
Hi @melekes, thanks for bring this topic. We have `chaos-mesh` implementation in our roadmap, since at the moment we have the the `CRD` installed in our cluster (k8s) with [chaos-mesh](https://chaos-mesh.org/) but we don't expose any way to configure the scenario for the test. We also want to explore how we can implement similar features between the rest of the providers (native/podman).

I think implementing some set of predefinen scenario's for (1) could be a good step forward to explore how we can expose a useful config/api from zombienet.

**Comment by pepoviola** [comment]
Hi @altonen / @melekes, I added individual tasks and use this issue as umbrella to represent this feature in the zombienet roadmap. Thanks!!

**Comment by altonen** [comment]
Thanks. @melekes informed that he'd be interested in helping with this so if you're busy with other stuff, he could probably do some of the tasks. I think he's OoO right now but when he gets back he'll probably be in contact with you.

**Comment by pepoviola** [comment]
Sounds good! Yes, we can touch base with @melekes when his back :)

**Comment by wirednkod** [comment]
Moved to https://github.com/paritytech/zombienet-sdk/issues/15

**Comment by pepoviola** [comment]
Hi @melekes / @altonen, add `delay` using chaos-mesh with `k8s` as provider is now supported in the latest release. At the moment you can only set the `delay settings` in the network definition and will be injected at spawn phase.

You can check an example [here](https://github.com/paritytech/zombienet/blob/main/tests/chaos/0001-delay.toml).
We will continue working on moving this feature to other providers (podman/native) and to allow add/remove/modify as part of the `testing` phase through our D.S.L.

Thx!

**Comment by altonen** [comment]
Thanks for the info @pepoviola, I'll git it a go soonish when things have settled down a little

**Comment by pepoviola** [comment]
Great, we will continue working to add more functionalities and also port those to other providers.
Thx!
