### ISSUE TITLE
Error launching specific Zombienet config.

### ISSUE THREAD

**Issue by dudo50** [paritytech/zombienet#908]
### Issue Description

Following config results into following issues on Mac and on Ubuntu
Config available here: https://github.com/paraspell/ui-v2/blob/Zombienet-Upgrade/paraspell-zombienet-config.toml
Guidance on replicating issue can be found here: https://github.com/paraspell/ui-v2/tree/Zombienet-Upgrade#zombienet-linux

Results into following errors.
Any idea? (Podman)
Linux:
<img width="816" alt="Screenshot 2023-04-08 at 18 34 52" src="https://user-images.githubusercontent.com/55763425/230732840-1f57da68-4c72-4a64-9037-fcf0f122f346.png">
MacOS:
<img width="956" alt="Screenshot 2023-04-08 at 18 28 08" src="https://user-images.githubusercontent.com/55763425/230732852-19d4c105-c0fe-4db3-8b4a-a19eb06082d2.png">

**Comment by pepoviola** [comment]
For reference, the `linux` issues is because the config doesn't include the `regestry` part for the image (e.g `docker.io/`). The macOS issue is still in investigation but is related to `podman` on mac.

Closing here.
Thanks!!
