### ISSUE TITLE
zombienet-linux-arm64 v1.3.43 Release doesn't work

### ISSUE THREAD

**Issue by zzccppp** [paritytech/zombienet#915]
### Issue Description

download zombienet-linux-arm64 from release and run but received the MODULE_NOT_FOUND error;

### Steps to reproduce the issue

Steps to reproduce the issue
1. download zombienet-linux-arm64 from release 
2. run it without any parameters

### Describe the results you received

``` bash
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/snapshot/javascript/packages/cli/dist/cli.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

### Describe the results you expected

It should print the help information

### Zombienet version

v1.3.43

### Provider

Native

### Provider version

```yaml
No provider used
```

### Upstream Latest Release

Yes

### Additional environment details

OS: Ubuntu 22.04.2 LTS aarch64
Host: Orange Pi 5
Kernel: 5.10.110-rockchip-rk3588
Uptime: 5 days, 19 hours, 32 mins
Packages: 861 (dpkg)
Shell: bash 5.1.16
Terminal: /dev/pts/1
CPU: (8) @ 1.800GHz
Memory: 2171MiB / 15718MiB

**Comment by pepoviola** [comment]
Closing here, can you re-try with the latest version. Thx!
