### ISSUE TITLE
[infra] Simulate bad network conditions

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#927]
- Add support to set:

- [x] latency
- [x] packet loss
- [x]  jitter

We should support in the available providers:
`k8s` through chaos-mesh CRD (installed in the cluster)
`native` ( tc & netem on Linux)
`podman` (need exploration).

**Comment by wirednkod** [comment]
Moved to https://github.com/paritytech/zombienet-sdk/issues/16

**Comment by pepoviola** [comment]
re-open since we want to implement this as part of v1 with the scope of `k8s`
