### ISSUE TITLE
Error running astar and moonbeam

### ISSUE THREAD

**Issue by rubenguc** [paritytech/zombienet#942]
### Issue Description

I'm trying to running a network with astar and moonbeam and I get an "Invalid JSON" error when it's running.

config.toml:
```
[relaychain]
default_command = "./bin/polkadot"
default_args = [ "-lparachain=debug" ]
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  ws_port = 9900
  extra_args = [ "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  extra_args = [ "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "charlie"
  validator = true
  extra_args = [ "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "dave"
  validator = true


[[parachains]]
id = 1282
chain = "moonbeam-local"

  [parachains.collator]
  name = "alith"
  ws_port = 9910
  command = "./bin/moonbeam"

[[parachains]]
id = 2006
chain = "astar-dev"

  [[parachains.collators]]
  name = "collator1"
  ws_port = 9920
  command = "./bin/astar-collator"
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. Make a folder and copy zombienet there
2. Create a bin folder inside the previous one and copy the binaries (I uploaded them for testing purposes: [binaries](https://drive.google.com/drive/folders/17AT3dm4JpOdjjK3ejsIzkrTXrWZbLZ7M?usp=share_link))
3. Create config.toml inside the folder
4. run:
```
./zombienet-macos -p native spawn config.toml
```

### Describe the results you received

uncaughtException
Error: Invalid JSON (Unexpected "d' at position 44328 in state STOP )
at Parser.charError ( /snapshot/javascript/node_modules/jsonparse/jsonparse. js: 90:16)
at Parser.write (/snapshot/javascript/node modules/isonparse/isonparse.is: 154:23)
at Stream. <anonymous> (/snapshot/javascript/node_modules/JSONStream/index. js: 23:12)
at Stream.write (/snapshot/javascript/node_modules/through/index. js: 26:11)
at ReadStream. ondata (node: internal/streams/readable: 754:22)
at ReadStream. emit (node: events: 527:28)
at addChunk (node: internal/streams/readable:315:12)
at
readableAddChunk (node: internal/streams/readable:285:11)
at ReadStream. Readable. push (node: internal/streams/readable: 228:10)
at node: internal/fs/streams: 275:14

### Describe the results you expected

The network should be running with a specification table for the chains with their endpoints, etc

### Zombienet version

1.3.43

### Provider

Native

### Provider version

```yaml
## For binaries
polkadot 0.9.40-a2b62fb872b
moobeam 0.31.1-e85c6107f21
astar-collator 5.4.0-8120cd78a3b
```

### Upstream Latest Release

Yes

### Additional environment details

I'm using macbook Pro M1

### Additional information

I have uploaded the temporary folder generated by zombienet in case you need it for anything: https://drive.google.com/file/d/19h69Uu1ve1hFJkedTo1EIlUxxbagUUkY/view

### Screenshots

console error: 
![Screenshot 2023-04-19 at 2 23 09 PM](https://user-images.githubusercontent.com/45153592/233174374-e5735bc2-923e-4279-a399-90b7fbf091b6.png)

generated json files:
![Screenshot 2023-04-19 at 2 26 26 PM](https://user-images.githubusercontent.com/45153592/233174486-64aec67d-cbd2-4fe3-97be-ff8e52fd0617.png)

folder structure:
 
![Screenshot 2023-04-19 at 8 04 01 AM](https://user-images.githubusercontent.com/45153592/233174675-50573baf-8581-4c79-9627-e3f5b8eeceae.png)

**Comment by pepoviola** [comment]
Hi @rubenguc, thanks for posting this issue. Is similar to this question in SE (https://substrate.stackexchange.com/questions/8174/error-running-astar-parachains-with-zombienet)? Could be a chain-name issue in the config?

Thanks!

**Comment by rubenguc** [comment]
> Hi @rubenguc, thanks for posting this issue. Is similar to this question in SE (https://substrate.stackexchange.com/questions/8174/error-running-astar-parachains-with-zombienet)? Could be a chain-name issue in the config?
> 
> Thanks!

No, I have tried many combinations with the chain name and id but I kept getting the same error. I noticed that the configuration I posted only works once, if I want to run it again I have to restart my laptop. 

I changed polkadot binary to v0.9.37 and the config worked, but I think there is something wrong with moonbeam (moonbase or moonriver too) parachain. I'm not able to create assets or send xcm transaction to relay chain. In Alith log I see this:

![Screenshot 2023-04-24 at 10 19 28 PM](https://user-images.githubusercontent.com/45153592/234158457-324bbf34-bd49-4920-ba4d-cfd2bebf430b.png)

This is the last run I tried today:
```
[relaychain]
default_command = "./bin/polkadot"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  ws_port = 9900
  extra_args = [ "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  extra_args = [ "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "charlie"
  validator = true
  extra_args = [ "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "dave"
  validator = true


[[parachains]]
id = 1287
chain = "moonbase-local"

  [parachains.collator]
  name = "alith"
  ws_port = 9910
  command = "./bin/moonbeam_3"
  args = ["-lparachain=debug"]

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
```

Here is the zipped temporary folder if you want to see it: : https://drive.google.com/file/d/1GN4mYSh9v_y4vYSiE4oALbbjrqP4L8Bv/view?usp=share_link
