### ISSUE TITLE
Getting `UnhandledRejection: ReferenceError: fetch is not defined`

### ISSUE THREAD

**Issue by skunert** [paritytech/zombienet#972]
### Issue Description

When running a zombienet test with `--provider native`, I am getting an error message.
```
UnhandledRejection:      ReferenceError: fetch is not defined
```
Zombienet version: 1.3.43, binary downloaded from the releases page.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Clone cumulus
2. cd into repo
3. `zombienet --provider native spawn zombienet/tests/0007-full_node_warp_sync.toml`

### Describe the results you received

```
UnhandledRejection:      ReferenceError: fetch is not defined
```

### Describe the results you expected

Test runs

### Zombienet version

1.3.43

### Provider

Native

### Provider version

```yaml
latest master, locally compiled
```

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by pepoviola** [comment]
Hi @skunert, thanks for reporting this one. I will fix asap.
Thanks!

**Comment by pepoviola** [comment]
Fixed in https://github.com/paritytech/zombienet/pull/976. And will be part of the next release, I plan to release today.
Thanks!

**Comment by pepoviola** [comment]
Fixed in https://github.com/paritytech/zombienet/releases/tag/v1.3.44 .
Closing here, please re-open if needed.
Thanks!!
