### ISSUE TITLE
Customizable metrics prefixes

### ISSUE THREAD

**Issue by kamilsa** [paritytech/zombienet#974]
### Is your feature request related to a problem? Please describe.

We were trying to integrate KAGOME into the zombienet, and it almost worked. The only missing thing is that zombienet expected prometheus metric with `substrate_` prefix, while in KAGOME we have `kagome_`. 
Eg **substrate**\_process_start_time_seconds instead of **kagome**\_process_start_time_seconds.

### Describe the solution you'd like

It would be convenient to customize prefix metric. This could be done as new parameter. For example:
```
  [[relaychain.nodes]]
  name = "bob"
  command = "./bins/kagome"
  prometheus_prefix="kagome"
```
Default value for `prometheus_prefix` could be `substrate` for backwards compatibility

### Additional context

KAGOME is a C++ implementation of Polkadot host. We have parachains support, live validator in westend. Would be great to add more tests into our CI using zombienet

https://github.com/soramitsu/kagome

**Comment by wirednkod** [comment]
Thank you @kamilsa for this; 
Have you considered creating a decorator in order to accomplish it?
You can see how `moonbeam` is [doing something similar](https://github.com/paritytech/zombienet/blob/main/javascript/packages/orchestrator/src/paras-decorators/moonbeam.ts#L141-L143)

**Comment by pepoviola** [comment]
Hi @kamilsa, thanks for your feedback and also cool project! The `decorator` will not work out of the box here since is designed for `parachains`.  I think the config per node make sense and we can set `substrate` as `default`. 
We will trying to implement and ping your for testing.
Thanks!

**Comment by wirednkod** [comment]
hey @kamilsa - PR https://github.com/paritytech/zombienet/pull/1001 is introducing this feature;
Can you please let us know if KAGOME is released as an image - in order to add it in our tests for the specific feature?

Thank you

**Comment by kamilsa** [comment]
@wirednkod sure. Please try `soramitsu/kagome:latest`
